### PR TITLE
Fix credential cache not being used, forcing re-authentication for every download

### LINKED ISSUE #1168: Write credentials to cache only if they are changed
**Is your feature request related to a problem? Please describe.**
A minor problem. When login with cached credentials and `store_credentials` is `true` in call to `Session::connect()` the file with cached credentials is written every time `Session::connect()` is called. The contents of the file usually do not change with these writes.

**Describe the solution you'd like**
The file with cached credentials should be written only if cached credentials have changed (have been updated by Spotify).

**Describe alternatives you've considered**
Set `store_credentials` to `false` and use code that writes credentials to cache if they are changed.
https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/blob/ea26d0d6d50bc0fd394c8934b14d18266671264b/audio/spotify/src/common.rs#L162

**Additional context**
Problem was noticed in: https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/merge_requests/1195

### PR DESCRIPTION
**Pull request by Laiteux**
Fixes #1168!

This PR makes the cache work, reusing `auth_data` from the credential cache.

Even faster downloads now, since no authentication has to be done again every time.

This is my first time working with Rust at all, so please let me know if anything could/should have been done better (:

### CODE REVIEW

**Comment by Laiteux** [comment]
Also, let me know if I should make a PR for the `dev` branch too. I went with `master` because this is what the project I use is on.

**Comment by Laiteux** [comment]
This would however still use the cache even if the user attempted to switch accounts.

I thought of comparing usernames, but that isn't safe because the user can also authenticate using their email.

A possibility would be to store the email/login in the credential cache too, and compare. Thoughts?

**Comment by oSumAtrIX** [comment]
The PR target should be set to `dev`. https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by kingosticks** [comment]
The PR you link to is solving a very specific problem, which it does solve. I think the problem you have described is different.

The use of cached credentials (or not, your PR breaks this) should be handled outside of `Session::connect` by the calling code and passed in via the `credentials` parameter. I assume your calling code is not doing this properly, the correct fix lies in that code, not librespot.

**Comment by kingosticks** [comment]
The bundled program in this repo does this properly, you can also see an example in use [here](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/blob/main/audio/spotify/src/common.rs?ref_type=heads#L132-L150).

Please do fix the downstream application Doing this wrong will only draw attention, which I don't think will be good news for anyone.

**Comment by Laiteux** [comment]
Can you please elaborate on

- the correct fix lies in that code, not librespot" - what is "that code"?

- "The bundled program in this repo" - what repo?

I'm not fluent enough in Rust for now to elaborate a proper PR, probably. Maybe I can come back to it later as I'm still learning, for now it seems it works for my use case. lmk

**Comment by oSumAtrIX** [comment]
He is referring to the upstream code that uses librespot to do it like this:

https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/blob/main/audio/spotify/src/common.rs?ref_type=heads#L134-160

**Comment by Laiteux** [comment]
I see. So the issue has to be fixed from the impl. Then, this PR should be closed?

**Comment by kingosticks** [comment]
I was referring to the example application that is contained in this repository. You can find it  at https://github.com/librespot-org/librespot/tree/dev/src

The gstreamer stuff is another example.

Yes, close this PR, it's not necessary.

**Comment by Laiteux** [comment]
Alright, closing. But then what's the point of this credential cache if it doesn't reuse what it's caching?

**Comment by kingosticks** [comment]
Because it's a library, it can be used many different ways, not everyone wants it to work the same way you do. So the caller needs to handle this aspect. You can see this in the two examples I provided as in they both work differently.

**Pull request closed without merging**
