### PR TITLE
symphonia_decoder tweak

### PR DESCRIPTION
**Pull request by JasonLG1979**
* Remove unwrap

* Refactor normalisation_data.

### CODE REVIEW

**Comment by kingosticks** [comment]
What's the difference replacing the returns with breaks? I personally find that harder to parse.

**Comment by JasonLG1979** [comment]
Functionality none. It's just a style choice. If you're in a loop you should use loop statements IMHO.

**Comment by JasonLG1979** [comment]
It really doesn't matter that much to me. Consistency in style is the most important thing really. If the consensus is to use returns than we should always use return and any use of break in the codebase in that situation should be changed to return.

**Comment by kingosticks** [comment]
I can see value in break expressions in the examples used in the rust docs but not so much when trying to return the value from the entire function. I doubt we have any other break expressions used like this (if any at all).

**Comment by JasonLG1979** [comment]
If that is the convention and consensus that's fine. There's a break in the buffer loop in the the ALSA backend that I will change to return.

**Comment by JasonLG1979** [comment]
@kingosticks I've reverted the "return to break" part of the commit but while looking at `symphonia_decoder.rs` I noticed a case of a "returning break" and took the opportunity to improve `normalisation_data` a bit. (at least I think it's an improvement?)

**Comment by JasonLG1979** [comment]
In that particular case it would be really nice if we could just get the latest metadata without looping. I might see what I can do at [symphonia](https://github.com/pdeljanov/Symphonia)? I haven't looked at the source but I would imagine the underlying metadata revisions are stored as some kind of vec maybe? It shouldn't be hard to just get the latest off the end without looping though it?

**Comment by roderickvd** [comment]
I don’t know, you’d have to ask @pdeljanov. Might have to do with a moving cursor like with decoding samples.

**Comment by JasonLG1979** [comment]
Upon further reading I'd also like some clarification about a couple options. So if anyone (@roderickvd and/or @pdeljanov) have any further insight that would be great.

`FormatOptions`, `prebuild_seek_index` and `DecoderOptions` , `verify`.

The docs are pretty vague but on face value they both seem like good ideas it's just a matter of if they're even applicable to the formats we care about or if they have any major downsides?

**Comment by pdeljanov** [comment]
Hi @JasonLG1979,

Regarding skipping to the latest metadata revision: the interface is purposefully designed to make a user iterate over the revisions for two reasons. The first is to get them to pop off old revisions from the queue to prevent a pseudo memory leak.  The second is because Symphonia doesn't try to guess how metadata should be used. For example, a revision could be a completely new set of tags or it could only contain an updated set of tags. It is an application specific decision, though I'd wager the former is the case the majority of the time.

Regarding `DecoderOptions::verify`, this asks decoders that have the ability to verify the decoded output against a provided checksum to do so. The result is provided after you call `Decoder::finalize`. This option is only useful if you play the track from start to finish with no seeks. It's currently only supported by the FLAC decoder. It's off by default because of the aforementioned limitations that render is pretty useless for a music player. Its main purpose is to verify the integrity of the file.

`FormatOptions::prebuild_seek_index` asks format readers to pre-scan the file to build a seek index if one isn't provided. This is useful for formats that do not have per-packet timing information (e.g., MP1/2/3, ADTS). While the option is present, it isn't implemented by any public branch of Symphonia.

**Comment by JasonLG1979** [comment]
@pdeljanov Thanks!!!

I'll continue the discussion about the metadata in my PR.

> Regarding DecoderOptions::verify, this asks decoders that have the ability to verify the decoded output against a provided checksum to do so. The result is provided after you call Decoder::finalize. This option is only useful if you play the track from start to finish with no seeks. It's currently only supported by the FLAC decoder. It's off by default because of the aforementioned limitations that render is pretty useless for a music player. Its main purpose is to verify the integrity of the file.

> FormatOptions::prebuild_seek_index asks format readers to pre-scan the file to build a seek index if one isn't provided. This is useful for formats that do not have per-packet timing information (e.g., MP1/2/3, ADTS). While the option is present, it isn't implemented by any public branch of Symphonia.

Ok, good to know. Neither is of any use to us then.

**Pull request merged**
