### PR TITLE
Update deps round 2

### PR DESCRIPTION
**Pull request by JasonLG1979**
Let's see if this will blow up or not?

### CODE REVIEW

**Comment by JasonLG1979** [comment]
We know it's going to fail 1.53...

**Comment by roderickvd** [comment]
If you commit `.github/workflows/test.yml` then I think you can bump MSRV to 1.56 and see how it goes in the CI.

**Comment by JasonLG1979** [comment]
I want to make sure jack works. On my fedora machine I can't install the jack build deps because they conflict with PipeWire. I'll need to ssh into my server and build there if there's a jack issue to see if I can fix it.

**Comment by JasonLG1979** [comment]
Winner, winner chicken dinner!!!

I can't change the workflow via the cli. I'll have to do that manually.

**Comment by JasonLG1979** [comment]
Looks good to me for a 0.4.1.

**Comment by roderickvd** [comment]
Thanks mate. I'll run some checks and hopefully get 0.4.1 out of the door, this time with an updated `Cargo.lock`.

**Comment by JasonLG1979** [comment]
No problem. Sorry if I seem argumentative.

**Comment by roderickvd** [comment]
All good, thanks. 🍻

**Pull request merged**
