### PR TITLE
Feature flags for top level crate

### PR DESCRIPTION
**Pull request by jwiesler**
I added feature flags to the top level crate to avoid compiling a lot of unecessary packages when just using audio or core and being unable to pull in just the respective subcrates.

### CODE REVIEW

**Comment by sashahilton00** [comment]
Why not just use `librepot-audio` or `librespot-core` directly if you need to use only particular bits of functionality?

**Comment by Johannesd3** [comment]
There are two different models: Use one big crate and feature flags ([Tokio](https://github.com/tokio-rs/tokio/tree/master/tokio)), or use many small crates and one crate to re-export all the smaller crates ([Futures](https://github.com/rust-lang/futures-rs)). You would like to combine both ways, but I think that makes it just more complicated.

**Comment by jwiesler** [comment]
I think you are completely right with what you say, but the feature flags approach is more general: I forked the repo and can't choose at all what to compile since Cargo does not allow to import subcrates from a "git" dependency (correct me if I'm wrong).

**Comment by Johannesd3** [comment]
Yes, I think you're wrong: If you specify the crate name, cargo will automatically look in the whole workspace, but I'm not sure either.

**Comment by jwiesler** [comment]
Yes that actually works, thanks.

**Pull request closed without merging**
