### PR TITLE
Handle reset and decode errors with the Symphonia decoder.

### PR DESCRIPTION
**Pull request by pdeljanov**
This change fixes the handling of the `ResetRequired` error. By propagating the `ResetRequired` error up, the next Spotify track will be advanced to. This should be perfectly acceptable behaviour for librespot.

This change also modifies the decode loop to skip corrupted packets when they're encountered. If the decode error is propagated up then the next track will be advanced to which seems undesirable.

I tested these changes with about 15 or so songs.

### CODE REVIEW

**Comment by roderickvd** [comment]
Thanks for your contribution to `librespot` and of course Symphonia in the first place!

Just so I get this right, other than what we are already doing in `seek`, there can be no `ResetRequired` result from `self.format.next_packet()` for us to call `self.decoder.reset()`?

Skipping corrupted packets is a nice enhancement. We will however need to take care and report the new playback position to Spotify. Currently we only report that when we are lagging, not when we are ahead because that might be due to buffering of the backends. I have an idea about this though, which I'll implement after this is in.

Would you do the honours of running `cargo fmt`?

**Comment by pdeljanov** [comment]
Whoops, the formatting should be fixed now.

Let me try to explain things in more detail.

All of this will be from the point-of-view of Symphonia only. In this explanation, a "track" is a track within the format reader  (`OggReader`, `Mp3Reader`, etc.), and a "decoder" is an instance of `Mp3Decoder`, `VorbisDecoder`, etc.

It's important to note that aside from the packets produced by a format reader, there is no communication between a format reader and a decoder. This is so you can mix-and-match them, as well as use external libraries. For example, Symphonia should be able to decode packets from FFMpeg and vice-versa.

However, this disconnect will create a problem when you seek because seeking causes a discontinuity in packets. For example, if you seek from T=1s to T=10s there's a discontinuity of ~9s of audio (and an equivalent amount of packets).

Some decoders need to use information from previous packet(s) to decode the current packet. Therefore the discontinuity causes problems. This is the *only* reason why decoders have a `reset` function. It clears the internal state of the decoder to prevent audio glitches.

---

The `ResetRequired` error is for a completely different problem.

In the context of `FormatReader::next_packet`, `ResetRequired` is returned when the tracks within the container are replaced. When this occurs you must create a **new** decoder. This is because there are no guarantees the new track(s) even use the same codec.

In other words, you keep the same instance of format reader, but because the tracks within the format reader have been replaced, you need to instantiate new decoders.

This error is used to support a feature of OGG called "chaining".

In OGG a group of tracks (the official name for a track is "logical stream") are combined into a single "physical stream". For example, a video file may combine two audio tracks, one video track, and five subtitle tracks into a single physical stream.

A physical stream ends when all the logical streams making up the physical stream end.

However, what OGG allows is for a **new** physical stream to begin after the last one ends. Within the next physical stream, there will be a completely different set of tracks. When `OggReader` detects the start of a new physical stream, it returns the `ResetRequired` error and expects the user to replace the previous set of decoders with a new set that can decode the new tracks.

OGG is primarily a streaming format, so this feature can be used to create a continuous stream from many different files. Essentially, to create a continuous audio stream you can just append one OGG file after another.

This isn't a case librespot needs to deal with so I made the change to allow the `ResetRequired` error to propagate up. In the odd case that it is encountered, the propagated error will switch to the next *Spotify* track rather than continuing with the chained audio. Handling this case properly is more complex, and I don't expect you'd ever see it.

---

In the context of `Decoder::decode`, `ResetRequired` is returned when the signal specification of the audio buffer changes.

For example, if there were a codec that could dynamically change sample rate, this error would be returned when it switches from sample rate A to B. Again, this is something we don't need to support in librespot since none of the codecs you use will do this. Therefore, I just let the error propagate up in the impossible chance it does occur. :)

---

I hope this explanation is far more clear!

Unfortunately, without background knowledge it's difficult to get these ideas across via. an API definition.

Do you think it would help if `FormatReader::next_packet` returned an error named `TracksReplaced` instead? I feel like this may be more clear and specific.

Thanks!

**Comment by roderickvd** [comment]
Great write-up, thanks so much!

> Do you think it would help if `FormatReader::next_packet` returned an error named `TracksReplaced` instead? I feel like this may be more clear and specific.

I think my mix-up came from the apparent connection between `Decoder::reset` and `ResetRequired` -- they sound like they are the same, but I now understand that they are not. Anything that removes this apparent connection would make things clearer, I think.

I am not sure if `TracksReplaced` is the most exact. From what I understand there's a *new* track encountered in the container next, rather than one that replaces the current one. (A matter of perspective I guess whether you look at it from either the format or decoder.) I offer my suggestions to describe state like `NewTrack` or be more in the imperative mood like `ReloadDecoder`. The former may be better because a decoder it does not imply a decoder is actually present.

**Comment by roderickvd** [comment]
In a33014f9c5ae40125098a28394ffc7fc034e8f63 we notify Spotify of our new track position when we've skipped malformed data.

**Pull request merged**
