### PR TITLE
Improve discovery

### PR DESCRIPTION
**Pull request by JasonLG1979**
This is a wip atm.

### CODE REVIEW

**Comment by roderickvd** [comment]
Since this is a WIP, do you want to convert this PR to draft?

**Comment by roderickvd** [comment]
You may want to hold up on this one. I'm pretty far with removing `unwrap` and `expect` everywhere except the player. Will push to `new-api` soon.

**Comment by roderickvd** [comment]
Panics were removed in the latest #891 commits. Depending on the scope of this PR, you may want to rebase on `new-api` and submit a PR to my branch instead.

**Comment by JasonLG1979** [comment]
I think it would probably be easier just to close this and see where the dust settles. From the sound of things you've rendered this PR basically moot. I can't wait for you to finish the new API stuff. It's looking like a vast improvement.

**Pull request closed without merging**
