### PR TITLE
New dynamic limiter for very wide dynamic ranges

### PR DESCRIPTION
**Pull request by roderickvd**
Well that was a fun exercise! This time I actually think I know what I'm doing.

The current dynamic limiter was an amateur attempt that worked within a limited range and first Rust code I ever wrote. This time I took a article from the Journal of the Audio Engineering Society [1] and wrote a fresh implementation of the most recommended variant (feed-forward in the log domain with a smooth, decoupled peak detector).

So far it seems to work beautifully, including the tracks with wide dynamic range in the linked issue. Would be nice if some of you could give this a spin on various genres and let me know how it goes.

I purposely changed the field names to signal developers downstream that some of these fields now hold values in a different unit. Before in `0.2.0` this caused distorted audio for some other applications and I'd like to prevent that this time.

Closes: #934

[1] [Giannoulis, D., Massberg, M., & Reiss, J.D. (2012). Digital Dynamic Range Compressor Design—A Tutorial and Analysis. Journal of The Audio Engineering Society, 60, 399-408](https://github.com/librespot-org/librespot/files/7850566/GiannoulisMassbergReiss-dynamicrangecompression-JAES2012.pdf)

### CODE REVIEW

**Comment by acid-sun** [comment]
I fond another track.
```
[2022-01-12T13:50:58Z INFO  librespot_playback::player] <Danse Macabre, Op. 40,R.171> (442693 ms) loaded
[2022-01-12T13:50:58Z WARN  librespot_playback::player] This track will at its peak be subject to 7.44 dB of dynamic limiting.
[2022-01-12T13:50:58Z WARN  librespot_playback::player] Please lower pregain toavoid.
[2022-01-12T13:50:58Z DEBUG librespot_playback::player] Normalisation Data: NormalisationData { track_gain_db: 5.923416, track_peak: 0.94552505, album_gain_db:1.1973114, album_peak: 0.9883812 }
[2022-01-12T13:50:58Z DEBUG librespot_playback::player] Calculated Normalisation Factor for Track: 197.77%
```
All sounds good. I like it. Thank you.

**Comment by roderickvd** [comment]
Great to hear. One more report would be great for me to merge this with confidence.

**Comment by JasonLG1979** [comment]
I will give it a test. There are a couple tracks that I know of that distort.

**Comment by JasonLG1979** [comment]
So far so good. The entire Bush, Sixteen Stones album was pretty bad with the old limiter 
( https://open.spotify.com/album/5IJm0boSQuEBLiYNZJKV2Y?si=5q4kkdqFRWOFdQatWWUVdQ ) It's honestly not much better with the new limiter but it's at least somewhat tolerable. Even without a limiter it's really bad. It's a fuzzy, squished hot mess full of inter-sample peaks I'd guess. A victim of the loudness wars and "more me" mixing.

**Comment by JasonLG1979** [comment]
I do notice that it uses a little bit more CPU though. Maybe 2%-ish more on my Raspberry Pi 4. That should still be fine on a Pi Zero I would think though. It should still be under 30%.

**Comment by roderickvd** [comment]
> So far so good. The entire Bush, Sixteen Stones album was pretty bad with the old limiter
> ( https://open.spotify.com/album/5IJm0boSQuEBLiYNZJKV2Y?si=5q4kkdqFRWOFdQatWWUVdQ ) It's honestly not much better with the new limiter but it's at least somewhat tolerable. Even without a limiter it's really bad. It's a fuzzy, squished hot mess full of inter-sample peaks I'd guess. A victim of the loudness wars and "more me" mixing.

Oh man that's definitely a throwback! Can't remember much often I played that album back in the days. A lot.

However with the default pregain of 0.0 I don't think the dynamic limiter kicks in at all? The tracks indeed suffer from very low dynamic range. The average ReplayGain for these tracks is around -10 dB. The peaks then all stay under threshold.

> I do notice that it uses a little bit more CPU though. Maybe 2%-ish more on my Raspberry Pi 4. That should still be fine on a Pi Zero I would think though. It should still be under 30%.

Yeah, that's quite possible. Though the code is short and sweet, there are more things going on now that the CPU has no intrinsics for. Like linear <> logarithmic conversions, twice for every sample.

**Comment by roderickvd** [comment]
Now that you mentioned it I do have some ideas to optimize this when we aren’t attacking or releasing a peak.

**Comment by roderickvd** [comment]
dce7944 is a little more efficient and hasn't broken anything right?

**Comment by JasonLG1979** [comment]
Yep, that cut it from about 2% to about 1%,lol!!!

LGTM

After you merge this and your `--device` fix I'll release a new version of Raspotify. I'm sure if there's any bugs they'll show themselves.

**Comment by roderickvd** [comment]
> > The tracks indeed suffer from very low dynamic range. The average ReplayGain for these tracks is around -10 dB.
> 
> I didn't read the logs but I want to say that Glycerine in track mode distorts?

I don't think so -- it's down -5.6 dB. If you mean that guitar, I do think that it clips but already in the recording and possibly even on the guitar amp. This is "Glycerine - Remastered" on "Sixsteen Stone (Remastered)": https://open.spotify.com/track/5buITai6eMzU8rJonMEI6e?si=962443be52484f34

> > [dce7944](https://github.com/librespot-org/librespot/commit/dce79440d1d26195990f0f32229bc7fcd9a58651) is a little more efficient and hasn't broken anything right?
>
> Yep, that cut it from about 2% to about 1%,lol!!!

Well, like it said on the tin 😆 I'll take it.
 
> After you merge this and your `--device` fix I'll release a new version of Raspotify. I'm sure if there's any bugs they'll show themselves.

For a final check maybe you can compare what Glycerine sounds like in an official Spotify client. On macOS, the official app sounds a little lower in volume, but the guitar no better.

> After you merge this and your `--device` fix I'll release a new version of Raspotify. I'm sure if there's any bugs they'll show themselves.

👍

**Comment by JasonLG1979** [comment]
Testing on my Pi Zero shows CPU usage in the high teens to low 20's. So it's about what I expected. 1% increase on the Pi 4 and 5-10% on the Pi Zero. Not great but not a deal breaker. Still plenty of headroom. When the new API work becomes more complete I will test that on the Zero.

**Comment by coderootme** [comment]
Wow! Thank you for this! I could never use the old dynamic limiter, because this song was always crackling:

```
[2022-01-16T16:19:01Z INFO  librespot_playback::player] Loading <Feel Like Going Home> with Spotify URI <spotify:track:0qMPttvKZkUXyDgNmZhKsY>
[2022-01-16T16:19:01Z DEBUG librespot_audio::fetch] File 8663bb953f40917e6c295a7e4ac96d06d0074ad2 already in cache
[2022-01-16T16:19:01Z DEBUG librespot_core::audio_key] new AudioKeyManager
[2022-01-16T16:19:01Z INFO  librespot_playback::player] <Feel Like Going Home> (292773 ms) loaded
[2022-01-16T16:19:01Z WARN  librespot_playback::player] This track will at its peak be subject to 7.47 dB of dynamic limiting.
[2022-01-16T16:19:01Z WARN  librespot_playback::player] Please lower pregain to avoid.
[2022-01-16T16:19:01Z DEBUG librespot_playback::player] Normalisation Data: NormalisationData { track_gain_db: 1.2700005, track_peak: 0.81324977, album_gain_db: 0.3600006, album_peak: 1.0166621 }
[2022-01-16T16:19:01Z DEBUG librespot_playback::player] Calculated Normalisation Factor for Track: 230.94%
```

Now the limiter is finally useful!

**Comment by roderickvd** [comment]
Glad to hear it’s appreciated ❤️

**Pull request merged**
