### PR TITLE
Bump MSRV to 1.53

### PR DESCRIPTION
**Pull request by WhyNotHugo**
See: https://github.com/librespot-org/librespot/pull/997

### CODE REVIEW

**Comment by kingosticks** [comment]
And see #979

**Comment by WhyNotHugo** [comment]
Not sure if it's desirable to update dependencies too or if it's best to do that separately.

**Comment by roderickvd** [comment]
Yeah, let's do this. Would you please also add a changelog entry indicating that this is a breaking change? I'll merge it after.

**Comment by WhyNotHugo** [comment]
Oh, CI failures are already present in master, so not caused by this PR.

**Comment by roderickvd** [comment]
Yeah we'll see about that CI failure later, which is only for the ARM target.

Also after merging these pulls I'd like to get `new-api` up to speed. I think there will be some conflicts also from earlier commits, that we should resolve before it's going too stale. Can then release this as `0.4` and promote `new-api` to `dev`.

**Comment by WhyNotHugo** [comment]
Why do you cross-compile on CI rather than just have a workflow run on ARM natively?

**Comment by roderickvd** [comment]
For no good reason other than that it was already there when I got on board. If you can change the actions to do a native build, then be my guest to put in a PR! Indeed I'd rather test ARM as a platform than testing cross-compilation.

**Comment by kingosticks** [comment]
I don't think Travis had any support for ARM and it didn't get upated when we switched.

**Pull request merged**
