### PR TITLE
Update old-api

### PR DESCRIPTION
**Pull request by JasonLG1979**
Bump deps and clean up a couple clippy lints

### CODE REVIEW

**Comment by JasonLG1979** [comment]
@roderickvd I think the failure may be related to the rust version used for CI as everything builds fine on my machine with the current rust stable version. Can we bump it to 1.61?

**Comment by JasonLG1979** [comment]
Ok now I'm getting:

```
error: failed to compile `cargo-hack v0.5.22`, intermediate artifacts can be found at `/tmp/cargo-installKSXt8B`

Caused by:
  failed to select a version for the requirement `toml_edit = "^0.15"`
  candidate versions found which didn't match: 0.[14](https://github.com/librespot-org/librespot/actions/runs/3349614252/jobs/5549784083#step:9:15).4, 0.14.3, 0.14.2, ...
  location searched: crates.io index
  required by package `cargo-hack v0.5.22`
```

Is CI broken on this branch?

**Comment by JasonLG1979** [comment]
Stable, beta and nightly builds fine, with the fairly normal network error (that has nothing to do with the build) on stable.

**Comment by JasonLG1979** [comment]
Much better. The only failed test is a network error. What say you @roderickvd?

**Comment by JasonLG1979** [comment]
I'm not sure what you'd call this? It changes really nothing from the perspective of a user or consumer other than some potential bug fixes in librespot's deps. `v0.4.3`?

**Comment by kingosticks** [comment]
If there isn't a issue in librespot that these new deps fix I'm not sure a release/tag makes sense, even a minor one. I've certainly never done this.

**Comment by roderickvd** [comment]
Thanks for the update. I’m with @kingosticks  on the release. Certainly a Rust edition change to 2021 is breaking and warrants a new major release. But we already have a v0.5 target branch with updated crates and Rust edition so this PR seems a bit stuck between a rock and a hard place.

**Comment by JasonLG1979** [comment]
> If there isn't a issue (edit: or security vulnerability) in librespot that these new deps fix I'm not sure a release/tag makes sense, even a minor one. I've certainly never done this.

So you don't periodically update the deps of the software you write? 

You let it just sit and rot? Software does not age like fine wine.

**Comment by JasonLG1979** [comment]
> Thanks for the update. I’m with @kingosticks on the release. Certainly a Rust edition change to 2021 is breaking and warrants a new major release. But we already have a v0.5 target branch with updated crates and Rust edition so this PR seems a bit stuck between a rock and a hard place.

The edition can prob be changed back to 2018. But other than that every now and then until dev is released we're going to need to bump the deps. Unless you want this branch to basically be abandoned ware?

**Comment by JasonLG1979** [comment]
There. THat doesn't change the edition nor the MSRV. It just changes the version used by CI.

**Comment by JasonLG1979** [comment]
That should constitute a "patch" level version bump. Nothing in librespot's API, MSRV nor Edition changes.

**Comment by JasonLG1979** [comment]
We really should do this every so many months on a regular schedule for our current releases so they don't rot.

**Comment by JasonLG1979** [comment]
Whatever I guess. If the condenses is to let released version rot and to tell people to use dev if they want up to date crates then so be it I guess. I'll just run `cargo update` in my build script so at least my users get the dep bump and the potential bug and security fixes.

**Comment by kingosticks** [comment]
I'm not stuck in the world of cargo pinning particular versions, no. But even if I was, assuming the software still works (no issues or vulnerabilities) then no, zero update required and no "rot". Software doesn't rot like food.

**Comment by JasonLG1979** [comment]
> I'm not stuck in the world of cargo pinning particular versions, no. But even if I was, assuming the software still works (no issues or vulnerabilities) then no, zero update required and no "rot". Software doesn't rot like food.

There are 3 options:

1. Leave it as is to let it *potentially* rot.

2. Meticulously and constantly pick though librespot's deps and update when needed.

3. Run run cargo update every now and then and update the current librespot version with a patch release.

**Comment by JasonLG1979** [comment]
I don't care though. I'm not fighting the pushback. Do what you want.

**Comment by kingosticks** [comment]
Sorry, why can't we just merge the update and not cut a release? Why is this all or nothing?

**Comment by JasonLG1979** [comment]
> Sorry, why can't we just merge the update and not cut a release? Why is this all or nothing?

So you want to not include the updates for projects that pull in librespot via cargo? What would even be the point of merging the update then?

**Comment by JasonLG1979** [comment]
It doesn't matter to me. I don't pull in librespot via cargo and as mentioned I can just run cargo update in my build script. So I'm going to mute this convo. If anyone wants to be a responsible maintainer they can replicate this PR pretty easily.

**Comment by roderickvd** [comment]
> Whatever I guess. If the condenses is to let released versions rot and to tell people to use dev if they want up to date crates then so be it I guess.

I don't know man :shrug: I was fine merging your latest commit but minutes later you pulled the plug? You can't expect me to reply by the minute, you know. I was at the hospital visiting my wife.

> If anyone wants to be a responsible maintainer they can replicate this PR pretty easily.

Thanks for the vote of confidence :-1:

For someone who volunteers his time and only ever tries to be friendly and sensible, I find these rage quits or whatever they discouraging and undeserved. Second time in a row this week.

I am about done policing MSRV, SemVer and release policies :wave:

**Comment by JasonLG1979** [comment]
> I don't know man  I was fine merging your latest commit but minutes later you pulled the plug? You can't expect me to reply by the minute, you know. I was at the hospital visiting my wife.

It's not about the lack of immediate response it's about the amount of pushback for a very basic and responsible thing.

> Thanks for the vote of confidence -1

That was more to @kingosticks who loves to chime in but doesn't actually commit any code at all.

> For someone who volunteers his time and only ever tries to be friendly and sensible, I find these rage quits or whatever they discouraging and undeserved. Second time in a row this week.

I also volunteer my time. This was me trying to upstream something extremely basic and common sense and getting way to much pushback. This was not a rage quit. This was me seeing that it wasn't worth my time as I can do it myself in Raspotify. I simply wanted all librespot consumers benefit.

**Comment by JasonLG1979** [comment]
I looked at the other PR. He is right IMHO. If this is happening a lot it may not be us. It's probably you.

**Pull request closed without merging**
