### PR TITLE
Fix broken streaming mode

### PR DESCRIPTION
**Pull request by Johannesd3**
e71a004e93d9376bb30834416cdd9248ad521246 broke the streaming mode, this PR fixes my mistake.

### CODE REVIEW

**Comment by Johannesd3** [comment]
This is a rather grave issue, is this change ok for you?

**Comment by ashthespy** [comment]
I will have a look over the weekend!

**Comment by ashthespy** [comment]
@Johannesd3 I haven't had the time to look into the implementation in detail - I played around a bit and it seems so follow the old behaviour of adding the file to cache after the fetch is complete..
So LGTM!

**Review by ashthespy — APPROVED** [review]

**Comment by Johannesd3** [comment]
Then I'll go ahead

**Pull request merged**
