### PR TITLE
Don't panic when the computed MAC doesn't match the client's expected MAC

### PR DESCRIPTION
**Pull request by kingosticks**
This just handles this error situation more gracefully. I randomly made up the JSON result error codes/strings. 

There's also a couple of other tiny fixes.

### CODE REVIEW

**Comment by sashahilton00** [comment]
Are there any undesirable side effects from dropping that assert statement? Haven't had the chance ot test. Will wait for feedback from OP on #289 if that works for you.

**Comment by kingosticks** [comment]
I don't believe so, since I'm still checking they are equal and simply skipping the new credentials so it's as if they were never received. I've tested it by intentionally corrupting the shared key and it seems fine. The client didn't switch (as before) but then you can try again since librespot didn't crash. 

I guess I don't know what's supposed to happen if you had an active session (A), then you try and switch to (B) and that switch fails. Session A will remain active but is that correct? Is the client that initiated the switch OK with that? An additiinal change could be to shutdown session A, so nothing is left active. Maybe that state (nothing active) is a better place to be following an error?

Either way, I still think not crashing is an improvement. But happy to wait for further verification. It's entirely possible the original issue isn't fixed by this.

**Comment by sashahilton00** [comment]
@patrickjane let us know once you've tested this. if it works, we'll merge it.

**Comment by sashahilton00** [comment]
Closes #289

**Pull request merged**
