### PR TITLE
Move keymaster to core

### PR DESCRIPTION
**Pull request by sashahilton00**

### CODE REVIEW

**Comment by kingosticks** [comment]
How come the CI builds succeeded despite the apparently missing dependency?

**Comment by sashahilton00** [comment]
Hard to say, I was under the assumption that serde_derive was a fragment from the PST, but apparently it's required for some of the macros serve uses. Not entirely sure why the CI is fine with it, most likely the compiler misses it. Though I did try with it removed and it ran fine. I'm going to leave it in for now and merge, but I'd also be interested in why it's needed, since I don't see it in use anywhere

**Comment by sashahilton00** [comment]
Just realised I need to add serde_derive back to lib.rs

**Comment by sashahilton00** [comment]
For some reason the CI failed to downlaod resources for the beta. Built fine on other distros, and just tested locally with the beta. If no one has any objections/suggestions I'll merge this tonight.

**Comment by kingosticks** [comment]
Travis just needed a good kick :+1:

**Pull request merged**
