### PR TITLE
Harden systemd service, update restart policy

### PR DESCRIPTION
**Pull request by tlvince**
Running as `nobody` throws the following warning:

```
/usr/lib/systemd/system/librespot.service:9: Special user nobody configured, this is not safe!
```

Since it appears librespot doesn't require its own per-say, I've chosen [DynamicUser](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#DynamicUser=), which adds some sand-boxing niceties alongside.

I've also changed the [Restart](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=) policy to `on-failure` as it would otherwise restart on clean/0 exit codes.

### CODE REVIEW

**Comment by JasonLG1979** [comment]
Nice. I'm stealing the `SupplementaryGroups=audio` bit. We might also change `After=network-online.target` to just `After=network.target` as per [the docs on the subject](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/).

**Comment by JasonLG1979** [comment]
If you really wanted to lock down the system service it would look something like this:
```
[Unit]
Description=Librespot (an open source Spotify client)
Documentation=https://github.com/librespot-org/librespot
Documentation=https://github.com/librespot-org/librespot/wiki/Options
Requires=network.target audio.target
After=network.target audio.target

[Service]
DynamicUser=yes
SupplementaryGroups=audio
Restart=on-failure

# Add AF_UNIX if you want to be able to talk to PulseAudio
# Add AF_BLUETOOTH of you want to be able to talk to bluetooth
# AF_INET = ipv4
# AF_INET6 = ipv6
# AF_NETLINK = zeroconf
RestrictAddressFamilies=AF_INET AF_INET6 AF_NETLINK

# Some of these may be implied by DynamicUser=yes
RestrictRealtime=true
RestrictSUIDSGID=true
RestrictNamespaces=true
ProtectHostname=true
ProtectControlGroups=true
ProtectKernelLogs=true
ProtectKernelModules=true
ProtectKernelTunables=true
ProtectProc=invisible
ProtectHome=true
ProtectSystem=strict
ProtectClock=yes
DevicePolicy=strict
DeviceAllow=char-alsa rw
DeviceAllow=/dev/null r
DeviceAllow=/dev/random r
DeviceAllow=/dev/urandom r
PrivateTmp=true
PrivateUsers=true
ProcSubset=pid
NoNewPrivileges=true
PermissionsStartOnly=true
LockPersonality=true
MemoryDenyWriteExecute=true
RemoveIPC=true

CapabilityBoundingSet=

SystemCallFilter=@system-service
SystemCallFilter=~@privileged @resources
SystemCallErrorNumber=EPERM

# Make the cache dir 0600
#UMask=077
# Make a cache dir in /var/cache/foo (really /var/cache/private/foo)
# You can then do --cache /var/cache/foo
#CacheDirectory=foo

ExecStart=/usr/bin/librespot --name "%p@%H"

[Install]
WantedBy=multi-user.target
```

**Comment by JasonLG1979** [comment]
Changing:
```
Restart=always
RestartSec=10
```

To:
```
Restart=on-failure
```
Is also ill advised:

1. `Restart=always` => `Restart=on-failure` is pointless because the only difference is that `Restart=on-failure` doesn't restart on a clean exit. `librespot` will never exit cleanly on it's own. It will run forever, exit(1) or go down in flames. http://0pointer.de/public/systemd-man/systemd.service.html#Restart=

2. Removing `RestartSec=10` makes `librespot` restart in 100ms (the default) have fun spamming the shit out of your logs... http://0pointer.de/public/systemd-man/systemd.service.html#RestartSec=

**Comment by tlvince** [comment]
Thanks. I've reverted the `Restart` changes and updated `Requires`.

Not sure if it's a good idea to go the whole hog on the other sandboxing features (haven't read up on all the options tbh); would `ProtectHome=true` and `ProtectSystem=strict` (implied by `DynamicUser`) be enough?

**Comment by JasonLG1979** [comment]
I'm in the process of scream testing the Raspotify unit file. So far that's what I've come up with. Raspotify is a packaged version of librespot for Raspberry Pi's so it should be a good testing ground for what will work on Debian based systems.

**Comment by JasonLG1979** [comment]
Anything is better than what we have now though, which is basically nothing.

**Comment by JasonLG1979** [comment]
And it should be wants not requires.

**Comment by JasonLG1979** [comment]
Yep, derp on my part. Sound not audio,lol!!!

LGTM

**Comment by JasonLG1979** [comment]
Don't forget the change log though.

**Comment by tlvince** [comment]
Done, thanks.

(Sorry for all the commits; was trying [github.dev](https://docs.github.com/en/codespaces/the-githubdev-web-based-editor). Can you squash merge?)

**Comment by JasonLG1979** [comment]
> Done, thanks.
> 
> (Sorry for all the commits; was trying [github.dev](https://docs.github.com/en/codespaces/the-githubdev-web-based-editor). Can you squash merge?)

@roderickvd can.

Other than that it LGTM. Thanks!!!

**Comment by roderickvd** [comment]
Thanks for your contribution ❤️

**Pull request merged**
