### PR TITLE
Improve playback speed

### PR DESCRIPTION
**Pull request by kaymes**
I did some profiling to figure out why librespot is so much slower than the official Spotify client to start a playback. Of the issues I found, two were quick fixes, which I'm committing here.

1) seek() on an audio stream is a very slow operation here because under the hood we do an interval search over the file. Thus, many different parts of the file must be downloaded inspected. Librespot does such a seek when playing a file from the beginning. This is unnecessary.

2) the network requests for downloading the key and the encrypted file can be done in parallel which saves on round trip time.

### CODE REVIEW

**Comment by kingosticks** [comment]
What speedup do you see?

**Comment by chrisbp** [comment]
Awesome work @kaymes. I'm seeing significantly decreased load times when starting/switching tracks.

Some info on my test setup:
- Odroid C2 as the playback device running librespot
- 15 Mbit internet connection
- 200ms typical ping to Spotify access points
- 320 Kbit bitrate setting in librespot
- librespot audio cache disabled so tracks are always downloaded
- timed with stopwatch, so results are probably accurate to +- 1 sec. I've also taken into account that some tracks have silence at the start as well

On the current master build of librespot, typical 3-5 min tracks take 13 seconds after hitting play/next before I can hear any sound output. This increases to about 16 seconds when loading a 41 min track.

With the changes from this PR, 3-5 min tracks as well as the 41 min track are loaded and outputting sound in 1-2 seconds. Quite a difference compared to master.

**Comment by sashahilton00** [comment]
Thanks for looking into that. Haven't really done much there since running on 1gbps here, but glad to hear it's making a difference for those with slower broadband. If someone else is idling here and has slower internet, and you also get the chance to test, that would be great. Will try and review and merge in the next couple of days, though right in exams atm, so no promises.

**Comment by kaymes** [comment]
@kingosticks: I didn't do as thorough timings as @chrisbp, but my results are comparable. On my DSL connection, I get starting an un-cached track from the beginning from around 10 seconds down to 1-2 seconds.

Starting a track from the middle (e.g. when you transfer playback from the phone to librespot) is as slow as before because the seek() still needs to happen. The benefit of parallel downloading the two files is half a second, so you won't feel the improvement if you are impacted by the seek().

I'd like to get this down further to the sub-second reaction times of the official client. I've identified a promising way to speed things up further for both, playback from start and middle, but I'd need some help understanding some aspects of the code. I might open a separate issue to discuss this.

**Comment by michaelherger** [comment]
@kaymes this is really interesting. While I've never experienced these long waiting times myself, I do have users who claim it would take really long to start playback. In my implementation (the Spotty plugin for Squeezebox) I do pipe audio data out to the server's transcoding pipeline. But I'd hardly ever wait more than 5s to get playback.

What I think I've seen is that it depends on the hardware used, too. Eg. on my dev machine (Mac with SSD) I'd often get sound within a second. My main systems are an oldish Intel Atom based Linux box using disks, and a Pi 3B+ on SD card. There I'd see something around 5s. But I've had reports of users using the same Pi and OS ([piCorePlayer](https://github.com/piCorePlayer)) complaining about 15s buffering time.

Could you imagine that the storage would have a big impact on the buffering? I _think_ (not sure, tbh) that data is buffered in the temporary folder. If that was true, could using a slow SD card be responsible for the delays?

**Comment by kaymes** [comment]
@michaelherger the delays I've been looking at were all due to network operations. I added debug messages to my built and then timed them using "ts" to see what librespot does and how long it takes.

librespot splits up files into chunks of 128K. A chunk must be downloaded in full before the part of this part of the file can be accessed. Thus, when the stream player wants to access a certain position of the file, a minimum of 128K must be downloaded before the position is available.

Doing a seek() on the audio file does a search. Searching for position 0 (the beginning of the stream) works as follows: The stream player first inspects the end of the file (we need to download the last chunk). Then it inspects the middle of the file (another chunk). Then it inspects the 25% position of the file (another chunk). And so on until it reaches the beginning of the file. So basically, you have to download quite a few 128K chunks before you can start to play the file.

My change removes the needless search for the beginning of the file. Thus, now, only a single 128K chunk must be downloaded before playback can commence. This is the grunt of the speed up this PR provides.

If the file is in the cache already, all this delay goes away and playback starts pretty much immediately. Otherwise, it depends on how quickly you can download those chunks. All of this has nothing to do with the speed of the storage device, but only with the speed of your network connection (bandwidth and ping time to Spotify).

**Comment by michaelherger** [comment]
@kaymes thanks for these details. I'll give it a try.

**Comment by kingosticks** [comment]
@kaymes, OK fair enough. I think we just always need to he wary of performance improvements without data to demonstrate the benefits. A before and after timing comparison would make a good addition to the commit message. Along with your environment since, like @sashahilton00, I never noticed this issue on a 150 Mbps connection and being located physically near-ish to my Spotify access point. @chrisbp's data points are helpful in this regard (thanks!).

The official client downloads the next one or two tracks in the queue as soon as it's finished  downloaded the current track. If you start the client with the console logging switch you'll see messages about the 'sliding window prefetch' (or something like that). I guess the size of the sliding window might depend on a few things (connection speed? space available?). I'm not sure if such an optimisation belongs in librespot or not. 

@michaelherger, the currently downloading file is written to a temporary file, the location of which is system dependent but on any sane modern Linux distro this will be a tmpfs (i.e. in RAM). So SD card speeds won't come into play. But slow CPU speeds (rpi etc) must have an effect as its going to take longer to download and decrypt a bunch more data.

**Comment by michaelherger** [comment]
Interesting: while I've never seen this issue on my own environment, one of my users confirmed the improvement after I did a custom build for him applying the changes suggested in this PR. Thanks, guys!

**Comment by kingosticks** [comment]
I think these optimisations are great and they get my vote. 

@kaymes I was thinking about this a bit more and you'll be able to get audio to start a bit quicker if you reduce the audio sink start threshold setting. I know that's possible for ALSA and i would assume there's something similar for the other audio backends. The problem with changing it to something more aggressive is that you are end up basically tuning it to your particular system. And then you might find it actually results in much worse playback on someone else's system. It's maybe the sort of thing you'd want to be user-configurable (do we have enough options yet!?) 

You could also investigate the result of a smaller chunk size when trying to improve seek time. Or maybe even have just the first two chunks half size?

The speedups available if you start prefetching tracks is probably the best but that might also require something to monitor the space usage and evict old stuff. And maybe you also need to move it between RAM and disk since you'd be consuming a lot more space with it all, some of which wasn't even used. Actually, I guess you'd just say that you can only prefetch when the (on disk) cache is enabled. But my point is that it quickly gets complicated and we start thinking does it really belong in this *library*? I don't have that answer. 

Maybe you are already looking/have looked at some of these options? I'd be most interested in the chunk size (since it's by far the easiest to test/reason about).

**Comment by kaymes** [comment]
@kingosticks At the moment, the bottleneck is the way the blocks are downloaded. 128K should be just over three seconds of music at 320KBit and over 6 seconds at 160KBit. The current infrastructure only supports reading from any part of the block once the whole block is available. Thus, at the time we're starting to send audio to the device, we already have several seconds worth of data. My guess is, that today's CPUs are fast enough that decoding speed is negligible.

Thus, I dare say, improving the download strategy is where we can make the biggest impact.

A while ago, I made a test built with much smaller block sizes. While it is much more reactive for seek() and starting the playback, you start to get throughput issues pretty quickly. Thus, we need adaptive block sizes and a download strategy that caters well for both, seek() (random access of very small chunks) and playback (sequential read of large portions of the file).

I'll try to write something proper about my ideas to solve it in the next few days, but I'm a bit busy at the moment.

**Comment by sashahilton00** [comment]
@kaymes seeing as this is a fairly minor change, i'm happy to merge it without waiting for multiple testing feeedback. Do you want it merged now or do you want to wait for a bit whilst you examine the download strategy as mentioned in the previous comment?

**Comment by kaymes** [comment]
@sashahilton00 thanks, please merge it now.

**Comment by kaymes** [comment]
I just opened Issue #306 for discussing further improvement options.

**Comment by l3d00m** [comment]
This is really noticeable already, I love it. Thanks :)

**Pull request merged**
