### PR TITLE
Remove warning for Rodio on Alsa (fixed upstream)

### PR DESCRIPTION
**Pull request by roderickvd**
Fixed with the recent bump of the Rodio and cpal crates.

### CODE REVIEW

**Comment by roderickvd** [comment]
The build is fine but the CI is failing over some Spotify server error. Please rerun the tests or just ignore the results.

**Comment by Johannesd3** [comment]
Is the `Cargo.lock` already up to date?

I can't observe any CI failure, BTW

**Comment by roderickvd** [comment]
> Is the `Cargo.lock` already up to date?

Yes, this was merged in 222f9bbd01994f55160c3d226641c9e258eee7fd.

> I can't observe any CI failure, BTW

Neither do I, they must have run again.

**Comment by Johannesd3** [comment]
I added this test that tries to connect to the Spotify servers using the credentials `test` - `test` end expects an error "Bad credentials", but every now and then it fails... Recently, it even hung up. Maybe this test was a stupid idea.

**Pull request merged**
