### PR TITLE
upgrade coreaudio-sys, fixes some build errors on macos

### PR DESCRIPTION
**Pull request by herrernst**

### CODE REVIEW

**Comment by ashthespy** [comment]
I'm guessing this is just the result of running `cargo update` ? 
Any chance you could just bump `coreaudio-sys` and friends in a single commit?

**Comment by herrernst** [comment]
No, I've only updated the coreaudio-sys package by running `cargo update -p coreaudio-sys`. But `coreaudio-sys` [upgraded the bindgen dependency](https://github.com/RustAudio/coreaudio-sys/compare/cda0c954a89d2781f9e5edb375030d441f86e3b3...4cc3081b6ebb1c9367ef58e113f06bd3d5afc973#diff-80398c5faae3c069e4e6aa2ed11b28c0) which itself updated some dependencies.

If you want to be safe you can ignore my pull request and commit the result of `cargo update -p coreaudio-sys` yourself.

Thanks!

**Comment by ashthespy** [comment]
Sorry, this slipped under the radar, thanks!

**Comment by herrernst** [comment]
Thanks!

**Pull request merged**
