### PR TITLE
Simplify librespot-protocol build caching.

### PR DESCRIPTION
**Pull request by willstott101**
Whilst on my laptop the github desktop app cloned this repo with crlf line endings. This threw off the crc checking in the protobuf build script. Triggering a rebuild using protoc...

I'm on Windows and installing protoc is a fiddle. With the aim of very slowly making librespot easier to use and distribute on Windows I switched to using the `protobuf-codegen-pure` crate.

When playing with this I found out the existing string replacement technique could end up corrupting files.rs (if one checksum was a substring of another). That may only be possible when manually changing the checksums to trigger builds though...

Regardless I decided to just get rid of the shell/cksum/protoc dependencies altogether, and have a completely rust based build system for the protobuf files.

~When trying to get rid of the shell script I moved the CRCs to the lib.rs file. I'm also now using an existing crate to calculate the checksum as there's no need to be compatible with `cksum`.~

Now this PR removes the checksum system in favour of trusting cargo to run build.rs at the right times, and always re-generating the rust files. However the regenerated files are only written to disc (triggering a proper rebuild) when those resulting files have actually changed (whole-sale string comparison). This avoids all kinds of caching problems, and makes the code simpler IMO.

### CODE REVIEW

**Comment by ashthespy** [comment]
@willstott101 any reason #270 didn't work for you? It should do the same thing?

**Comment by willstott101** [comment]
@ashthespy so first off, I didn't notice that PR somehow... I guess I assumed it would be an obscure issue to be having as protoc is a pretty common dependency. Sorry about that, I didn't intentionally avoid adding to your patch.

You're right that it solves the large problem, and with a much smaller change. So perhaps I will close this and add to yours... however

I arrived at making the larger changes I did because when removing build.sh the process for including new proto files felt a bit confusing. You would have to add a reference in both files.rs and lib.rs which were previously both generated files. Instead I opted for a different approach of parsing lib.rs so there is only one source of the file list. In my opinion the regex based method [with the comments](https://github.com/librespot-org/librespot/pull/293/files#diff-d4c5bc97c295bf5c093ad83635490794) is clearer and more robust than what was there. But maybe using comments is a bit ugly to some...

Regardless the only blocker in your fix vs this one is the replacement of CRLF line endings. When cloning onto a windows machine using the GitHub desktop app it does that insane thing of swapping all the line endings. Obviously this then changes the checksums and causes a rebuild.

Honestly I'm not sure if I should close this now. In the next few days I'll try adding the CRLF resistance to your branch, and if that works alright for me and there's not much interest in my other changes then I'll close this.

Sorry again, I just didn't check properly.

**Comment by willstott101** [comment]
To be honest, I'm not sure the CRC stuff is all that necessary anyway. Replacing the proto generated modules every build will trigger a rebuild of the library every build AFAICT. Unless we regenerate every time build.rs is run into a temp folder, and only move the files in if they've changed. That would remove the checksum code dependency completely. Once the librespot-protocol object is built I don't _think_ it will get run again. So only a file change will trigger a rebuild. The reduced complexity might be worth the minor increase in build times?

If that's interesting to anyone I could have a look into that. Perhaps timing the code gen.

**Comment by sashahilton00** [comment]
Thanks for working on this, I've been meaning to review #270 as well for a while, so will look at both in the not too distant future, get a feel for which one is best to merge and do so hopefully.

**Comment by sashahilton00** [comment]
I think I agree with you on just regenerating the proto files on each build. The trade off of a few seconds on build time vs. less CRC boilerplate and code complexity is worth it imo. If anyone else has a view (@ashthespy?) feel free to chime in

**Comment by ashthespy** [comment]
Sorry for the sporadic responses - playing catch up with submissions ;-)
While there is quite some additional code complexity currently in the CRC calculation, it might just be worth coming up with a way to not regen the modules each time -  if my memory serves me right, it took more than few seconds to build `librespot-protocol`. But I might be wrong, I shall refresh my memory and play around with it again shortly!

**Comment by sashahilton00** [comment]
That's fair enough. I was building librespot on my dev machine, which could be the reason it only took a couple of seconds, would be good to hear from people if it's taking a significant amount of time, as we can stick with caching generated files if that's optimal.

I definitely think we want to lose the dependency of protoc though - it's wierd to setup, and one of the blockers to easy Windows builds. As a temporary solution, we could merge #270 now as that caches the generated files, then in the meantime we can test this PR in terms of added build time for generating definitions at build time. Let me know if that works for you guys.

**Comment by ashthespy** [comment]
A quick unscientific test - triggering a rebuild of `librespot-protocol` by changing a checksum leads to this on my system:
```
$ cargo build --release --no-default-features
   Compiling librespot-protocol v0.1.0 (/Spotify/librespot/protocol)
   Compiling librespot-core v0.1.0 (/Spotify/librespot/core)
   Compiling librespot-metadata v0.1.0 (Spotify/librespot/metadata)
   Compiling librespot-audio v0.1.0 (/Spotify/librespot/audio)
   Compiling librespot-playback v0.1.0 (/Spotify/librespot/playback)
   Compiling librespot-connect v0.1.0 (/Spotify/librespot/connect)
   Compiling librespot v0.1.0 (/Spotify/librespot)
    Finished release [optimized] target(s) in 1m 02s
``` 
This is based on #270 - but I don't think there will be a significant difference given this PR's mplementation of hashing being the only difference?

**Comment by willstott101** [comment]
Yeah it should be the same ballpark. You can print from the build script but you have to do `cargo build -vvvv` in which case timing the actual generation would be more interesting. Since I assume that will only happen if something else triggers a rebuild anyway. Also would be worth noting the time to run all files through protoc as I think we only run the one with a changed checksum atm?

Hopefully I will find time to investigate tomorrow

**Comment by sashahilton00** [comment]
>     Finished release [optimized] target(s) in 1m 02s

What system are you compiling this on? I'm just wondering if I didn't properly invalidate the checksum when testing, or if you're testing on a low end machine

**Comment by willstott101** [comment]
Since you're merging #270 I'll get a version working without any checksum stuff in this PR instead. Probably by comparing file contents wholesale. Generating the rust files seems pretty instantaneous, so I don't think we'll see any measurable slow down if we only do a rebuild when they've actually changed. i.e. Reset the mtimes or use a temp directory and mv from there.

I'm extremely new to Rust and doing anything takes a while... but I'll get there.

**Comment by sashahilton00** [comment]
No problem, sounds like a plan, take your time.

**Comment by willstott101** [comment]
Come to think of it there is probably an api for generating the rust files in memory... that would be a lot cleaner. A thought for tomorrow.

**Comment by willstott101** [comment]
This latest version uses a Regex to parse lib.rs and then generates all the relevant modules. These are only saved to their destination if the resulting code is different (check is done after removing crlf line endings).

Currently librespot-protocol takes about 40 seconds to build in `--release` on my laptop. This time doesn't change measurably if I comment out all the code generation and saving.

I haven't rebased and all of that jazz because I'm using the github desktop client on this machine. Which is completely abysmal. I'll rebase, and squash I guess, on my desktop soon.

This removes one dependency from master but adds a regex dependency. Could just parse using `std::sting::String` methods tbh.

**Comment by willstott101** [comment]
So I've just started getting my head around just how much you can fiddle with commits after pushing... git is mad.

This feels like the most straight forward solution to me. The regex is pretty simple

**Comment by ashthespy** [comment]
@willstott101 Doesn't this still need you to have `protoc` installed on your system? The idea behind switching to `protobuf_codegen_pure` was to avoid an external dependency and keep a pure Rust build process.

**Comment by willstott101** [comment]
`protobuf_codegen_pure` is just an API wrapper for `protobuf_codegen`, so that it matches the one for executing protoc. I'm just using the `gen` function of `protobuf_codegen` instead of the `gen_and_write` function that `protobuf_codegen_pure` uses. This is all still pure rust.

**Comment by willstott101** [comment]
Is there anything wrong with this? Every time I build I get 7 changed files in git cause of the CRLF fun, would be nice to get rid of that when working in other branches.

**Comment by willstott101** [comment]
I've re-based on master and removed the regex usage.

**Comment by gruenebanane** [comment]
Works fine for me in contrast to the master.

**Pull request merged**
