### PR TITLE
Upstream LibreELEC patch

### PR DESCRIPTION
**Pull request by simonpils**
Hello,
librespot for LibreELEC is [patched to notify Kodi of playback start/stop](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/addons/service/librespot/patches/librespot-01_notify_kodi.patch).
I have updated the patch for librespot 0.1.6 to work for librespot of the dev branch.
Would it be possible to upstream this patch to librespot?
This commit is the best I can do with my limited knowledge of librespot and Rust.
I expect that this commit needs to be adapted to suit librespot coding conventions.

### CODE REVIEW

**Comment by roderickvd** [comment]
Sure, upstream patches are welcome. They'll have to be somewhat generic though, we don't want `--notify-kodi` and in the future `--notify-foo` and `--notify-bar`.

Principally I think the behavior you are looking before should go with one of the existing event handlers here: https://github.com/librespot-org/librespot/blob/39fcbb83260d38c078f4e07c44b0fcf4e15e94cc/src/player_event_handler.rs.

**Comment by simonpils** [comment]
Thank you for your reply @roderickvd.
Using the existing event handlers would add a shell layer between librespot and its Python wrapper.
Would it be possible to add an event handler to log events to the standard error (`--log-events`), as the libreelec patch does?

**Comment by roderickvd** [comment]
We're already printing lots of stuff to `stdout` with the `--verbose` flag.

**Comment by JasonLG1979** [comment]
> Would it be possible to add an event handler to log events to the standard error

That sounds like an abuse of standard error to me.

**Comment by JasonLG1979** [comment]
> Using the existing event handlers would add a shell layer between librespot and its Python wrapper.
> Would it be possible to add an event handler to log events to the standard error (`--log-events`), as the libreelec patch does?

1. Don't abuse Standard Error. That's not what it's for. If someone were to use that flag and librespot were running as a service any and all things that handle services would rightfully interpret the output as an error.
 
2. If you want to handle events use the event handler.

3. Otherwise if that's not to your liking add what you need to the existing debug level messages in `spirc.rs` for state changes, use the verbose logging mode and parse `stdout`. (Still not a great idea our logs are already noisy enough IMHO)

IMHO `--onevent` is the best and most downstream agnostic solution. As soon as we accept `notify-kodi` we'll have 75 other non-compatible app specific flags and options.

**Comment by roderickvd** [comment]
Is anyone interested in implementing a more general solution or should I move to close this PR?

**Comment by roderickvd** [comment]
Closing for now but feel to reopen for a generic solution.

**Pull request closed without merging**
