### PR TITLE
Migrate to rust 2018 edition

### PR DESCRIPTION
**Pull request by marcelbuesing**
Migrated to rust 2018 edition using `cargo fix` and removed `extern crate` as this is redundant in Rust 2018. For more details about the transition [here](https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html).

### CODE REVIEW

**Comment by marcelbuesing** [comment]
Just noticed there is already a PR which duplicates this partially #391

**Comment by marcelbuesing** [comment]
@ashthespy I squashed your PR #391 from November and rebased it on top of master, I hope that's ok for you?

**Comment by marcelbuesing** [comment]
Not sure why beta and nightly is stuck, but it looks more like a CI to me.

**Comment by sashahilton00** [comment]
Indeed it is. I've removed some more stuff from the build cache, I think there might still be one line in `.travis.yml` that is invalid (`cargo clean -p...`), will look into fixing that. Have triggered a rebuild in the meantime. Closes #391. I think we'll just bite the bullet on cargo fmt and add it, seems like it's more stable now anyway.

**Pull request merged**
