### PR TITLE
remove deprecated and unused import

### PR DESCRIPTION
**Pull request by lrbalt**

### CODE REVIEW

**Comment by lrbalt** [comment]
strange. Travis does not pull in bytes 0.4.7 which introduces the deprecation warning??

**Comment by sashahilton00** [comment]
Likely due to the fact that travis caches crates. Try changing bytes in cargo.toml to 0.4.7 and recompiling

**Comment by sashahilton00** [comment]
Great. Tried just bumping the version number, but now it conflicts w/ other crates...

**Comment by lrbalt** [comment]
we may need to wait for a day or so to let the caches invalide?

**Comment by sashahilton00** [comment]
No, it just needed to have ```cargo update``` run against it. Ignore what I said about bumping the version number, wasn't thinking clearly. It should build now.

**Comment by lrbalt** [comment]
yes, all green now

**Comment by sashahilton00** [comment]
thanks, merged.

**Pull request merged**
