### PR TITLE
Feature flag for selecting dns service

### PR DESCRIPTION
**Pull request by sashahilton00**
Code for allowing one to use dns-sd instead of mdns with the ```--features "dns-sd"``` compile time flag. Documentation needs to be added. Review and suggestions welcomed.

### CODE REVIEW

**Comment by mherger** [comment]
I guess the downside of using dns-sd is that it would require avahi or similar to be running?

**Comment by sashahilton00** [comment]
To be honest, I'm not too sure. This pr is just my implementation of a feature flag because libreelec needs it apparently. I'm not really sure of the difference between mdns and dns-sd, hopefully the OP can provide some insight? Cc @awiouy

**Comment by awiouy** [comment]
@mherger the rationale is given in #13
By default, LibreELEC runs avahi, whose configuration can not be changed

**Comment by sashahilton00** [comment]
@awiouy can you build with feature ```with-dns-sd``` and confirm that it works with libreelec, and in the meantime if anyone sees a way to cleanup the code a bit, great. Once confirmed working, I'll merge, suggested improvements notwithstanding.

**Comment by awiouy** [comment]
Will do right away!

**Comment by awiouy** [comment]
Builds and runs! Thanks much!

**Pull request merged**
