### PR TITLE
lewton_decoder as default, libvorbis_decoder as optional

### PR DESCRIPTION
**Pull request by awiouy**
Switch `lewton_decoder` as default and `libvorbis_decoder` as optional after #123
Works fine here

### CODE REVIEW

**Comment by plietar** [comment]
cc @est31

**Comment by sashahilton00** [comment]
Are there any upsides/downsides to doing this? Presumably libvorbis is more mature?

**Comment by est31** [comment]
Upsides:

* safety. There have been multiple CVEs against libvorbis. lewton on the other hand doesn't use a single line of unsafe code.
* no need for a C compiler

Downsides:

* lewton needs to be compiled in release mode in order to have comparable speed to libvorbis. lewton still is faster than realtime in debug mode, but be prepared for startled users :).
* yes libvorbis has been around longer and less bugs. If you find any bug in lewton, please report it!

**Comment by sashahilton00** [comment]
Thanks for clarifying. Sounds like we could make the switch to lewton as default without too much impact then. We may also want to consider switching the default build mode to release if we do make lewton the default, depending on the speed, but given that librespot is eventually to be the behind-the-scenes library for the daemon, it's probably unnecessary. Thoughts?

**Comment by plietar** [comment]
> We may also want to consider switching the default build mode to release
AFAIK there isn't a way of changing what `cargo build` does. The best we can do is use `--release` in the README (which is already the case).

There's a couple of other places in librespot which are pretty slow in debug mode (generating DH keys during handshake for example takes a handful seconds on x86_64, and likely a lot more on low end devices) so this isn't really a concern to me.

**Comment by sashahilton00** [comment]
If no one objects, I'll merge this in a couple of hours and update the docs.

**Pull request merged**
