### PR TITLE
Update connectivity.proto

### PR DESCRIPTION
**Pull request by SuisChan**

### CODE REVIEW

**Comment by roderickvd** [comment]
Thanks mate. Do you know how the other platforms Linux, iOS, Android get their client tokens?

**Comment by SuisChan** [comment]
> Do you know how the other platforms Linux, iOS, Android get their client tokens?

Yes, everything looks almost the same, with one request or two (with hashcash challenge)

**Comment by roderickvd** [comment]
Do you have some sample protobuf requests with the values to put in? I'd prefer to send a proper platform request instead of always the Windows request.

**Comment by SuisChan** [comment]
> Do you have some sample protobuf requests with the values to put in?

Have for android, two requests and responses, easly decoded with [Cyberchef](https://gchq.github.io/CyberChef/)
[clienttoken_android.zip](https://github.com/librespot-org/librespot/files/7925713/clienttoken_android.zip)

**Comment by roderickvd** [comment]
At work and not much time too look into this, but what's in the bin files? The binary protobufs? Do you know the values for the protobuf fields so I can build the message in Rust?

**Comment by roderickvd** [comment]
Also I guess `librespot` isn't run on Android that often. Mostly Linux I think but no protobufs for that, right. I wonder which protobufs Spotify's own Linux and Mac clients use.

**Comment by SuisChan** [comment]
> ut what's in the bin files? The binary protobufs? Do you know the values for the protobuf fields so I can build the message in Rust?

Packed protobuf messages so you can just copy the values from it, the only change required is to change NativeWindowsData to NativeAndroidData and fill out the request



> no protobufs for that, right

Unfortunately, I might get it later.

**Comment by SuisChan** [comment]
Got payload for Linux, I'll update it later

**Pull request merged**
