### PR TITLE
Use serde 1.0

### PR DESCRIPTION
**Pull request by medwards**
* Upgrades all projects to use serde 1.0
* Remove unused serde dependencies in root (note: did not verify that serde dependencies were used in the workspaces)
* Update Cargo.lock? Should this even be tracked or is it mistakenly committed?

### CODE REVIEW

**Comment by ashthespy** [comment]
Can we wait until https://github.com/librespot-org/librespot/pull/305 is merged to merge this?

**Comment by medwards** [comment]
No rush from me. Just would be nice for downstream users to take advantage
of serialisation of librespot types (or Credentials). If there's some easy
workaround (like with newtypes or something) then feel free to defer this
as long as you want. I just didn't take the time to look into workarounds
yet but will do so later this weekend.

**Comment by medwards** [comment]
Sadly I wasn't able to get a newtype struct in a serde 1.0 object to reuse the serde 0.9.6 serde traits in librespot. This leaves only awkward options for downstream users. Downgrading to 0.9.6 ends up requiring downgrading of some other packages (`toml` and `reqwest` in my case). I just create my own "credentials" type and manually convert it, though this isn't pretty since the `AuthenticationType` serde can't be used.

Regarding #305, I don't see any tricky blockers. I'd be happy to present a version of #305 which is compatible with this pull request.

**Comment by ashthespy** [comment]
@medwards Not really a big deal - I maintain a separate branch with update crates for similar reasons. I can also just rabase #305 when this is merged in - no issues!

**Comment by sashahilton00** [comment]
@medwards #305 merged. @ashthespy merge this once you're happy with it.

**Comment by medwards** [comment]
Resolved some merge conflicts in the manifests and updated the signature
for the track deserializer.

**Comment by sashahilton00** [comment]
Think you accidentally closed the PR

**Comment by medwards** [comment]
What the heck...

**Comment by medwards** [comment]
Oops was on detached head when I pushed, my bad.

**Comment by medwards** [comment]
BTW: I'd recommend adding Cargo.lock to the project .gitignore

**Comment by sashahilton00** [comment]
I'm tempted to, but official guidelines suggest otherwise https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html. Still, it's a PITA when merging PRs

**Comment by medwards** [comment]
"If you’re building a library that other packages will depend on, put
Cargo.lock in your .gitignore." doesn't apply?

I mean, I know librespot is building some binaries, but it also has 'lib'
right in the name. XD

**Comment by sashahilton00** [comment]
whilst it is a library, it defaults to building an executable. Will probably remove once it becomes just a library and librespotd is the the binary.

**Pull request merged**
