### PR TITLE
fix: change spotify version needed in clientoken to use semantic format

### LINKED ISSUE #1261: Unable to get client token
**Describe the bug**

When using the `playlist_tracks.rs` example with a large playlist (+300 songs), there is eventually a failure due to a "too many request" exception.

The exception is raised by `SpClient::client_token`, which seems to constantly fail with a `400 Bad Request`, thus gets called at each API request.

**To reproduce**

1. Build and launch the  `playlist_tracks.rs` example with a large playlist (+300 songs)
2. See error

**Log**

```
...
2024-03-10T00:07:05Z DEBUG librespot_core::spclient] Client token unavailable or expired, requesting new token.
[2024-03-10T00:07:05Z DEBUG librespot_core::http_client] Requesting https://clienttoken.spotify.com/v1/clienttoken
[2024-03-10T00:07:05Z DEBUG hyper::client::pool] reuse idle connection for ("https", clienttoken.spotify.com)
[2024-03-10T00:07:05Z DEBUG h2::codec::framed_write] send frame=Headers { stream_id: StreamId(419), flags: (0x4: END_HEADERS) }
[2024-03-10T00:07:05Z DEBUG h2::codec::framed_write] send frame=Data { stream_id: StreamId(419), flags: (0x1: END_STREAM) }
[2024-03-10T00:07:05Z DEBUG h2::codec::framed_read] received frame=Headers { stream_id: StreamId(419), flags: (0x5: END_HEADERS | END_STREAM) }
[2024-03-10T00:07:05Z DEBUG h2::codec::framed_read] received frame=Ping { ack: false, payload: [0, 0, 0, 0, 0, 0, 4, 101] }
[2024-03-10T00:07:05Z DEBUG h2::codec::framed_write] send frame=Ping { ack: true, payload: [0, 0, 0, 0, 0, 0, 4, 101] }
[2024-03-10T00:07:05Z WARN  librespot_core::spclient] Unable to get client token: Client specified an invalid argument { Response status code: 400 Bad Request } Trying to continue without...
[2024-03-10T00:07:05Z DEBUG librespot_core::http_client] Requesting https://gew1-spclient.spotify.com:443/metadata/4/track/...?product=0&country=GB&salt=436026428
...
````

**Host (what you are running `librespot` on):**
- OS: Linux
- Platform: amd64
- Version: `dev`

### PR DESCRIPTION
**Pull request by acolombier**
Fixes #1261

### CODE REVIEW

**Comment by kingosticks** [comment]
Which platforms are tested with this? Is it the string formatting that's important here or just the newer version number? It's a bit odd we still have the old version number in use elsewhere.

**Comment by acolombier** [comment]
Good question - I'm not sure. I stumble across this as I was comparing the protobuf message between the Spotify Desktop Client and Librespot and noticed that the `version` appeared to be corrupted - it didn't include a string for a `float32` instead, which I think explain the `Bad Request` server-side. Now, since `spotify_version()` returns a `String`, it is very odd how this ends up being packed as a float, instead of string - perhaps a bug in the proto crate? 
Anyway, using a `str` as source seems to have fixed the problem, and I can now see identical proto messages between both desktop client and librespot. I didn't spend the time checking whether other values semantic version compatible would work, but I would expect so, if the theory of incorrect message format is the correct one.

**Comment by wisp3rwind** [comment]
FWIW, this also silences the warnings from #1261 for me (also Linux amd64).

**Comment by roderickvd** [comment]
I'll merge it as it's clearly an important "hot fix". Thanks.

Ideally though all the number versions should be consistent with the protocol version at that time, meaning that the protobufs match / were extracted from that client version. If someone could do that...

**Comment by acolombier** [comment]
I'd be happy to give it a go, but not sure how to do that. Is there wiki or doc? Or is that a matter of digging in Spotify files to find where they have been packed?

**Comment by hrkfdn** [comment]
Is this something that's worth backporting to the `master` branch? It seems to be a problem with the current release.

**Comment by kingosticks** [comment]
Are you sure? The current release is 0.4.2 and doesn't use a client token to get metadata via HTTP, it uses Mercury. It would be impossible to backport this fix to master. I'm not saying there isn't a similar problem in master but it seems unlikely to be exactly this.

**Comment by hrkfdn** [comment]
Librespot doesn't as a binary. `ncspot` however uses it as a library and requests a client token via Mercury like so: https://github.com/hrkfdn/ncspot/blob/d1ea7b069efd4df7e311be9d6d24d4fa3edb2991/src/spotify_worker.rs#L66-L87

This token is then used to request HTTP metadata and according to the bug report https://github.com/hrkfdn/ncspot/issues/1421 seems to be suffering from the same issue reported in #1261.

**Pull request merged**
