### PR TITLE
Dynamic failable buffer sizing alsa-backend

### PR DESCRIPTION
**Pull request by JasonLG1979**
Dynamically set the alsa buffer and period based on the device's reported min/max buffer and period sizes. In the event of failure use the device's defaults.

This should have no effect on devices that allow for reasonable buffer and period sizes but would allow us to be more forgiving with less reasonable devices or configurations.

Closes: https://github.com/librespot-org/librespot/issues/895

### CODE REVIEW

**Comment by roderickvd** [comment]
Sorry, I had a weekend with family time over something like a national holiday. So haven't been able to give it a spin on my rig. Reports from any others?

**Comment by JasonLG1979** [comment]
> Sorry, I had a weekend with family time over something like a national holiday. So haven't been able to give it a spin on my rig. Reports from any others?

It's all good. I got plenty on my plate also. No real hurry. It will be here next weekend.

**Comment by JasonLG1979** [comment]
*It's next weekend.

**Comment by JasonLG1979** [comment]
All squashed and ready for review. @roderickvd?

**Comment by roderickvd** [comment]
Yes again I missed the opportunity to test on my Alsa rig this weekend. Sorry man. I’m on the road a lot these weeks. Now I think of it, this weekend won’t work either. So please if others could report this is working well with regressions on their own system? With a few good reports in we can get this merged.

**Comment by JasonLG1979** [comment]
> Yes again I missed the opportunity to test on my Alsa rig this weekend. Sorry man. I’m on the road a lot these weeks. Now I think of it, this weekend won’t work either. So please if others could report this is working well with regressions on their own system? With a few good reports in we can get this merged.

@oebeledrijfhout and @sarlej have both confirmed that it works on the Vero4K and I can confirm that manually configuring and locking a device's buffer and period size to an allowed but unreasonable value in `/etc/asound.conf` also works similarly in that `librespot` basically just facepalms and says "whatever, use your configured default."

That's basically the meat of this PR. Where as before `librespot` would just throw an error and exit when met with an unreasonable or misconfigured device with this it will trace level log what went wrong and just use the device's defaults, which may not be ideal but are hopefully serviceable. In the event that they aren't it will be very evident in the logs (with `-v`, `--verbose` ofc) after this it will be much easier to wash our hands of crappy and/or misconfigured hardware. That's why there are so many `trace!` messages. It's evidence and ammunition to be able to push audio bugs upstream instead of having them languish. It makes it much easier to say "not our problem" and smash that close button,lol!!!     

@sarlej has confirmed that it does not break their previously working USB DAC and I can also confirm that it works with both of my desktops, my son's laptop, my USB DAC and the DAC HAT on my Raspberry Pi 4 and Zero.

**Comment by JasonLG1979** [comment]
As with pretty much anything else, really no one is going to help us test PR's. We were actually pretty lucky to get 2 others to actually test this one.

**Comment by roderickvd** [comment]
I'm afraid you're quite right. OK let's merge this then.

**Pull request merged**
