### PR TITLE
do not panic on connection reset

### LINKED ISSUE #196: crash after playback ends
Hello,
when the playback ends, librespot always crashes with following message:
```
 thread 'main' panicked at 'Box<Any>', core/src/session.rs:79:42
 stack backtrace:
    0:     0x5649b9f3422f - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h124b4bcef8>
    1:     0x5649b9f1a0f1 - std::sys_common::backtrace::print::hc582a11b3ee21b31
    2:     0x5649b9f2562d - std::panicking::default_hook::{{closure}}::h8186675e6f93fe64
    3:     0x5649b9f252df - std::panicking::default_hook::hd0d178fcebd87257
    4:     0x5649b9f25b1d - std::panicking::rust_panic_with_hook::h3ecd70e9e7b4a365
    5:     0x5649b9c7649a - std::panicking::begin_panic_new::hb538b624dc78c62a
    6:     0x5649b9cb5857 - <futures::future::map_err::MapErr<A, F> as futures::future::Future>::>
    7:     0x5649b9ef903c - tokio_core::reactor::Core::poll::h26ce83ebe657b45c
    8:     0x5649b9b8ffa4 - librespot::main::h9e79c76471055a88
    9:     0x5649b9f3c6e7 - __rust_maybe_catch_panic
   10:     0x5649b9f257c7 - std::panicking::try::h36ff7733b5113eb6
   11:     0x5649b9f36269 - std::rt::lang_start::h60bbe14d465df98b
   12:     0x7f2b65551f69 - __libc_start_main
   13:     0x5649b9b72299 - _start
   14:                0x0 - <unknown>
```
I have tried to build the latest master with same results.
Parameters for build:
```
 cargo build --release --no-default-features --features alsa-backend
```

### PR DESCRIPTION
**Pull request by lrbalt**
If Spotify cannot communicate with your Librespot device, the connection is reset. This patch handles this case by stopping the Session, Spirc and Player. Librespot then keeps listening for new connections

This should fix #196 and #134

### CODE REVIEW

**Comment by lrbalt** [comment]
I’d like to implement a reconnect using the credentials of the session which connection was reset. I’m seeing a lot of resets. But with this patch at least Librespot does not panic and keeps running

**Comment by lrbalt** [comment]
If it crashes, do you have a stacktrace to see if that crash is related to this patch?

**Comment by sashahilton00** [comment]
@lrbalt thanks for taking a stab at this long running bug :) I'll not merge it for now to give @elganzua124 a chance to provide a stack trace to see if it has anything to do with this PR and/or if there is anything that can be added if necessary. With regards to reconnecting with existing credentials, I think you could potentially use the auth blob that's stored/returned to reauthenticate?

**Comment by plietar** [comment]
Please do not close #134 when merging this.
While this is a good workaround (thanks @lrbalt), it only works for librespot as a binary, not librespot as a library. The more general solution in #134 should be implemented instead.

**Comment by elganzua124** [comment]
I can not reproduce the issue right now. I'll do some more tests tomorrow. For now it resolves Internet interruptions just fine:
```
 /usr/bin/librespot -n test -b 320 --initial-volume 
INFO:librespot: librespot  (). Built on 2018-04-23. Build ID: 9x8FJj6v
INFO:librespot_core::session: Connecting to AP "guc3-accesspoint-b-fzk9.ap.spotify.com:4070"
INFO:librespot_core::session: Connecting to AP "guc3-accesspoint-b-lb9j.ap.spotify.com:4070"
INFO:librespot_core::session: Authenticated as "me" !
INFO:librespot_playback::audio_backend::alsa: Using alsa sink
INFO:librespot_core::session: Country: "AR"
INFO:librespot_playback::player: Loading track "Some track" with Spotify URI "spotify:track:blabla"
INFO:librespot_playback::player: Track "Some lyric" loaded
ERROR:librespot_core::session: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
INFO:librespot_core::session: Connecting to AP "guc3-accesspoint-b-lqm9.ap.spotify.com:4070"
INFO:librespot_core::session: Authenticated as "me again" !
INFO:librespot_playback::audio_backend::alsa: Using alsa sink
INFO:librespot_core::session: Country: "AR"
INFO:librespot_playback::player: Loading track "Some track" with Spotify URI "spotify:track:blabla"
INFO:librespot_playback::player: Track "Some lyric" loaded
```
Regarding to credentials, it would be great if librespot could reconnect using them, then one could choose in configurations if librespot should resume when session is restored (default) or just wait for user directives. With that I would be more than satisfied.

**Comment by lrbalt** [comment]
I can try to do the reconnect for #134. @plietar, are you available for review?

This PR can be merged in the mean time so that we do not panic on connection reset.

**Comment by sashahilton00** [comment]
Will merge this later this evening if no objections

**Comment by lrbalt** [comment]
Sorry, I missed you cargo fmt question. I’ll do that tomorrow.

**Comment by lrbalt** [comment]
@sashahilton00 rustfmt added to PR

```
➜  librespot git:(master) ✗ rustc -V; cargo fmt --version
rustc 1.27.0-nightly (ac3c2288f 2018-04-18)
rustfmt 0.4.2-nightly (dd807e2 2018-04-18)
```

cargo fmt does complain about configuration options:

```
➜  librespot git:(master) ✗ cargo fmt --all
Warning: Unknown configuration option `reorder_imports_in_group`
Warning: Unknown configuration option `reorder_imports_in_group`
Warning: Unknown configuration option `reorder_imports_in_group`
Warning: Unknown configuration option `reorder_imports_in_group`
Warning: Unknown configuration option `reorder_imports_in_group`
Warning: Unknown configuration option `reorder_imports_in_group`
Warning: Unknown configuration option `reorder_imports_in_group`
Warning: Unknown configuration option `reorder_imports_in_group`
Warning: Unknown configuration option `reorder_imports_in_group`
Warning: Unknown configuration option `reorder_imports_in_group`
Warning: Unknown configuration option `reorder_imports_in_group`
```

**Comment by sashahilton00** [comment]
@lrbalt thanks, will let Travis run and merge.

**Comment by sashahilton00** [comment]
Merged, thanks for implementing this. Have left #134 open for when the reconnection logic is implemented in the library.

**Pull request merged**
