### PR TITLE
Persist software volume across restarts

### PR DESCRIPTION
**Pull request by bricedp**
This pull request adds the ability to persist the software volume across restarts of librespot. A user can now specify a file path using the `--persist-volume` flag where the volume will be written to disk. If the file exists, the volume will be read from it and it will override the `--initial-volume` value. If not, it will be written upon the first connection of a client. This way, `--initial-volume` can still be used to set the volume for the first run of librespot, after which the persistent volume will take precedence.

For example, `librespot --initial-volume 25 --persist-volume /tmp/librespot.vol` will start at 25%, but all future runs of the program will read the most recent volume from /tmp/librespot.vol.

In the event that the file cannot be written to or read from, the current logic intends for librespot to fail fast and hard, so that the user is made aware and not led to believe that the volume is being persisted when in fact it isn't.

Builds against the latest nightly version of rust (1.27.0) pass without errors or warnings, and rustfmt has been used to standardize the code. Please let me know if you need me to make any changes. Rust is a relatively new language to me, so I am not sure if the `unwrap()` and `clone()` calls are considered best practice as implemented here.

### CODE REVIEW

**Comment by plietar** [comment]
Thanks @bricedp !

I agree this should just use the cache directory as opposed to specifying a custom path.
I would use a separate file though, not reuse credentials.json.

Also I don't think `--persist-volume` is necessary at all, I don't see any downside in having this always enabled.

**Comment by plietar** [comment]
Also `--initial-volume` should override the persisted one. Although I think the initial volume flag will not be used much once we can persist it.

**Comment by bricedp** [comment]
Okay, it certainly makes more sense for it to be stored in the cache directory, I agree. If you want to persist by default and the user no longer needs to specify a separate path, then I can remove the command line flag as well. In that case you're right; `--initial-volume` should override the persisted volume because it's more explicit.

I can work on making those changes before merging; it would be a cleaner implementation from the start. Assuming we don't reuse credentials.json: do you anticipate the need for a more general config.json file that stores state/settings or would you rather I use a plaintext file with just the volume percentage, as I have it now?

**Comment by plietar** [comment]
Plaintext file is file for now at least.

**Comment by bricedp** [comment]
I think `--initial-volume` would make sense as an explicit default that bypasses the persistent volume. In cases where a user is caching, it is expected behavior that the volume will be restored on the next run, just as credentials are. The hard-coded default of 0x8000 would then be a last-resort fallback, when `--initial-volume` has not been specified and there has not yet been a volume persisted to disk. So the starting volume would have priority as follows:

1. value taken from `--initial-volume`
2. value stored in cache directory
3. hard-coded default (currently 0x8000)

I don't see a use case in which the hard-coded value is preferable to the persisted value, especially since that hard-coded default is opaque to the user. With this priority, the presence of `--initial-volume` is the same as the lack of a `--persist-volume` flag — it says "ignore the cache and use this value instead".

In your example's second run, librespot would not necessarily start with the saved `--initial-volume`, but rather whatever volume the music was last playing at before the program was terminated.

**Comment by sashahilton00** [comment]
Actually, that does sound better. So if `--initial-volume` is present, it would use that, otherwise if `--cache` is present and a volume stored, it would use that, else the default of 0x8000.

**Comment by bricedp** [comment]
Yes, that's right. That logic also simplifies and centralizes much of the changes I made, so I'd like to hold off on merging while I work on that.

**Comment by bricedp** [comment]
I've moved this pull request to another branch for clarity, as it was almost a complete rewrite. See here: [https://github.com/librespot-org/librespot/pull/220](https://github.com/librespot-org/librespot/pull/220)

**Pull request closed without merging**
