### PR TITLE
Skip track on decoding error

### LINKED ISSUE #902: Librespot crashes when seeking to a position that is not yet downloaded.
When librespot starts downloading and playing a track, when one seeks manually forward to a part that is not yet downloaded, librespot crashes. Here is the last lines of the ``--verbose`` log:

```
[2021-12-09T18:32:39Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
[2021-12-09T18:32:39Z DEBUG librespot_playback::player] command=Seek(98835)
[2021-12-09T18:32:40Z ERROR librespot_playback::player] PlayerInternal handle_command_seek: Lewton Decoder Error: Ogg decode problem
[2021-12-09T18:32:40Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
[2021-12-09T18:32:40Z TRACE librespot_connect::spirc] ==> kPlayStatusPlay
[2021-12-09T18:32:40Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
[2021-12-09T18:32:40Z TRACE librespot_connect::spirc] ==> kPlayStatusPlay
[2021-12-09T18:32:40Z ERROR librespot_playback::player] PlayerInternal poll: Lewton Decoder Error: Vorbis bitstream audio decode problem
```

Then the application crashed.

EDIT: This is running ``librespot 0.3.1 e66cc55 (Built on 2021-12-02, Build ID: b5V8XqQE, Profile: release)``.

### PR DESCRIPTION
**Pull request by roderickvd**
I haven't encountered this myself, but this should close #902.

### CODE REVIEW

**Comment by JasonLG1979** [comment]
You should probably check against the type of error. A decoding error my be resolved by skipping tracks but a audio backend error no so much. You also might want to set a throttler. Something that says "Ok this has happened 20 times in a row in x amount of time let's stop trying and exit."

**Comment by roderickvd** [comment]
All that 8e9fad52338aa20c0b9307128399c31eafd7f385 does is cover the crashes where the decoder can't return samples or can't proceed to the next packet. It has nothing to do with the audio backends.

**Comment by JasonLG1979** [comment]
> All that [8e9fad5](https://github.com/librespot-org/librespot/commit/8e9fad52338aa20c0b9307128399c31eafd7f385) does is cover the crashes where the decoder can't return samples or can't proceed to the next packet. It has nothing to do with the audio backends.

Oh Ok. You still might want to throttle it since you're skipping tracks on error. Otherwise you could theoretically get the user and/or `librespot` in trouble for exceeding some rate limit if there were some sort of catastrophic decoder bug. You'd machine gun right though a bazillion tracks in secs.

**Comment by roderickvd** [comment]
It’s not a bad idea. It goes for everything that makes a network request though. So we really should implement it at the source. In `new-api` I’ll see about implementing throttling in the HTTP client.

**Comment by roderickvd** [comment]
I agree. This is mostly a copy/paste action from other parts of the player, but I can make those prettier too.

**Comment by JasonLG1979** [comment]
> It’s not a bad idea. It goes for everything that makes a network request though. So we really should implement it at the source. In new-api I’ll see about implementing throttling in the HTTP client.

Ofc we have no way to know what the rate limit of the playback API is but I think it would be a good idea to checkout [this page](https://developer.spotify.com/documentation/web-api/guides/rate-limits/).

**Comment by JasonLG1979** [comment]
In the meantime before the new API is done this LGTM. Ofc I can't actually reproduce the error in question but this should basically do as advertised.

**Comment by roderickvd** [comment]
I had hoped for comments by @coderootme but let's just get this in. I see no way of it causing regressions.

**Comment by JasonLG1979** [comment]
> I had hoped for comments by @coderootme but let's just get this in. I see no way of it causing regressions.

It can't really get any worse,lol!!! But in the new API I'd follow the docs and wait the amount of time stated in the 429 error response. The rate limit window is 30 sec but it doesn't actually say what the rate limit is but instead implies that it's not a static value. You could pretty easily calculate a dynamic rate limit by keeping track of how many calls were made in the last 30 sec and if you get a 429 that's your rate limit. There's also ofc making sure to use batch methods as much as possible and not making redundant calls.

**Pull request merged**
