### PR TITLE
Move functionality into modules.

### PR DESCRIPTION
**Pull request by sashahilton00**

### CODE REVIEW

**Comment by plietar** [comment]
The keymaster was already moved to core in #122. Can you rebase and only keep the discovery commit.

**Comment by sashahilton00** [comment]
Not the greatest with git, but I believe that the only changes in this PR are now the discovery changes.

**Comment by plietar** [comment]
I've fixed the Git history. I don't actually have Rust on this machine so waiting to see what travis says.

**Comment by sashahilton00** [comment]
Thanks for that. I'm a cretin when it comes to anything vaguely complex in git :)

**Pull request merged**
