### PR TITLE
Remove automatically generated protobuf files

### PR DESCRIPTION
**Pull request by tstenner**
Since 7cb551d66d3d195d04d7e247b3dc8d9f597a347c protobuf files are regenerated automatically so these files can be removed from the repository.

### CODE REVIEW

**Comment by willstott101** [comment]
Theoretically this makes sense, but I'd be interested to know if you'd found any problems with them being included?

**Comment by willstott101** [comment]
Seeing the changes in a PR diff and tracking their changes over time has value in my opinion so I'd hesitate to add them to git ignore unless they're troublesome in some way

**Comment by kingosticks** [comment]
Maybe I missed the memo here, but does this mean that you now require the protobuf tools to compile librespot?

**Comment by willstott101** [comment]
The protobuf generator we use is pure rust, and is compiled as part of the build process. The goal was to streamline and remove all dependencies or environmental requirements which cargo couldn't sort out itself.

**Comment by kingosticks** [comment]
Ahh OK great. Thanks. (sorry for the noise)

**Comment by tstenner** [comment]
> Theoretically this makes sense, but I'd be interested to know if you'd found any problems with them being included?

Whenever protobuf is updated (even for minor versions, e.g. 2.8.0 to 2.8.1) the protobuf files have to be included as well. Also, they shouldn't be changed manually so tracking the changes in the repository doesn't make sense.

> Seeing the changes in a PR diff and tracking their changes over time has value in my opinion so I'd hesitate to add them to git ignore unless they're troublesome in some way

It's just the automatically generated code, real changes to the protocol files are to the .proto files in `protocol/proto`. Changes to the generated files could be useful when something breaks but I haven't encountered such a case yet.

**Comment by ashthespy** [comment]
>Whenever protobuf is updated (even for minor versions, e.g. 2.8.0 to 2.8.1) the protobuf files have to be included as well. Also, they shouldn't be changed manually so tracking the changes in the repository doesn't make sense.

I'd rather keep them checked in as well, just to be safe. We could pin `protobuf` instead?

**Comment by willstott101** [comment]
Yeah we'll definitely need to be sure everyone has the same Protobuf version if we're keeping them checked in. I had assumed that was the case already thanks to Cargo.lock? Presumably we'd currently require a `cargo update` to make Protobuf get bumped up by even a minor version. And the result of `cargo update` would make sense as a standalone PR IMO.

**Comment by willstott101** [comment]
@tstenner have you actually had cargo automatically update one of the protobuf dependencies? If so I think the issue here is how those dependencies are defined rather than the generated files being included.

**Comment by tstenner** [comment]
I did, and the files were regenerated automatically. There something to be said for removing them from the repository, but I also see your point that the files' histories are helpful to have just in case.

**Comment by ashthespy** [comment]
@tstenner If there are no explicit problems that this solves, lets keep it checked in for now, and revisit this in the future?

**Pull request closed without merging**
