### PR TITLE
Port to gstreamer-rs 0.19

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by roderickvd** [comment]
There seems to be a trend of high MSRVs lately. You think upping our MSRV is worth it for this update?

**Comment by sdroege** [comment]
> You think upping our MSRV is worth it for this update?

I think artificially staying at an old version is just causing friction in the ecosystem. If someone can update to a newer version of a crate they can also update their toolchain :shrug:

**Comment by roderickvd** [comment]
It was an honest question and observation for joint deliberation, not a decision already made up. 

To understand where this project is coming from when I got maintainer rights: it used to track the Rust version in Debian stable as MSRV. 

I am glad that you have picked up the `gstreamer` gauntlet. Let me know if you if you wish to reopen.

**Comment by sdroege** [comment]
We had the same discussion last time already :)

**Comment by roderickvd** [comment]
Coming back to me now 😄

**Pull request closed without merging**
