### PR TITLE
Issue 130

### PR DESCRIPTION
**Pull request by awiouy**

### CODE REVIEW

**Comment by awiouy** [comment]
With this I am done with what I can do about #130.
Someone please take over the rest. @sashahilton00?

@plietar:
- the `new` method generated by the `component!` macro is not exposed anymore
- `session::spawn` can not be made more private
- remaining stuff in `util/mod.rs` is used all over other crates

**Comment by plietar** [comment]
I think u128 should stay in it's own file. I'm fine with where it was, it just shouldn't be exposed outside the crate.

**Comment by awiouy** [comment]
I have reworked u128

**Comment by sashahilton00** [comment]
Thanks @awiouy, I've updated #130. Will look at the other stuff later on.

**Pull request merged**
