### PR TITLE
rustfmt

### PR DESCRIPTION
**Pull request by awiouy**
rustfmt applied to core, except component.rs (maximum width exceeded)

### CODE REVIEW

**Comment by michaelherger** [comment]
I always hate this moment... while I do understand the idea of clean formatting, I hate the fact that this basically renders git log useless. But oh well... I've survived it before :-).

Q: where would I find the rules applied here? rustfmt's web page doesn't really explain what the formatting rules are (or I haven't found that page).

**Comment by awiouy** [comment]
I have added `rustfmt.toml` so that we can build upon a agreed format.
`max_width = 105` provides for `component.rs`, which is now also reformatted.

I just switched from [ed](https://www.gnu.org/fun/jokes/ed-msg.txt) to [atom](https://atom.io/).
I have added rustfmt to atom as described [here](https://github.com/rust-lang-nursery/rustfmt/blob/master/atom.md).

**Comment by plietar** [comment]
I often split imports into "external crates" and "local crate". Can you try with `reorder_imports_in_group = true`. That should preserve this.

**Comment by awiouy** [comment]
@plietar I have updated the pull request

**Comment by awiouy** [comment]
@michaelherger `rustfmt --config-help`

**Comment by plietar** [comment]
@michaelherger The rules are described here: https://github.com/rust-lang-nursery/fmt-rfcs/blob/master/guide/guide.md. The discussion around the style happens in that repo's issues.
I find the diff acceptable. It's mostly just signatures and imports being changed.

@awiouy Thanks. Could you add something like this to `.travis.yml` to make sure the style stays consistent.
```yaml
- if [[ $TRAVIS_RUST_VERSION == *"nightly"* ]]; then
         rustup component add rustfmt-preview;
         cargo fmt --package=librespot-core -- --write-mode=diff;
  fi

**Comment by awiouy** [comment]
Done. Fixes #132

**Comment by michaelherger** [comment]
Thanks @plietar. Agreed, it's not as bad as replacing spaces/tabs or new lines in all of the code base... :-)

**Pull request merged**
