### PR TITLE
Various code improvements

### PR DESCRIPTION
**Pull request by roderickvd**
This is a collection of code improvements:
1. upgrade deprecated `std::u16::MAX` constants
2. use `FromStr` for fallible `&str` conversions everywhere
3. upgrade legacy `as_ref().map()` calls into `as_deref()`
4. DRY up strings into constants
5. use `Duration` for time constants and functions

### CODE REVIEW

**Comment by Johannesd3** [comment]
`FromStr` is older than `TryFrom`, but it has the advantage that you can use `str::parse` to convert a string into this type. Using `From` + panic if conversion can fail would be much worse.

I also have the feeling that constants like `ONE_SEC_AS_MILLIS` wouldn't be necessary if `Duration` would be used more idiomatic.

**Comment by roderickvd** [comment]
> `FromStr` is older than `TryFrom`, but it has the advantage that you can use `str::parse` to convert a string into this type. Using `From` + panic if conversion can fail would be much worse.

There's mixed use of `FromStr` and `TryFrom` in `dev` now. Would you rather move everything to `FromStr`?
Right now it all panics regardless, it'd be a separate PR to fail gently instead of calling `expect`.

> I also have the feeling that constants like `ONE_SEC_AS_MILLIS` wouldn't be necessary if `Duration` would be used more idiomatic.

Good idea.

**Comment by roderickvd** [comment]
The nice `Duration::SECOND` are only in Rust nightly unfortunately.

**Comment by JasonLG1979** [comment]
> The nice `Duration::SECOND` and friends are only in Rust nightly unfortunately.

What's to prevent you from creating a const out of `Duration::from_millis(1000)` and just calling that `duration_SECOND` or whatever?

**Comment by roderickvd** [comment]
That's the same as defining `ONE_SEC_AS_MILLIS` but without the syntactic sugar.

**Comment by JasonLG1979** [comment]
> That's the same as defining `ONE_SEC_AS_MILLIS` but without the syntactic sugar.

If you're defining time in 1 sec chunks the `_AS_MILLIS` part of the name serves no purpose. When I think of idiomatic I think of how a person would speak. I wouldn't say "In one second of milliseconds I will do this."

**Comment by roderickvd** [comment]
I think I see what you guys mean, take a look at da1eded. It compiles but still needs testing.

Also let me know about `FromStr` or `TryFrom` and I'll update if necessary.

**Comment by JasonLG1979** [comment]
> I think I see what you guys mean, take a look at [da1eded](https://github.com/librespot-org/librespot/commit/da1eded88e7b837c2372fe09b0b97eb1e939e6f9). It compiles but still needs testing.

I guess my nitpick is that if `Duration::from_secs(TIMEOUT_SECONDS)` is never going to yield a different result there's no point in calculating it over and over again. It should just be calculated once and used as a const. I may be totally wrong and misunderstanding what's going on though,lol!!!

**Comment by roderickvd** [comment]
> > I think I see what you guys mean, take a look at [da1eded](https://github.com/librespot-org/librespot/commit/da1eded88e7b837c2372fe09b0b97eb1e939e6f9). It compiles but still needs testing.
> 
> I guess my nitpick is that if `Duration::from_secs(TIMEOUT_SECONDS)` is never going to yield a different result there's no point in calculating it over and over again. It should just be calculated once and used as a const. I may be totally wrong and misunderstanding what's going on though,lol!!!

In Rust, values from non-static functions cannot be assigned to a constant.

**Comment by JasonLG1979** [comment]
> In Rust, values from non-static functions cannot be assigned to a constant.

Weird that something that would never change, the system's value for a sec, can't be be assigned to a constant?

**Comment by roderickvd** [comment]
It's being changed in Rust nightly but that won't be in `librespot` MSRV for a couple of years as long as we track Debian stable `rustc`.

**Comment by JasonLG1979** [comment]
> It's being changed in Rust nightly but that won't be in `librespot` MSRV for a couple of years as long as we track Debian stable `rustc`.

Crusty old Debian stable,lol!!!

**Comment by Johannesd3** [comment]
> I guess my nitpick is that if `Duration::from_secs(TIMEOUT_SECONDS)` is never going to yield a different result there's no point in calculating it over and over again. It should just be calculated once and used as a const. I may be totally wrong and misunderstanding what's going on though,lol!!!

"Calculating" would be the wrong word here. I'm pretty sure the compiler would optimize it in a way that hasn't more overhead than using a `const` value. But ...

> It's being changed in Rust nightly but that won't be in librespot MSRV for a couple of years as long as we track Debian stable rustc.

I don't think that's true. Every `const fn` can be used to calculate the value of a `const`. And `Duration::from_*` are const since a long time. 

> Also let me know about `FromStr` or `TryFrom` and I'll update if necessary.

Honestly, I don't know. Maybe search for it in the internet, we're certainly not the only ones who wonder what's better.

**Comment by JasonLG1979** [comment]
> "Calculating" would be the wrong word here. I'm pretty sure the compiler would optimize it in a way that hasn't more overhead than using a `const` value.

I'm not so sure about that? The compiler can't even optimize a "round to even" situation to not take twice the CPU,lol!!!

**Comment by JasonLG1979** [comment]
Plus if you could do a const it would look a Hell of a lot cleaner.

**Comment by Johannesd3** [comment]
Look: https://godbolt.org/z/E9GrbTox6. The compiler doesn't even generate code for the second function because it knows they're the same.

> Plus if you could do a const it would look a Hell of a lot cleaner.

Agreed. But you _can_ do.

**Comment by JasonLG1979** [comment]
> Look: https://godbolt.org/z/E9GrbTox6. The compiler doesn't even generate code for the second function because it knows they're the same.
> 
> >

I was just poking fun. You know a lot more about it then I do,lol!!!

> Agreed. But you can do.

Then we should do. By "we" I mean we in the royal sense, as in @roderickvd should do,lol!!!

**Comment by roderickvd** [comment]
Honestly I didn't even try, but now see that this works so I'll get on it:

```rust
use std::time::Duration;

const TIMEOUT: Duration = Duration::from_secs(1);

fn main() {
    println!("{:?}", TIMEOUT);
}
```

> > Also let me know about `FromStr` or `TryFrom` and I'll update if necessary.
> 
> Honestly, I don't know. Maybe search for it in the internet, we're certainly not the only ones who wonder what's better.

Man, huge can of worms. I don't particularly care either way, I just want to make them consistent. I'm fine with changing my proposal if anyone thinks that'd be better. Otherwise if no one has an opinion on this, might as well stick with it.

**Comment by Johannesd3** [comment]
I would stick to `FromStr` as far as lifetimes allow it.

**Comment by roderickvd** [comment]
> I would stick to `FromStr` as far as lifetimes allow it.

Here you go.

> Plus if you could do a const it would look a Hell of a lot cleaner.

Thanks for the push into this direction. Using `Duration` everywhere does look a lot nicer.

**Comment by roderickvd** [comment]
If there are no further comments, or people who need more time, I plan on merging this evening. Will merge `dev` in and get the checks running. I successfully verified that preloading and dynamic normalisation are still working.

**Comment by Johannesd3** [comment]
You could write the comments for the constants above the constants and make rustdoc comments out of it

**Comment by roderickvd** [comment]
@Johannesd3 this what you had in mind?

**Comment by Johannesd3** [comment]
No, I meant those in audio/src/fetch/mod.rs

**Comment by roderickvd** [comment]
:man_facepalming: this should be it then. Intend to merge when CI passes.

**Pull request merged**
