### PR TITLE
adding callback for reusable credentials

### PR DESCRIPTION
**Pull request by Louis9902**
This adds a callback to the creation of the session, so the reusable credentials can be stored separately. This is useful when using a keychain or something like the secret_service api.

The way it's implemented, no API is broken but the possibility to reuse the credentials is there.

#### Why do I wan't this?

When using librespot without the cache, Spotify will send an email about a new login attempt when using the password credentials, with the long-lived token this does not happen. But I don't want to either use the cache or I don't want the token in a json file on my fs.

Feel free to give me some feedback or another solution, but I’m relatively new to rust, so I might ask some questions.

### CODE REVIEW

**Comment by Louis9902** [comment]
Since I'm new to this language, I think that this is a better solution.

**Comment by roderickvd** [comment]
This might be semantics but this is not exactly a callback, is it?

It does break the API but I don't mind about that.

I can see the benefits of making the credentials available to others. Indeed it could be done by returning them in the result. Another option would be making them public as a field of some struct. The former may be more secure, the latter more flexible.

Opinions?

Also would you please run `cargo fmt`?

**Comment by Louis9902** [comment]
> This might be semantics but this is not exactly a callback, is it?

Yeah, my first attempt was a callback, but that was a little strange to use, so I changed it to the return type.

> It does break the API but I don't mind about that.

Okay I'm not to familiar with rust, how does it break the api, I have changed nothing in the declaration?

I also run cargo fmt again, sorry for that.

**Comment by roderickvd** [comment]
You changed the function name, and now return `Ok` with a tuple instead of a single value.

**Comment by kingosticks** [comment]
@roderickvd I think you missed the bottom part of the patch which provides the old function now wrapping the new one so the API is unchanged. 

Personally I think a new store_credentials flag in `SessionConfig` would be neater. Not sure about the name of the new function .

**Comment by Louis9902** [comment]
> You changed the function name, and now return `Ok` with a tuple instead of a single value.

Yeah but the old way is still there, it uses the new one internally.

**Comment by Louis9902** [comment]
> But still not sure about the name of the new function .

Yeah, but I couldn't figure out a better name

**Comment by roderickvd** [comment]
> @roderickvd I think you missed the bottom part of the patch which provides the old function now wrapping the new one so the API is unchanged.

Indeed I did. That mechanism is fine. 

> Yeah, but I couldn't figure out a better name

We can also just think about changing the API. I don’t particularly mind. Can’t think of a good function name either. 

Again the other option is to not return the credentials on connect, but keep them in fields of some struct. 

I’m not arguing either way, just wondering what would be the preferred idiom.

**Comment by Louis9902** [comment]
I think returning it and not storing it inside the struct is fine because when the session struct is used the credentials don't matter anymore. At this point, I already have a working session.

**Comment by roderickvd** [comment]
I think I agree. So let's come up with a good name and get this in then.

**Comment by Louis9902** [comment]
maybe `connect_with_credentials`?

**Comment by roderickvd** [comment]
Not that, because `with_xxx` is intended as a general constructor with more parameters than in `new`: https://rust-lang.github.io/api-guidelines/naming.html

Maybe just change `connect` altogether and just break the API. We'll be releasing `0.4.0` soon anyway.

**Comment by Louis9902** [comment]
> Maybe just change `connect` altogether and just break the API. We'll be releasing `0.4.0` soon anyway.

Okay seems like the best idea, I will change it.

**Comment by roderickvd** [comment]
Sorry for having taken so long. For the final touch, would you please add a changelog entry? I will merge it after.

**Pull request merged**
