### PR TITLE
Add support for Sentry panic reporting

### PR DESCRIPTION
**Pull request by sashahilton00**
Ok, so the folks over at Sentry.io have given us a FOSS account for the project, allowing us to transparently collect panics when they occur in librespot. Members of librespot-org should be able to sign in and view reported issues, which should aid in triaging and fixing errors/bugs in the long run. Reporting requires no input from users, it is done automatically in the background. However, I'd like views on whether we want to add this, as doing so increases the size of the binary by approx. 5MB in debug mode, due to the need for TLS to secure communication. Also, if people don't feel that this will be useful, we shouldn't bother merge it. Thoughts?

### CODE REVIEW

**Comment by michaelherger** [comment]
The way you implemented it Sentry would only be added to the librespot executable, but not the library? This way it wouldn't work in my application which uses librespot as a binary?

I think that's a good decision. 

Would it only be part of the dev build? Maybe it should be a (opt-out) feature?

**Comment by plietar** [comment]
I'm *very* opposed to such a "feature". This would upload user data (even if not sensitive) to a 3rd party without any consent from the user.

If this is implemented at all, this should at the very least be a runtime opt-in that makes it very clear to the user what is happening, along with a compile time opt-in or out to avoid the extra cost.

I also believe this should, if implemented at all, go into librespotd, not librespot.

**Comment by sashahilton00** [comment]
Adding a compile time/runtime flag isn't difficult, I did mention one previously in Gitter but just didn't implement as there didn't seem to be much of a view either way. 

@michaelherger 

It has been deliberately kept in the binary, as people using the library probably don't want the extra bloat, and if they do, it's a trivial change to make manually.

@plietar

Concern for data security is completely justified, though Sentry has a pretty good track record, and is used by a number of large companies (Uber, Microsoft, Airbnb, Dropbox, Mozilla, etc. see [here](https://sentry.io/customers/) for a full list.), so I'm not too concerned that there is going to be dodgy behaviour on their behalf. Most of the data is not sensitive anyway, and consists of backtraces primarily, and in the event that private data is uploaded, they have a number of safeguards, such as data scrubbing, to remove sensitive data before it is visible in the dashboard. See [here](https://docs.sentry.io/learn/sensitive-data/)

With regards to librespot vs. librespotd, it went into librespot first simply because I had main.rs open for librespot already. I've ported it to librespotd locally as well, since librespotd is just a copy/paste of main.rs atm.

I'll add the compile time and runtime flags, but I would suggest that we print a line at the very beginning of librespot(d) explaining that we use sentry, and what the runtime flag to opt out is, rather than go for an opt-in approach. The reason for this is mainly that this is meant as a productivity improvement, an end to issues where the user uploads a log without a backtrace, and is then unable to reproduce the bug once ```RUST_BACKTRACE=1``` is set. In addition to this, the average user that doesn't know to run the program with ```RUST_BACKTRACE=1``` is equally as unlikely to know to run with something like ```--enable-error-reporting```, whereas generally those who do not wish to send back error data are going to be more likely to know to run with ```RUST_BACKTRACE=1``` when reporting an error, and also know about/act on a ```--disable-error-reporting``` flag.

**Comment by plietar** [comment]
This isn't so much an issue of trusting Sentry, but about a fundamental principle. *We do not upload user data without explicit consent*. This is way outside the scope of an open source project of the scale of librespot. Productivity is not a big enough reason to sacrifice user privacy.

That private companies do this does not make a difference. They are in a very different position (a commercial product for most of them), with an EULA and a team of lawyers.

If you want to improve reports the first step is to set `RUST_BACKTRACE=full` by default. That only takes a few lines in `main.rs` and would go a long way already.

That being said, I'm still interested in hearing other people's opinion on the matter.

**Comment by sashahilton00** [comment]
I'm not worried about EULA and other legal stuff; the project is MIT licensed (as-is, no warranty), and is open source. If people don't want it, they can just remove/not compile it.

With regards to the user data without explicit consent, I guess it depends on what one calls user data. Personally I wouldn't call a backtrace user data, and in the event that anything does slip through the net, the data scrubber/project maintainers ought to catch it. Still, if one thinks the user data is the issue, and others feel the same, how would people feel if error reporting isn't included by default, but is opt-out if it is included at build time? 

Also, shouldn't we enable the full backtrace regardless, since it's costless to do so?

**Comment by awiouy** [comment]
I prefer logs/traces to remain local to the device on which they are generated. Moreover, Sentry appears to add many dependencies unrelated to librespot and to inflate the size of the binary. I therefore respectfully disagree.

By default, logs/traces should be as complete as possible, with an option to reduce/suppress them for stable/embedded/unattended devices. We could provide the user a simple standard way to upload debug information (eg a binary to upload to pastebin or similar).

Is it possible to force RUST_BACKTRACE=full in main.rs? Where is this documented?

**Comment by kingosticks** [comment]
Personally I'm against these schemes, especially when it's opt-out. 

Also, this may sound harsh but the user being required to provide a log/backtrace at least shows they are willing to support the developers to fix the issue. If there is a mechanism to force RUST_BACKTRACE in debug builds that'd be good (I don't understand why it isn't the default in Rust).

**Comment by sashahilton00** [comment]
Ok, so the response here is that this PR was misguided, and as such I'll close it. I'm also going to enable RUST_BACKTRACE=full in librespot for the binary in all release modes, since it costs nothing, and should prevent useless backtraces in issues.

**Pull request closed without merging**
