### PR TITLE
Log error instead of panicking when child fails to start

### PR DESCRIPTION
**Pull request by roderickvd**
librespot currently panics when `onevent` programs fail to start, which seems a bit harsh -- there's nothing in the way of resuming music streaming. This PR handles this gracefully.

### CODE REVIEW

**Comment by sashahilton00** [comment]
I believe we decided to make it panic originally as we assumed a valid, functioning program as a prerequisite, hence the panic meant that any error caused an immediate failure as opposed to continuing regardless. I'm indifferent as to whether it logs or panics, I can see arguments for both.

**Comment by Johannesd3** [comment]
IMHO, Rust programs _should_ never panic. Panics are actually meant for logic errors, i.e. programmer's mistakes. The proper way is to propagate the error down to the main function, and terminate the program printing an error message.

**Comment by sashahilton00** [comment]
That's fair enough. Given that it spits out an error if the script fails, I think we can probably change this behaviour as I agree, panicking does feel heavy handed.

**Comment by roderickvd** [comment]
> IMHO, Rust programs _should_ never panic. Panics are actually meant for logic errors, i.e. programmer's mistakes. The proper way is to propagate the error down to the main function, and terminate the program printing an error message.

Is this we want to improve in general? There is a *lot* of `.expect()` and `.unwrap()` going on for operations that may well fail (e.g. incorrect command line parameters, failure to open an audio backend) that could be made nicer. It's not high priority but I'd be willing to invest some time in it.

**Pull request merged**
