### PR TITLE
Proxy support in tokio migration

### PR DESCRIPTION
**Pull request by Johannesd3**
Adding a git dependency of a hyper_proxy version with tokio 1.0 support. It is not yet merged, and as far as I see there was no reaction of the maintainer: tafia/hyper-proxy#18.

### CODE REVIEW

**Comment by ashthespy** [comment]
@Johannesd3 While you are at it, do you think you could place this behind a feature flag? 
(from back then https://github.com/librespot-org/librespot/pull/191#issuecomment-424040306)

**Comment by Johannesd3** [comment]
Yes, sure. But while we're at it, would you please explain me why hyper_proxy _and_ proxytunnel.rs are necessary?

**Comment by Johannesd3** [comment]
Most crates are in our dependency tree anyway. I'm more worried that hyper_proxy is no longer actively maintained.

**Comment by ashthespy** [comment]
Good question, but from a quick glance, the AP resolution stuff could also be handled by adapting `proxytunnel.rs` -- @janderholm would be the right person to answer..

**Comment by janderholm** [comment]
If I recall, it was quite a long time ago, proxy servers are usually configured to only support CONNECT if the destination port is 443. Any normal HTTP request such as apresolve need to implement the full proxy standard.

If it's possible to resolve through port 443 then the proxy tunnel could probably be used. The server is going to need to support CONNECT anyway so requiring it for resolve as well is reasonable.

**Comment by Johannesd3** [comment]
HTTPS://apresolve.spotify.com/ seems to work, so is there any reason not to use proxy tunnel?

**Comment by janderholm** [comment]
In my opinion, if you manage to hook it up, go for it :-)

**Comment by Johannesd3** [comment]
Wait, is hyper used only for apresolve? We could replace it with reqwest which supports proxies.

**Comment by ashthespy** [comment]
@Johannesd3 no, we use hyper for discovery as well (but as a server)

**Comment by Johannesd3** [comment]
Reqwest uses hyper internally, so probably it won't add many dependencies even if we keep hyper. So what do you think?

**Comment by ashthespy** [comment]
> 
> 
> Reqwest uses hyper internally, so probably it won't add many dependencies even if we keep hyper. So what do you think?

Personally, I'd prefer not to pull in reqwest just to handle this AP query..
If we can't use the existing `proxytunnel.rs` a simple(r) option would be to just always use the fallback AP when using a proxy?

**Comment by Johannesd3** [comment]
It's already odd to use hyper for this simple query. There are at least some projects that rely on core but not on connect (like ncspot) and I really wonder how much it would decrease compile time if hyper was no dependency.

Using reqwest it could be something like this:

```rust
async fn request() -> reqwest::Result<APResolveData> {
    Client::new()
        .get(APRESOLVE_ENDPOINT)
        .send().await?
        .json().await
}
```
`reqwest` uses the system proxy which is given by the `http_proxy` and `https_proxy` env vars by default. I think this is really tempting, but this decision is not up to me.

We must implement [this trait](https://docs.rs/hyper/0.14.2/hyper/client/connect/trait.Connect.html) for proxytunnel. It doesn't seem to hard, I will take a look at it.

**Comment by plietar** [comment]
`https://apresolve.spotify.com/` requires a TLS library, which is a whole other can of worms.

I’d say using reqwest saves us a lot of trouble. Actually I’ve even been thinking of opening an issue on reqwest to split out the proxy code (or at least make it public). Then we can replace proxytunnel.rs, which, unlike reqwest, does not support https or socks proxies.

If people actually care about build times / binary size that much, we can make apresolve (always use the fallback) and proxy support optional. Then all the hyper/reqwest depencies go away (obviously discovery still needs hyper).  I’d rather not until someone actually complains about it though.

——

I don’t know how I feel about reqwest using environment variables when we also have a flag for it. Maybe if proxytunnel is replaced by reqwest’s proxy implementation then we can start using the environment variables and deprecate the flag. Until then we should tell reqwest to use a proxy if and only if the flag is set.

**Comment by Johannesd3** [comment]
Apresolve should work now with proxytunnel, but I'm not sure about the problems @janderholm mentions.

**Comment by sashahilton00** [comment]
I thought `extern crate` was more or less phased out in rust 2018

**Comment by Johannesd3** [comment]
@ashthespy We could merge this, and think about using hyper_proxy or reqwest later, or what do you think? At least it works now (I think), which was previously not the case.

**Comment by ashthespy** [comment]
@Johannesd3 Don't have the time to test this now, but if you are happy with it, will merge in..

**Comment by Johannesd3** [comment]
Yes, I would prefer this. Testing with a local proxy server instance worked, and after all it's just a WIP branch...

**Pull request merged**
