### PR TITLE
General fixes to protobuf bindings, depreciation warnings and publish.sh

### PR DESCRIPTION
**Pull request by sashahilton00**
Should fix the rust docs error mentioned by @ashthespy in Gitter. Also updates the publish script with some minor tweaks to deal with lock file and issues with remote server timing.

Have also fixed the depreciation warnings by removing redundant description methods and changing `description()` instances to use `to_string()`

N.B. This is non-functional atm, build.rs/lib.rs needs further updating.

### CODE REVIEW

**Comment by ashthespy** [comment]
@sashahilton00  have you seen the upstream issue and this particular "solution" https://github.com/stepancheg/rust-protobuf/issues/324#issuecomment-476109276?

That being said, I am not sure why we need to change this for docs.rs at all - don't we check in the generated files to git to begin with? So `build.rs` should not have to re-write anything when we publish on crates.io. Or am I missing something?

**Comment by sashahilton00** [comment]
I saw a solution similar to that on SO. I foolishly thought I could just change the destination from src to OUT_DIR and it would work, but it turns out it's not that simple, hence the fist commit in this or doesn't fix the build.rs issue. I've started the solution mentioned upstream, not at home today though so might have to wait a bit, feel free to jump ahead of me on that if you want it fixed as soon as possible.

**Comment by sashahilton00** [comment]
Ok perhaps I'm just having a bad day but I'm struggling to get this build.rs script working. I keep hitting a `must reside in include path` error whilst trying to include these files. Will take a look again tomorrow but I'm missing something currently.

**Comment by sashahilton00** [comment]
And as I post that, I get it working. C'est la vie. I'm not familiar with the rust docs build process, but I believe this should fix it. Essentially it creates the proto bindings at compile time as opposed to retaining the generated bindings in the repo. This will cause a slight performance hit, but the main brrier that we faced previously whereby the user was required to have protobuf installed on the system is no longer an issue now that we use the pure rust version of protobuf. Thus I figured generating at compile time is not longer such a burden. Feel free to disagree/amend if you think these assumptions are poor.

**Comment by sashahilton00** [comment]
Have done my best to test this in a sandbox using `Bubblewrap`, it should fix the docs.rs issue. If there are no objections I'll merge this.

**Pull request merged**
