### PR TITLE
Format according to rustfmt guidelines

### PR DESCRIPTION
**Pull request by sashahilton00**
These changes were generated by running ```cargo fmt --all``` against the project. Will let Travis build to confirm all is good, then merge.

### CODE REVIEW

**Comment by plietar** [comment]
Can you update `.travis.yml` to test this

**Comment by sashahilton00** [comment]
@plietar it looks to already do checking to a certain extent. https://github.com/librespot-org/librespot/blob/master/.travis.yml#L25

I'm running fmt in stable rust atm, Do you want me to just modify the travis script to run ```cargo fmt --all -- --write-mode diff``` for all rust versions except 1.20.0?

**Comment by plietar** [comment]
I thought stable didn't work yet (https://github.com/librespot-org/librespot/pull/159).
I'm just talking about changing `--package=librespot-core` to `--all`

**Comment by sashahilton00** [comment]
It doesn't work yet, in the sense that one gets the warnings, but since they're warnings, it's not going to cause a build to fail. Still, will leave it as nightly only until it's fully compatible with the stable release. Will push a commit for the travis update in a bit, just working on #130 atm.

**Comment by sashahilton00** [comment]
Will rework this once #166 is done

**Pull request merged**
