### PR TITLE
Move remaining errors to AlsaError

### PR DESCRIPTION
**Pull request by JasonLG1979**
If the error is returned to player move the error string to the AlsaError enum.

### CODE REVIEW

**Comment by JasonLG1979** [comment]
@roderickvd I figured you like it if all possible error strings were moved up into the `AlsaError` `enum`.

**Comment by JasonLG1979** [comment]
@roderickvd as a side note I just tested the error handling by unplugging my DAC during playback. It failed as expected but it leaked error messages into our output.

```
[2021-06-20T18:25:53Z WARN  librespot_playback::audio_backend::alsa] Error writing from AlsaSink buffer to PCM, trying to recover, ALSA function 'snd_pcm_writei' failed with error 'EPIPE: Broken pipe'
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8548:(snd_pcm_recover) cannot recovery from underrun, prepare failed: Broken pipe
[2021-06-20T18:25:53Z ERROR librespot_playback::player] Fatal error, could not write audio to audio sink: Error writing from AlsaSink buffer to PCM, recovery failed, ALSA function 'snd_pcm_recover' failed with error 'EPIPE: Broken pipe'
```

This is obviously not directly our output.
```
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8548:(snd_pcm_recover) cannot recovery from underrun, prepare failed: Broken pipe
```

I think that may be due to the `try_recover` in the bindings?

```rust
    pub fn try_recover(&self, err: Error, silent: bool) -> Result<()> {
        if let Some(e) = err.errno() {
            self.recover(e as c_int, silent) // <-- Here it does not seem to capture the error from recovery?
        } else { Err(err) } // <-- Here instead of returning the the error from recovery it returns the original error.
    }
```

Either that or it's leaking in from another thread?

**Comment by JasonLG1979** [comment]
Nope, it's not `try_recover` I tried basically recreating it but actually capturing the error from `recover` and no change, it still leaks. It must be leaking from another thread or something? Although I still don't like that `try_recover` just returns the original error. Looking at the C in ` snd_pcm_recover` it seems maybe it's possible that ` snd_pcm_recover` can return an error other that what it receives?

**Comment by JasonLG1979** [comment]
As a side note I think I've managed to simplify ` write_bytes` in `alsa.rs`.

Here's my version:

```rust
    fn write_bytes(&mut self, data: &[u8]) -> io::Result<()> {
        for i in data.iter() {
            self.period_buffer.push(*i);
            if self.period_buffer.len() == self.period_buffer.capacity() {
                self.write_buf()?;
                self.period_buffer.clear();
            }
        }

        Ok(())
    }
```

Vs what it is currently:

```rust
    fn write_bytes(&mut self, data: &[u8]) -> io::Result<()> {
        let mut processed_data = 0;
        while processed_data < data.len() {
            let data_to_buffer = min(
                self.period_buffer.capacity() - self.period_buffer.len(),
                data.len() - processed_data,
            );
            self.period_buffer
                .extend_from_slice(&data[processed_data..processed_data + data_to_buffer]);
            processed_data += data_to_buffer;
            if self.period_buffer.len() == self.period_buffer.capacity() {
                self.write_buf()?;
                self.period_buffer.clear();
            }
        }
        Ok(())
    }
```

I have no idea if they compile down to something different and/or if there is a performance difference but my version is certianly more concise.

**Comment by JasonLG1979** [comment]
I pushed the above to `write_bytes` if you don't like it or think it needs to be a separate PR I can revert it.

**Comment by JasonLG1979** [comment]
Yep as @kingosticks points out my refactor is a an epic fail. So I'm going to revert it. Hey, I tried,lol!!!

**Comment by roderickvd** [comment]
Principally I think the code checks out but I wonder if we need so many different error types. There are the generalized `HwParams` and `SwParams` errors, and the different `Unsupported*` errors I understand too, it's something you could catch and do differently. But why drill down in separate `Parsing*` errors and even the `Drain`? What would be useful use cases for such explicit errors?

**Comment by JasonLG1979** [comment]
> Principally I think the code checks out but I wonder if we need so many different error types. There are the generalized `HwParams` and `SwParams` errors, and the different `Unsupported*` errors I understand too, it's something you could catch and do differently. But why drill down in separate `Parsing*` errors and even the `Drain`? What would be useful use cases for such explicit errors?

Fair enough. I figured you'd like removing error strings from the "working" code. If you like you can close this. No hard feelings.

As a side note on a side note (lol) my simplified buffer code is actually the same speed (give or take a couple 100 nanosecs) as the current code if this playground gist I made is correct.

https://gist.github.com/rust-play/0d833117d5f5798e7dcfefbd2d934ad9

**Comment by JasonLG1979** [comment]
> What would be useful use cases for such explicit errors?

The main reason for such explicit errors is since you insist on forwarding the errors messages up to the player they will be printed there which means someone may have no idea *where* in the code the error actually happens because the error message lists it's line number from where it was printed in player. The were is just as important as the why or even more so sometimes. If you don't know where you're left hunting for error strings in the code and if they're generic you may have multiple places that throw the same string.

**Comment by JasonLG1979** [comment]
That's one reason I'm more of a fan of printing error messages where they actually happen and let the caller silently fail as opposed to the current situation.

**Comment by JasonLG1979** [comment]
I'm going to go ahead and close this as it doesn't really seem to add any value. @roderickvd if you disagree or think there's more to discuss feel free to re-open.

**Pull request closed without merging**
