### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by JasonLG1979**
Update dependencies and clean up some clippy lints in preparation of an eventual 0.4 release.

### CODE REVIEW

**Comment by JasonLG1979** [comment]
@roderickvd Shouldn't we just bump the dev branch's MSRV to the latest stable (currently 1.61.0) if we're going to release soon since the release will be stuck at that version?

**Comment by roderickvd** [comment]
I think we don’t have to live at the bleeding edge. Trailing behind a few releases is good enough functionality-wise and gives some headroom for users for their updates, and not force it on them.

**Comment by roderickvd** [comment]
I see now it’s about updating to Rust 2021. I’d really not jump yet if not so necessary. And it isn’t, because `alsa-0.6.0` chose to change Rust editions for no reason at all. I would prefer that they revert that single line in their own `Cargo.toml` and everything would compile just fine.

**Comment by JasonLG1979** [comment]
Well it is but it isn't my counterpoint to your argument is:

1. Even on Linux where you can install distro build rust, no one really does they use `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` to install the latest version anyway. So a MSRV of less than the current stable for a dev branch is silly.

2. The "bleeding edge" is only the bleeding edge for a very short time. The new API branch is still in pretty heavy development it will be a while before it's ready to be 0.5 (or whatever?) When 0.4 is released it will basically be a snapshot in time. IMHO it's better that that snapshot not represent the past since people will be using 0.4 for a long time.

3. I plan on going though and updating all the deps to there very latest versions but that's basically a one by one thing to make sure there are no bugs and whatnot.

**Comment by roderickvd** [comment]
This is something we disagree on and have discussed before. Unless a majority of the contributors feel otherwise, I'm holding on to the policy to bump MSRV only if essential for functionality or security.

**Pull request closed without merging**
