### PR TITLE
Port #976

### PR DESCRIPTION
**Pull request by JasonLG1979**

### CODE REVIEW

**Comment by JasonLG1979** [comment]
And fix clippy warnings along the way...

**Comment by roderickvd** [comment]
Thanks!

**Comment by roderickvd** [comment]
Yes all better now, thanks! Just too occupied at the moment to get my head down on `new-api` again. Will get back at it later again.

**Comment by JasonLG1979** [comment]
It's all good. I've started to play around with writing a proper "AudioPipline" still in the spitballing phase.

**Pull request merged**
