### PR TITLE
Migrate to futures 0.3 / tokio 1.0

### PR DESCRIPTION
**Pull request by Johannesd3**
Here's an attempt to migrate librespot to futures 0.3 and tokio 1.0. I'm sorry if this is competing with #487, but I had already started, when I saw this PR (that has been inactive for a while). It's totally ok if you decide in favour of the other PR, but nonetheless I want to offer my help.

The crates core, metadata, audio and playback will compile, but of course that doesn't mean that they'll work correctly. (I was not sure how to test it before finishing everything). However, I had to remove the proxy support in apresolve.rs, since I wasn't able to get hyper-proxy to work with hyper 0.14.

The remaining crate librespot_connect seems to be the hardest, I wasn't able to make any progress here. I still hope my PR is of some help.

Edit: This tokio_migration branch is far behind dev, so the [comparison to dev](https://github.com/librespot-org/librespot/compare/dev...Johannesd3:futures_migration) is perhaps better.

### CODE REVIEW

**Comment by Johannesd3** [comment]
I created a repository to test my PR: [Johannesd3/librespot-player](/Johannesd3/librespot-player). It works, but the sound is twice as fast and noisy. Any ideas why?

**Comment by marcelbuesing** [comment]
Awesome work! I just tested it with your librespot-player and had the same issue when using the pulseaudio-backend feature. I exchanged that with the gstreamer-backend and playback speed seems fine now.

**Comment by Johannesd3** [comment]
Pipe-backend and piping to pacat sounds good too. I did not touch any backends, so this seems funny.

**Comment by Johannesd3** [comment]
The same issue already occurs in dev, it has nothing to do with this PR. #540 may be the cause. I will file an issue.

**Comment by marcelbuesing** [comment]
Btw. the git commit history of the PR seems a little weird and messes up the Github diff. I assume it would probably make sense to do something like starting the branch fresh from dev cherry-picking your changes and force pushing afterwards so the PR is updated.

**Comment by Johannesd3** [comment]
The PR is totally up to date with dev (see the link to the comparison in the description). The 120 additional commits are simply the difference between librespot-org:tokio_migration and librespot-org:dev.

**Comment by marcelbuesing** [comment]
> The PR is totally up to date with dev (see the link to the comparison in the description). The 120 additional commits are simply the difference between librespot-org:tokio_migration and librespot-org:dev.

Sorry you are right, I did not see that you are planning to merge into tokio_migration, totally makes sense now.

**Comment by Johannesd3** [comment]
But you're right, this isn't optimal. Either someone must update tokio_migration, or I will change the target of this PR to dev.

**Comment by sashahilton00** [comment]
Have merged `dev` with `tokio_migration`

**Comment by sashahilton00** [comment]
You may need to rebase after that merge, there's something weird going on with conflicts.

**Comment by Johannesd3** [comment]
Closing in favour of #581.

**Pull request closed without merging**
