### PR TITLE
simplify get_factor

### PR DESCRIPTION
**Pull request by JasonLG1979**
Less math and logic that follows the spec.

### CODE REVIEW

**Comment by roderickvd** [comment]
It does look sweeter. But don't you want to print those warning messages? It hints the amount of pregain a user might want to set.

**Comment by JasonLG1979** [comment]
I would just tell them to use their ears.

**Comment by roderickvd** [comment]
Why remove something that was handy? I found it handy if not for the purpose of debugging.

**Comment by JasonLG1979** [comment]
The math and messages where not correct. The threshold has nothing to do with basic normalization and you can't say how much actually is being dynamically limited without knowing how long the transient peak is and doing a bunch more math taking the knee into consideration. The most you can say is either the track is subject to some limiting or that the gain was not raised as much as the user would like to avoid clipping.

**Comment by roderickvd** [comment]
That's true. Anything we can do about that?

**Comment by JasonLG1979** [comment]
My thought is that a level >= threshold should be a info level message basically saying hey you're bumping up against the limiter. And levels >= dBFS should be a hey you're in danger of possibly clipping warning message.

**Comment by JasonLG1979** [comment]
@roderickvd there I added back and improved upon (I think at least) the messages. I think that should about do it unless there's anything you like changed.

**Comment by JasonLG1979** [comment]
The dreaded `Error: Process completed with exit code 101.`...

**Comment by roderickvd** [comment]
Thanks I think it's good to have those even when they aren't super-exact.

One thing I wonder is, could we come up with a more concise name for `DBFS_RATIO`? I think you mean the level ("ratio") when the PCM is 0 dB from scale?

**Comment by JasonLG1979** [comment]
> One thing I wonder is, could we come up with a more concise name for `DBFS_RATIO`? I think you mean the level ("ratio") when the PCM is 0 dB from scale?

Yes. The replay gain spec defines a peak gain of 1.0 to be dBFS. Again just going off your code if you feed 0.0 (dBFS) into your `db_to_ratio` function you get 1.0.


https://wiki.hydrogenaud.io/index.php?title=ReplayGain_1.0_specification#Peak_amplitude
> The maximum peak amplitude value is stored as a floating point number, where 1.0 represents digital full scale.

I'm not married to the name though. It can be whatever you'd like maybe `RG_DBFS`? "RG" **R**eplay**G**ain?

**Comment by JasonLG1979** [comment]
BTW. I've been playing with your limiter by driving it with a pre-gain of +6 and playing modern rock and metal to get a feel for the over all "sound" of the limiter. I gotta say it's not bad at all. At that level you can obviously hear the compression if you know the song but it doesn't really distort it just ducks a little like you'd expect from driving it that hard.

Metallica Sad But True for example at +6 pre-gain is 1.69 dB above the threshold and honestly I've heard worse. It still sound less compressed than the Radio.

All in all I think it's a big winner. Good job.

**Comment by JasonLG1979** [comment]
There, better?

**Comment by roderickvd** [comment]
That’s good to hear man!

It’s not just that it’s a ReplayGain spec that defines 1.0 as dBFS. That’s just the way it is with PCM represented as a float, ReplayGain or not. That’s why I’m still looking for a more concise name. 

Other than that the code is looking good so if we could find a better name then we can get this merged quickly.

**Comment by JasonLG1979** [comment]
I'm open to suggestions? Like I said I don't really care what you call it.

**Comment by roderickvd** [comment]
I propose `PCM_AT_0DBFS` or along those lines.

**Comment by roderickvd** [comment]
Sorry to be such a pest but the 0 isn't redundant. A PCM represented as "1.0" in float is 0 dBFS. Not "any" dBFS or "PCM" decibel from scale.

**Comment by JasonLG1979** [comment]
> Sorry to be such a pest but the 0 isn't redundant. A PCM represented as "1.0" in float is 0 dBFS. Not "any" dBFS or "PCM" decibel from scale.

Whatever you like.

**Comment by JasonLG1979** [comment]
There.

**Comment by JasonLG1979** [comment]
@roderickvd Merge this and your PR so I can release a new Raspotify version and close https://github.com/dtcooper/raspotify/issues/504 and roll these into a new release.

**Pull request merged**
