### PR TITLE
Implement additional metadata for Artist

### PR DESCRIPTION
**Pull request by dnlmlr**
- The `AlbumGroups` containing `Vec<Albums>` is not flattened into a single `Albums` since the each contained Albums is a collection of different versions of the same album
- So to get the current version of an album only the first `Album` of each `Albums` in `AlbumGroups` has to be used
- The `portrait_group` in `Biography` is flattened since there is no point in the additional abstraction and it only needs to be implemented once

Please check and verify that I implemented the concepts in the correct way. I tried to reference the implementations of the other metadata types for this

### CODE REVIEW

**Comment by dnlmlr** [comment]
I added convenience functions to just get the current / latest version / release of each album from an artist. This is what you would want 99% of the time as it gives you a list of the albums without duplicates, just as you would get on spotify.

I'm not sure about the naming of these functions. If there are any other suggestions feel free to change it or comment and I will change it

**Comment by dnlmlr** [comment]
Actually collecting the `Iterator<Item = SpotifyId>` into `Artists` is not great since it will alloc the `Vec` every time. I did this mainly to be consistent with `Album::tracks`, but it might be a good idea to change both of those to just return the iterator instead. 
One slightly annoying thing about that would be that the item type has to be the same type `T` that is in `Artists(pub Vec<T>)` and the same for `Track`. If that type changes like in #1018 the Iterator types have to be updated manually as well since there is nothing like `Artists::InnerType` or similar type abstractions

**Comment by roderickvd** [comment]
This is great work man :heart: this looks good to me. Are you ready to merge? Maybe add some documentation what these `*_current` helper methods do -- it may not be immediately obvious that there are otherwise multiple versions of an item.

I like your suggestion to return an iterator. This would warrant a separate PR not just for this struct, but have it ubiquitous throughout metadata. In `playlist/list.rs` you see that the `Playlist` struct is decorated on top of an inner `SelectedListContent`. Maybe that can serve as an example for having inner structs.

**Comment by dnlmlr** [comment]
Good point with the comments! Other than that it's ready to merge. I'll add some comments and then you can merge it

**Comment by roderickvd** [comment]
Great, let me know when you're good to go.

**Comment by roderickvd** [comment]
:+1: will squash and merge now.

**Comment by dnlmlr** [comment]
Sorry, I missed `cargo fmt`. I force pushed over the last commit

**Pull request merged**
