### PR TITLE
Refactor Cache and remove Volume struct

### PR DESCRIPTION
**Pull request by Johannesd3**
This PR suggest a refactor of Cache. 

The `Volume` struct was removed, since its only purpose was to read and write a single integer in a file. Its logic was moved to `Cache`, as well as the functions to store `Credential`s to disk. It recently became possible to split audio and system cache (#506), so this PR makes the paths in `struct Cache` optional. Also, error handling and logging was improved. It contains some breaking changes.

Here are some random thoughts and questions about the cache I had while writing this PR. Some of this is stuff for future PRs.
* The `Cache` feels now very "threefold". The struct could neatly be divided into three independent structs. It's basically twice the same code for volume and credentials, and even the code for audio files is similar. Is there any abstraction possible to avoid repetition? 
* Why are audio cache and "system cache" in a single struct anyway? The audio cache is only needed in the audio crate, and the system cache is mainly used in the connect crate and the application. 
* Would it be possible to use file-system-level copy to store audio files in cache? As far as I understand, the audio files are temporarily stored on disk.
* The cache should use async file system operations (but this could happen in the tokio migration where it is much more convenient)
* With #518, the audio cache is flushed whenever an error occurs. This should handle the case of a full disk, but it was not distinguished between "No space left" and other errors, and I'm not aware of how to check this in Rust platform-independently. ~~(This functioniality is currently not present in this branch but could be added again.)~~ In #34 and #558 was suggested to limit the cache size. Any smart solutions for these problems?

### CODE REVIEW

**Comment by sashahilton00** [comment]
I think this is more elegant than #580. The Volume struct isn't worth having given that we're basically just saving an integer imo.

**Comment by Johannesd3** [comment]
Yes, I agree now. I will close the other PR.

**Comment by sashahilton00** [comment]
Cache has been up for discussion a few times. Ideally what we're looking for is something that can have a size limit set, and will then prune the least recently accessed files first. I agree though that the cache logic could be better though. It might be worth thinking about spinning it out into a separate crate, though this feels like overkill. 

One of the things that might be interesting to consider is that once we move to the CDN (#309) for downloading the audio files, there might be an existing request library with caching built in. https://docs.rs/static-http-cache/0.2.0/static_http_cache might be interesting, especially if we move towards using reqwest as mentioned in the tokio proxy migration PR, though one would have to investigate to see whether it was actually suitable.

In terms of splitting the cache out entirely, there could be a few possible upsides. Once contained within it's on crate, it becomes possible to implement multiple caching strategies such as space vs age based, whilst also having different behaviour for purging old files (wipe cache, remove oldest files first, etc.). Additionally, it then becomes possible to have caching as a compile time flag (enabled by default), for those that don't want any caching functionality.

**Comment by Johannesd3** [comment]
Thanks for the summary, most of it sounds reasonable imho. Some additional thoughts:

Why should the "cache" be bothered with credentials and volumes? It's rather configuration than cache and should be handled by the application instead of the library. We would need a nice api to retrieve reusable credentials and volume.

Maybe creating an AudioCache trait would be a good idea. If it unifies the cache and the tempfiles, we could even get rid of all file system dependencies in the audio crate. Downside: this wouldn't be compatible with the static-http-cache idea, I think.

---

While the best solution can be argued about, I think my PR is still worth merging. It's getting rid of all those `unwrap`s, and I don't think Librespot should panic just because it can't write something to cache.

**Comment by sashahilton00** [comment]
Yes, we should merge this in the meantime. Further discussion of reworking the cache should probably take place in #34

**Comment by Johannesd3** [comment]
@sashahilton00 I removed the commit that bumped the alsa dependency to let it happen in its own PR.
@LaurentLouf I rewrote parts of the cache. Can you confirm that the behaviour in case of a full cache is still the same?

**Pull request merged**
