### PR TITLE
Implement common SinkError and SinkResult

### PR DESCRIPTION
**Pull request by JasonLG1979**
* Implement common `SinkError` and `SinkResult` for use with all backends.

* `impl From<AlsaError> for SinkError` so `AlsaError`s can be thrown to `player` as `SinkError`s.

* `impl From<PulseError> for PulseError` so `PulseError`s can be thrown to `player` as `SinkError`s.

* Other backends can follow the same pattern as the alsa and pulseaudio backends for detailed errors in the future if someone wishes to implement them.

* A little code clean up and added blank lines to make it easier to read at a glance.

### CODE REVIEW

**Comment by roderickvd** [comment]
While I like this direction, I would prefer to not throw as `io::Error` but rather a `SinkError`. For inspiration take a look at how the decoder currently handles this.

**Comment by JasonLG1979** [comment]
> While I like this direction, I would prefer to not throw as `io::Error` but rather a `SinkError`. For inspiration take a look at how the decoder currently handles this.

You're talking about changing the return type in mod. That would instantly break every backend. That would mean I would have to fix all of the backends at once basically. That's not really something I want to do,lol!!!

I kinda like the idea of keeping `io::Error` as an interim stop gap. That allows us (hopefully other people will help?) to fix the backends one at a time and then finally when they're all up to snuff then we can implement `SinkError`.

From a possible regression/error standpoint I also think it would be better to make each backend fix a separate PR. It also makes for smaller jobs and easier to review code.

**Comment by JasonLG1979** [comment]
When all of the backends are eventually fixed by hopefully other people who actually use and care about them I volunteer to implement `SinkError`. I really only care that much about the PulseAudio and ALSA backends since that's basically I'm guessing what 99% of Linux users actually use. Pipe and subprocess I have to care about because they comes along for the ride no matter what but the other backends I care and know basically nothing about.

**Comment by roderickvd** [comment]
I'll think about it. I don't think changing it in all the backends would be that much work (as long as you keep further error improvements separate).

**Comment by JasonLG1979** [comment]
> I'll think about it. I don't think changing it in all the backends would be that much work (as long as you keep further error improvements separate).

There. You were right, it wasn't that bad. For the most part since most of the backends just unwrap and explode instead of actually throwing errors it was mostly just a matter of changing the return type on functions they override.

I'm not married to the error names or strings. I was just trying to keep it simple. I'm open to any and all suggestions.

**Comment by JasonLG1979** [comment]
@roderickvd on a totally unrelated note, looking at the alsa binding source,  this endian check is redundant as it's already done in the bindings:

```rust
        #[cfg(target_endian = "little")]
        AudioFormat::S24_3 => Format::S243LE,
        #[cfg(target_endian = "big")]
        AudioFormat::S24_3 => Format::S243BE,
```

https://github.com/diwic/alsa-rs/blob/9065d2eddf3a705762e5c368eb297c6f9804572a/src/pcm.rs#L490-L491

**Comment by JasonLG1979** [comment]
@roderickvd on an unrelated note I put in a [PR to the alsa bindings](https://github.com/diwic/alsa-rs/pull/78) so hopefully we can stop worrying about endianness in our backend. Not that it's a huge concern but still.

**Comment by roderickvd** [comment]
I see they were already merged upstream, great!

**Comment by JasonLG1979** [comment]
> I see they were already merged upstream, great!

Yep so I guess when the next version is released we can use `Format::s24_3()`.

**Comment by JasonLG1979** [comment]
@roderickvd I think this about ready for a review when you get a chance.

**Comment by roderickvd** [comment]
Shall we do #823 first?

**Comment by JasonLG1979** [comment]
> Shall we do #823 first?

Sure. You've already started the review process. No matter the order I will need do a little bit of tweaking on the one that gets merged 2nd anyway. I tried to make them contained as possible but it was inevitable that there would be a little bit of bleed though.

**Comment by roderickvd** [comment]
Alright, last one!

**Comment by JasonLG1979** [comment]
There's a little bit of work to be done in resolving the conflicts beyond what github would have you believe. I'll give it a go after work over the next day or 2.

**Comment by JasonLG1979** [comment]
If all goes well that should do it as far as fixing the conflicts.

**Comment by JasonLG1979** [comment]
Ok @roderickvd I think this is done for real this time :smiley: That last one was just a bonus. :laughing:

**Comment by roderickvd** [comment]
Great! I'll check it out and I think we have a `0.3.0` on our hands!

**Comment by roderickvd** [comment]
Working fine for me so far :heart: let's merge this, give it a bit of exposure and ping @sashahilton00 for a release somewhere the coming weekends?

**Pull request merged**
