### PR TITLE
Gracefully handle lost network connections

### PR DESCRIPTION
**Pull request by kaymes**
Currently librespot tends to panic as soon as something goes wrong with the server connection. Lost server connections can have a variety of causes such as network issues or a spotify server becoming unavailable. Librespot should recover from lost server connections gracefully and reconnect and/or wait for a new connection from a client. 

Here I made a series of changes that convert panics into proper error handling in case of lost connections.

* A lost network connection no longer causes a panic. Instead errors and channel closures are propagated through the system.
* When the session shuts down, the mercury and channel components are shut down as well and all channels of pending requests are dropped. This notifies pending requests and allows them to handle the situation. This is a necessary to avoid deadlocks. (e.g. the player thread might not join otherwise).
* Spontaneous shutdown of sqirc in main no longer causes a panic. Instead libreelec interprets it as a connection lost situation and attempts to re-connect with the same credentials. I added a limiter such that no further re-connection attempt is made if 5 re-connects happened within the last 10 minutes. In this case it just waits for another client to connect. This is more a precaution in case spirc shutdowns are triggered by protocol changes or similar one day.

### CODE REVIEW

**Comment by sashahilton00** [comment]
This seems like a good solution for the short term. We've discussed session re-connection in the past in #134 which is coming soon™. In short, there doesn't appear to be a quick and easy way to implement session re-connection such that minor issues (eg. a temporary network blip) can be recovered without user intervention in the form of reconnecting their device.

**Comment by sashahilton00** [comment]
Closes #417

**Comment by sashahilton00** [comment]
closes #417

**Comment by Saniq** [comment]
Hi, great work so far.
Unfortunately librespot panics while attempting to re-connect if the network connection has not been re-established.
To be exact it is `addr.to_socket_addrs().unwrap()` in `connection::connect` causing the panic.

**Comment by kaymes** [comment]
I went through the code that establishes connections and replaced the unwraps with proper error handling.
@Saniq please try again.

**Comment by Saniq** [comment]
Thanks, your fix resolved the issue.
Now librespot tries to re-connect to a spotify server once and then waits for a new client to connect if the attempt fails.

**Pull request merged**
