### PR TITLE
Add support for HTTP proxy

### PR DESCRIPTION
**Pull request by Fulkerson**
This pull request adds support for tunneling librespot data through an HTTP proxy. It relies on the fact that most http proxies support CONNECT to hosts on port 443.

A CONNECT results in the proxy tunneling all incoming data as is and is commonly used for TLS connections.

### CODE REVIEW

**Comment by Fulkerson** [comment]
I believe there is something wrong with the Travis builds. The console output seem to indicate `PKG_CONFIG_ALLOW_CROSS=1` is not set when cross compiling. It has to be set or pkg-config will not work.

**Comment by sashahilton00** [comment]
Indeed. I'm hesitant to merge this functionality though, as librespot doesn't use HTTPS anywhere (it only uses http to check apresolve.spotify.com), and hence openssl is not only a big dependency to include, but also entirely redundant in this case. I believe that librespot uses system proxy settings anyway?

**Comment by sashahilton00** [comment]
This request would also need to update the travis.yml file accordingly to enable cross compilation, and require OpenSSL be installed on any system wishing to use it, which can be a PITA.

**Comment by Fulkerson** [comment]
I didn't realize I had added openssl as a dependency! It must be the proxy library, I'll see if I can get rid of it.

**Comment by sashahilton00** [comment]
Looking at the commit, I think you just added hyper-proxy, but that it includes support for TLS, which in turn depends on OpenSSL :/

**Comment by Fulkerson** [comment]
I decided to skip trying to resolve an ap when using proxy and use the fallback directly. If and when there's a good library for making proxy requests that does not require SSL I'll revisit it.

I also think I've finally wrapped my head around futures and realized how I could move the proxy setup to it's own future. It's much nicer this way.

@sashahilton00 It seems something has happened with rustfmt so those tests fail pretty badly currently. Other than that it is green!

**Comment by sashahilton00** [comment]
yeah something in rustfmt changed, you'll need to run ```cargo fmt --all``` with a nightly to fix it. Can we close this pull request for now given that there is no immediate solution?

**Comment by Fulkerson** [comment]
What do you mean by close? I was hoping it could be merged since it solves the general case of running librespot behind a HTTP proxy. Using the fallback AP always for now should be fine I think.

**Comment by sashahilton00** [comment]
Sorry, didn't realise you had rewritten the code to avoid using TLS, assumed that when you mentioned revisiting that you hadn't found a workaround. Before this can be merged, you'll need to run ```cargo fmt --all``` with rust nightly and push a commit to fix the formatting. Will test this once that's done.

**Comment by Fulkerson** [comment]
Right, I wasn't very clear on that. It is passing now!

**Comment by Fulkerson** [comment]
Since https://github.com/tafia/hyper-proxy/pull/3 was merged I was able to fix the resolving of APs as well. Also made sure the proxy is allowed to resolve the remote url instead of resolving it directly.

I had to update the lowest rust librespot requirement to 1.21.0 though as there were version conflicts and removing Cargo.lock resulted in dependencies that are not buildable on 1.20.0

**Comment by Fulkerson** [comment]
The reason for it not working is that the proxy address needs to be in the form of a URL. Specifically only `http://host:port` is supported. I've updated the pull request with better validation of the input as well as changed from String to url::Url for proxies as it is a better representation.

There are other proxy types (https, socks4, socks5) so i think it is better to be strict about it from the start.

If you provide a proxy URL to somewhere that doesn't exist you are still going to end up with a "connection refused" but hopefully it is now more difficult to accidentally end up with invalid proxy URLs.

I'll update the wiki with info about proxies but the format is `http://host:proxy` and it uses `--proxy` or the `http_proxy` environment variable

**Comment by sashahilton00** [comment]
Sorry it's taken a while, just tested and works fine with the format you mentioned. Not too worried about the port error, as proxy is a fairly edge user case. Merging.

**Comment by michaelherger** [comment]
Looks as if this change reverted many of the formatting changes applied a few weeks ago? IMHO that's not good, as it kills the history in git. It makes it really hard to find the actual code changes :-(.

**Comment by Fulkerson** [comment]
@michaelherger Running `cargo fmt --all` on latest nigthly is a requirement for integration and they keep changing the behaviour. It is `cargo fmt --all` that caused this and I put it in a [separate commit](https://github.com/librespot-org/librespot/commit/612978908f5c6817e48c569cdd55b8b60bbf5a2d) to make it easier to find the actual changes to the code.

I agree the formatting changes are messing up the history (difficult to run git blame for example) and I personally dislike automatic code formatters for this reason. However I also think rust is a difficult language to format nicely manually. I think the best thing we can do is to make sure the result of `cargo fmt --all` is put in separate commits for now and hope rustfmt stabilizes.

On the other hand it encourages people to mainline their changes to avoid difficult merge conflicts, so perhaps it isn't so bad after all!

**Comment by michaelherger** [comment]
Fair enough. I'd be happy to mainline my changes. But they're very specific - and often ugly and hackish, lack of better Rust/librespot understanding :-). I doubt any of it would be desirable in mainline :-).

The formatting discussion is something I've been fighting in various projects before... But if `cargo fmt` still is changing all the time, should we really apply it? Once it's stable, why not. But if that causes large chunks of the code base to change all the time, then it's really not any helpful at all.

**Comment by ashthespy** [comment]
Do you think it would be better to make this optional? The binary is becoming quite distended off late. 
```shell
librespot$ cargo build --no-default-features --features 'alsa-backend' --release
librespot$ ls -l --block-size=M ./target/release/
total 14M
drwxrwxrwx 1 ash ash  1M Sep 24 18:00 build
drwxrwxrwx 1 ash ash  1M Sep 24 18:03 deps
drwxrwxrwx 1 ash ash  1M Sep 24 18:00 examples
drwxrwxrwx 1 ash ash  1M Sep 24 18:00 incremental
-rwxrwxrwx 1 ash ash  1M Sep 24 18:03 liblibrespot.d
-rwxrwxrwx 2 ash ash  1M Sep 24 18:03 liblibrespot.rlib
-rwxrwxrwx 2 ash ash 14M Sep 24 18:03 librespot
-rwxrwxrwx 1 ash ash  1M Sep 24 18:03 librespot.d
drwxrwxrwx 1 ash ash  1M Sep 24 18:00 native
```

```shell
git checkout 431be9e847a584d374ec44e7c138525dd8fbb9d6
librespot$ cargo build --no-default-features --features 'alsa-backend' --release
librespot$ ls -l --block-size=M ./target/release/
total 13M
drwxrwxrwx 1 ash ash  1M Sep 24 18:11 build
drwxrwxrwx 1 ash ash  1M Sep 24 18:14 deps
drwxrwxrwx 1 ash ash  1M Sep 24 18:00 examples
drwxrwxrwx 1 ash ash  1M Sep 24 18:00 incremental
-rwxrwxrwx 1 ash ash  1M Sep 24 18:14 liblibrespot.d
-rwxrwxrwx 2 ash ash  1M Sep 24 18:14 liblibrespot.rlib
-rwxrwxrwx 2 ash ash 13M Sep 24 18:14 librespot
-rwxrwxrwx 1 ash ash  1M Sep 24 18:14 librespot.d
drwxrwxrwx 1 ash ash  1M Sep 24 18:00 native
```
This might not give a completely accurate picture, as there were some  other changes b/w master and the commit I checked out, but still `hyper-proxy` contributes:
```
├── hyper-proxy v0.4.1
│   ├── bytes v0.4.7 (*)
│   ├── futures v0.1.21 (*)
│   ├── hyper v0.11.25 (*)
│   ├── tokio-core v0.1.17 (*)
│   └── tokio-io v0.1.6 (*)
```

**Comment by Fulkerson** [comment]
@ashthespy If you want to decrease the binary size it is better to start off by tweaking the build options. By adding the following to Cargo.toml you should be able to decrease the size substanially:

```
[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false
```

Don't forget to strip the resulting binary with _strip -s_

If you still need to get the size down try out _cargo bloat_ to find big offenders. Also since both hyper-proxy and librespot uses things like tokio-core, tokio-io, hyper and futures you should be able to decrease the size further by aligning the crate versions.

**Comment by ashthespy** [comment]
@Fulkerson  Yep, have already done the usual suspects to reduce size (`-Zstrip-debuginfo-if-disabled=yes`)
and after reading https://clap.rs/2018/01/09/new-years-weight-loss/ found cargo bloat and have been working towards aligning crates.  But in the end, it would be nice to break all these features into - features! ;-)

**Pull request merged**
