### PR TITLE
CI: Replace Travis with Github Actions

### PR DESCRIPTION
**Pull request by jnqnfe**
Fixes: #428

I converted my own crates earlier today and being on a roll I took care of this for you too.

Example successful run (before I tidied up the final commits):
https://github.com/jnqnfe/librespot/actions/runs/422461988

Not done:
 - The caching stuff.
 - The webhook notifications, since I could not find a solution.
 - The `fast_finish` setting. There's a `fail-fast` setting which I've used, but this does not seem to do what `fast_finish` does.

I believe otherwise it's essentially equivalent.

### CODE REVIEW

**Comment by ashthespy** [comment]
Just a thought - could we keep travis until we iron out these actions?

**Comment by jnqnfe** [comment]
> Just a thought - could we keep travis until we iron out these actions?

If that's what you want, I can drop that commit...

**Comment by toabctl** [comment]
Why is the new test not executed in **this** PR?

**Comment by jnqnfe** [comment]
> Why is the new test not executed in **this** PR? At least I don't see the results under the `Show all checks` link

@toabctl I would presume that github only uses the GA config once it's actually merged into the repo PRs target. I wonder what would happen if you make a PR to modify an existing GA config, does the existing config or the modified one get executed for that PR?

**Comment by jnqnfe** [comment]
@ashthespy I dropped the commit removing travis as requested, I'm not sure if you noticed.

**Comment by sashahilton00** [comment]
Looks good, let's give it a go.

**Pull request merged**
