### PR TITLE
Update subscription uri

### LINKED ISSUE #288: Starting playback fails if uri or context_uri is provided
Starting the playback of an album over spotify connect
Endpoint: `me/player/play?device_id=d9464366ec73e0eda87dc781314f8f25d1df7469` 
Data: `{'context_uri': 'spotify:album:6eGYLONkDMja0MNtZWnRRB'}`

Results in the librespot player debug output:
```
INFO:librespot_playback::player: Loading track "Intergalactic (In The Style Of Beastie Boys) [Performance Track with Demonstration Vocals]" with Spotify URI "spotify:track:6ZjubGKa55CYxN9a4LlOV1"
INFO:librespot_playback::player: Track "Intergalactic (In The Style Of Beastie Boys) [Performance Track with Demonstration Vocals]" loaded
```
This is the last track I played on my desktop spotify player

If I try to just start playback
Endpoint `me/player/play?device_id=d9464366ec73e0eda87dc781314f8f25d1df7469`
Data: `{}`

Results in no further output but playback of the above loaded track starts.

Update:

Request for single track using normal uris:
Endpoint: `me/player/play?device_id=d9464366ec73e0eda87dc781314f8f25d1df7469`
Data: `{'uris': ['spotify:track:5fpizYGbi5IQoEraj6FP0R']}`

This is on HEAD of master d2cadec4190a44572b1d5d5daed4f0eda1c2b921

### PR DESCRIPTION
**Pull request by forslund**
This fixes an issue loading new tracks probably caused by an update on spotify's side. The fix was suggested by @worleydl, all glory to them for figuring it out.

Resolves #288

### CODE REVIEW

**Comment by sashahilton00** [comment]
@kingosticks once you've tested and confirmed working, we'll merge this.

**Comment by kingosticks** [comment]
Yep. Works perfectly again for me too. Thanks @forslund and @worleydl.

**Comment by IsaacWoods** [comment]
Similar URIs appear elsewhere in the codebase ([here](https://github.com/librespot-org/librespot/blob/d12640fb478cc6536ae798057bbc6d1c84e0c598/metadata/src/lib.rs#L107), [here](https://github.com/librespot-org/librespot/blob/d12640fb478cc6536ae798057bbc6d1c84e0c598/metadata/src/lib.rs#L152) and [here](https://github.com/librespot-org/librespot/blob/d12640fb478cc6536ae798057bbc6d1c84e0c598/metadata/src/lib.rs#L197)). Has anyone confirmed whether these have moved?

**Comment by aksel** [comment]
Similarly, but not metadata, [here](https://github.com/librespot-org/librespot/blob/431be9e847a584d374ec44e7c138525dd8fbb9d6/connect/src/spirc.rs#L217).

**Comment by sashahilton00** [comment]
Hmmm, we should probably update the url at #217 in `spirc.rs`, as mentioned above, as that's essentially the same problematic endpoint. From what I can surmise though, metadata, users, etc. are all seperate services in Spotify's backend, and thus the necessary update to the URI of the users endpoint doesn't necessarily coincide with a change in the metadata endpoint. I suggest we leave the metadata uri's the same until a similar problem is encountered.

**Comment by forslund** [comment]
The L217 in `spircs.rs` is what this PR addresses, or am I missunderstanding something?

**Comment by sashahilton00** [comment]
No you missed nothing, I did.

**Comment by aksel** [comment]
You are right, and I am blind :~)

**Pull request merged**
