### PR TITLE
Enable pulseaudio device names

### PR DESCRIPTION
**Pull request by kaymes**
Pass the device name to the pulseaudio backend if --device was specified.

### CODE REVIEW

**Comment by ashthespy** [comment]
Fixes #207 
?

**Comment by kaymes** [comment]
@ashthespy: yes, it fixes #207.

**Comment by ashthespy** [comment]
I don't have access to a linux box, so can't test - @kaymes if it looks/works fine for you will go ahead and merge it..

**Comment by kaymes** [comment]
It works for me.

**Pull request merged**
