### PR TITLE
Merge dev into tokio_migration and fix warnings

### PR DESCRIPTION
**Pull request by Johannesd3**
... and fix (new?) clippy lints. Clippy didn't like the naming of some types and enum variants, consecutive upper letters are probably reserved for constants.

Maybe it's possible to fast-forward this merge to avoid an additional (useless) merge commit, but I'm no github pr expert.

### CODE REVIEW

**Comment by Johannesd3** [comment]
Is it too much CI @sashahilton00 ?

**Comment by sashahilton00** [comment]
@Johannesd3 it looks fine. My only concern is whether the tests on the various different systems are run in parallel and ho long they take, not sure how much resource Github grants projects to run CI workloads.

**Comment by Johannesd3** [comment]
No, that's to much. It's 100 minutes per run, and I think that's 20 runs per month, that's not enough. (I don't know why macos suddenly failed.)

**Comment by kingosticks** [comment]
Github actions is free for public repos, right? It's only private repos that have the 2k monthly limit.

**Comment by Johannesd3** [comment]
Didn't know that, thx. Another inconvenience: It will take twice as long (15min) until the tests are finished ...

I will try to rebase this PR using the latest changes from `dev`, and try to fix the macOS problem

**Comment by Johannesd3** [comment]
The target directory should rather be cached by os + rustc version, but I have no idea how to achieve this.

Anyway, I will close this PR and reopen it, as I want to see how much caching improves the speed.

**Comment by kingosticks** [comment]
Any idea why the `Run cargo test --workspace` step after `Run cargo build --workspace --examples` does more compilation, including some of the same stuff again? Is that right?

**Comment by Johannesd3** [comment]
Yes, those `#[cfg(test)]` blocks are only considered if the tests are executed, but not if the examples are compiled, so every crate needs to be compiled again.

**Comment by Johannesd3** [comment]
Next try to check caching again, hopefully it's the last try. Sorry for spamming you.

**Comment by Johannesd3** [comment]
I don't quite understand the macOS error :(  Apparently it's caused by caching, but I don't know why.

**Pull request closed without merging**
