### PR TITLE
examples/playlist_tracks: Add error message for bad ID

### PR DESCRIPTION
**Pull request by jforberg**

### CODE REVIEW

**Comment by roderickvd** [comment]
This is partly correct. Specifically there now exist playlist URI's with five parts too:
https://github.com/librespot-org/librespot/blob/c067c1524fadf55bc710f6908bc1656b64c08efa/core/src/spotify_id.rs#L162-L166

**Comment by jforberg** [comment]
How about this?

**Comment by kingosticks** [comment]
Weren't 5-part playlist URIs made extinct: https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/

**Comment by roderickvd** [comment]
Thanks for the quick update @jforberg.

@kingosticks I did not know that. In `new-api` I noticed in `librespot-java` and I just took it from there. @devgianlu what's your experience?

**Comment by roderickvd** [comment]
Well, without a reply from the others, let's get this in. I think it's a good clarification for now. Removing a potentially derelict 5-part playlist URI can be a separate PR if necessary.

**Pull request merged**
