### PR TITLE
Fix depreciation warnings, bump Travis version to 1.30.0

### PR DESCRIPTION
**Pull request by sashahilton00**

### CODE REVIEW

**Comment by sashahilton00** [comment]
Gonna let this sit for a couple of weeks as it just removes a depreciation message, and thus isn't worth bumping rust versions up just yet.

**Comment by willstott101** [comment]
Just FYI in https://github.com/librespot-org/librespot/pull/293/commits/7a03a2ce999fddb6005fb8f7a77c1165936078ef I had to re-implement some functions which are now in the standard library (since 1.26) to support 1.23

**Comment by sashahilton00** [comment]
@willstott101 you can lose those functions now, we bumped to 1.26.0 a couple of days ago

**Comment by sashahilton00** [comment]
Rust 1.34.0 released, merging this.

**Pull request merged**
