### PR TITLE
Update protobufs

### PR DESCRIPTION
**Pull request by roderickvd**
Tracking the protobufs extracted in #734.

To decide which new protobufs should go in, I intend to take cue from `librespot-java`:
https://github.com/librespot-org/librespot-java/tree/802ecf8cca8e30ca794f9fbd923a2486bf8630df/lib/src/main/proto

### CODE REVIEW

**Comment by kingosticks** [comment]
It's been literally years since I last looked at this part, just to check: by removing "unused" protobuf definitions are you removing types/functions that people may have been using? E.g if someone was using the search definitions for their player based on librespot.

**Comment by roderickvd** [comment]
To be unambiguous:

- "Unused" means that they were never built by `librespot-protocol`: https://github.com/librespot-org/librespot/blob/b0a94f901d47300db0e24a13f64596d1e8adfd8b/protocol/build.rs#L18-L30

- "Legacy" means that they no longer exist in the [latest](https://github.com/librespot-org/librespot/files/6033341/spotify_protobufs.zip) [protobufs](https://github.com/librespot-org/librespot/files/6446732/spotify_protos.zip).

I can't be sure of course, but thought it was unlikely because of point 1.

**Comment by kingosticks** [comment]
Super, thanks. I'm just wary of breaking changes when it's a library that's potentially used in all kinds of ways we don't realise. There was talk a while ago of separating the protobuf defs out into their own project for others to use but since that never happened and since we were not building these ones I think unused is a reasonable assumption.

**Comment by ashthespy** [comment]
Anything against just keeping all the new/updated definitions checked in? The unused proto definitions don't come at any extra cost to the codebase, other than extra files in the repo. Even if we don't use it now, it is good to have an overview. 

There was originally talk of maintaining these definitions in an external repo, so the different ports can all use them, but given how things have diverged, may not make much sense.  We also have a copy over at [spotify-analyze](https://github.com/librespot-org/spotify-analyze/tree/master/dissect/proto) for on-the-fly packet decoding.

**Comment by roderickvd** [comment]
> Anything against just keeping all the new/updated definitions checked in? The unused proto definitions don't come at any extra cost to the codebase, other than extra files in the repo. Even if we don't use it now, it is good to have an overview.

Sure, we could do that.

I am also thinking about moving the legacy protobufs (which we still need to authenticate I believe) to a separate "legacy" directory/namespace. Haven't checked if that would give any issues but I guess that should work, and provide some clarity to distinguish between what's current and what's historic, but still a code requirement.

> There was originally talk of maintaining these definitions in an external repo, so the different ports can all use them, but given how things have diverged, may not make much sense. We also have a copy over at [spotify-analyze](https://github.com/librespot-org/spotify-analyze/tree/master/dissect/proto) for on-the-fly packet decoding.

Anyone can still use the `librespot-protocol` crate separately of course, or pull it in as a Git submodule.

**Comment by kingosticks** [comment]
> I am also thinking about moving the legacy protobufs (which we still need to authenticate I believe) to a separate "legacy" directory/namespace. Haven't checked if that would give any issues but I guess that should work, and provide some clarity to distinguish between what's current and what's historic, but still a code requirement.

Personally I don't think this is worth doing.

**Comment by roderickvd** [comment]
Meaning you oppose the idea or would rather spend time differently? It’s my time so no need to worry about that 😄

**Comment by kingosticks** [comment]
I dont see why we need to move things to a legacy namespace, especially when we are using them. It's confusing.

**Comment by roderickvd** [comment]
Not saying you're not right, but looking from another perspective I thought it would be confusing to have one directory with all the currently extracted protobufs, _plus_ ones you won't find anymore. That's not very consistent either.

I don't particulary care either way, I am just looking to make it as clear as possible. Could also tag legacy protobufs with a code comment at the top of the file -- I'll be tagging them with "extracted at YYYY-MM-DD" lines anyway to keep track.

**Comment by ashthespy** [comment]
Given that the files are checked in via git, personally don't see the need for any special name spacing or additional tags.

**Comment by roderickvd** [comment]
Can do that if @sashahilton00 would let me know which version he used in https://github.com/librespot-org/librespot/discussions/734#discussioncomment-725121.

**Comment by sashahilton00** [comment]
I have no idea unfortunately - I just pulled them from the latest client at the time.

**Comment by sashahilton00** [comment]
Actually, I just checked, and saw that I made a note of the version at the time I extracted the protobufs. version is `1.1.53.608.g7ed9c03a` @roderickvd

**Comment by roderickvd** [comment]
No worries @sashahilton00 I managed to extract from the latest 1.1.61.583 myself and tag them accordingly, thanks though.

In 1.1.61.583, there are certain protobufs missing that I was able to extract from 1.1.33.569, some of which are still necessary like `connectivity.proto` and `spotify/clienttoken/v0/clienttoken.proto`. I compared the two versions, and also imported the ones from 1.1.33 that had no obvious match in 1.1.61.

By "no obvious match" I mean that message names that have gone plain missing in 1.1.61, and had no new counterpart. Example of the opposite is `context_player.proto` with a `message ContextPlayer` that _is_ in 1.1.33 and no longer in 1.1.61, however, in 1.1.61 there's a new `context_player_ng.proto` with a message `ContextPlayerNg` and the same fields.

For the venerable `authentication.proto`, `keyexchange.proto`, `mercury.proto`, and `spirc.proto` I could not find any versions to extract them from, I've gone back as far as 2016. The first three we will still need. `pubsub.proto` _may_ have been replaced by `PubSubCountPerIdent.proto` but the fields don't match up so I don't exactly see how, and kept it in.

What remains to be done for this PR is the following: `librespot-java` made some stub protobufs for ones they could not extract, but were necessary anyway. There's a chance the real protobufs have now been imported from 1.1.33 (`librespot-java` looked at earlier Spotify versions, but not *that* early), but just to be sure I will check if we are still missing some. If so I will copy the stubs from `librespot-java`, we have gotten the permission to relicense under MIT.

Finally, it is clear that the current `playlist4*.proto` protobufs are now legacy and need to be replaced with the new `playlist` ones. I won't do this under this PR because it will be breaking. For now I think that this PR plus @Johannesd3's earlier work on the websocket handler is the foundation we need, and next up will be commencing the breakfest until we get to working state again.

**Comment by roderickvd** [comment]
Final diff notes from having compared with `librespot-java`:

1. Previously there were `canvaz` and `canvaz-meta` protobufs. There now is `canvas`. It mostly matches up, however, `canvaz` deals with `repeated Canvaz canvases` and `canvas` just with a single `CanvasRecord`, whose fields are the same. I wonder if this will have to be gotten from a different endpoint. For now I'll leave the old `canvaz` out.

2. Interestingly, one field _disappeared_ from `TransferState` in the latest version: `creation_timestamp`. Probably won't matter but interesting nonetheless -- in almost all other cases fields are added, not removed.

In all, keeping all protobufs around amounts to 360+ files where we only need like 30 or 40 for playback. Unless someone objects to keeping them all, I'll be merging this into `new-api` shortly.

**Pull request merged**
