### PR TITLE
Update protobuf

### PR DESCRIPTION
**Pull request by ashthespy**
Was digging around and found the right name for it - `kSupportsExternalEpisodes`

I can't generate the proper files for now however as I can't seem to find  a `protoc` version 2 that I can install and use.

### CODE REVIEW

**Comment by michaelherger** [comment]
Out of interest: does this solve a known problem?

**Comment by ashthespy** [comment]
Nope - just for completeness.

**Comment by ashthespy** [comment]
I bumped up `protobuf` and build the files directly from the rust toolchain with `protoc-rust`.  Still needs `protoc` though. 

This should also also incorporate the parsing of unknown enum fields fix that was merged upstream.

**Comment by michalfita** [comment]
The tool is available from here:
https://github.com/protocolbuffers/protobuf/releases/tag/v3.6.1
Version 2 can be selected via command line argument.

**Comment by ashthespy** [comment]
@michalfita with the change to `protoc-rust` you just need `protoc` in your path. `apt` should have it under [`protobuf-compiler`](https://packages.ubuntu.com/search?keywords=protobuf-compiler)

**Comment by sashahilton00** [comment]
We might have to bump rust from 1.21, but this shouldn't be an issue. Will look at this tomorrow.

**Comment by sashahilton00** [comment]
@ashthespy is 1.27.0 the min. version? for choice want to keep the min version as low as possible, hence wondering if you tested say 1.24.0 or if 1.27.0 was just a stab in the dark

**Comment by ashthespy** [comment]
@sashahilton00 no, didn't test anything lower than `1.28.0`. The `1.27.0` comes from the other commit referenced.
Either way I've posted across at https://github.com/stepancheg/rust-protobuf/issues/298

**Comment by stepancheg** [comment]
FYI rust-protobuf since version 2 supports [pure-rust codegen](https://github.com/stepancheg/rust-protobuf/tree/master/protobuf-codegen-pure) (it doesn't require `protoc` command). It should be compatible to `protoc`-based codegen (and it is not, please file a bug report).

**Comment by sashahilton00** [comment]
@ashthespy keeping lowest version number allows more people to compile easily. expecting everyone to always be running latest version of rust would be nice, but unlikely to be the case.

will look into pure rust codegen, would be good to remove the dependency on protoc, since it can be a bit tricky to set up.

**Comment by ashthespy** [comment]
I looked into the `pure-rust-codegen` as well, but got a bit deterred by the disclaimer at the bottom of the page. But shall compare both and submit a PR when I find some time!

**Pull request merged**
