### PR TITLE
Obtain spclient access token using login5 instead of keymaster (Fixes #1179 and #1245)

### LINKED ISSUE #1179: Error 403
Hello,

suddenly my librespot instance on libreelec stopped playing any songs.

```
[2023-06-20T05:24:59Z INFO  librespot] librespot 0.5.0-dev d07b2ce (Built on 2023-06-18, Build ID: e4T4YlCt, Profile: release)
*** WARNING *** The program 'librespot' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
[2023-06-20T05:24:59Z INFO  librespot_playback::mixer::softmixer] Mixing with softvol and volume control: Log(60.0)
[2023-06-20T05:24:59Z INFO  librespot_playback::convert] Converting with ditherer: tpdf
[2023-06-20T05:24:59Z INFO  librespot_playback::audio_backend::alsa] Using AlsaSink with format: S16
[2023-06-20T05:24:59Z INFO  librespot_core::session] Connecting to AP "ap-gew4.spotify.com:4070"
[2023-06-20T05:24:59Z INFO  librespot_core::session] Authenticated as "11127372133" !
[2023-06-20T05:24:59Z INFO  librespot_core::session] Country: "CZ"
[2023-06-20T05:25:08Z INFO  librespot_core::spclient] Resolved "gew4-spclient.spotify.com:443" as spclient access point
[2023-06-20T05:25:08Z ERROR librespot_core::mercury] error 403 for uri hm://keymaster/token/authenticated?scope=playlist-read&client_id=65b708073fc0480ea92a077233ca87bd&device_id=78f3d06ba0952bdccb9e15230ae4f8c6891f6292
[2023-06-20T05:25:08Z ERROR librespot_connect::spirc] ContextError: Error { kind: Unavailable, error: Response(MercuryResponse { uri: "hm://keymaster/token/authenticated?scope=playlist-read&client_id=65b708073fc0480ea92a077233ca87bd&device_id=78f3d06ba0952bdccb9e15230ae4f8c6891f6292", status_code: 403, payload: [[123, 34, 99, 111, 100, 101, 34, 58, 52, 44, 34, 101, 114, 114, 111, 114, 68, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 34, 58, 34, 73, 110, 118, 97, 108, 105, 100, 32, 114, 101, 113, 117, 101, 115, 116, 34, 125]] }) }
[2023-06-20T05:25:08Z ERROR librespot_core::mercury] error 403 for uri hm://keymaster/token/authenticated?scope=playlist-read&client_id=65b708073fc0480ea92a077233ca87bd&device_id=78f3d06ba0952bdccb9e15230ae4f8c6891f6292
[2023-06-20T05:25:08Z ERROR librespot_playback::player] Unable to load audio item: Error { kind: Unavailable, error: Response(MercuryResponse { uri: "hm://keymaster/token/authenticated?scope=playlist-read&client_id=65b708073fc0480ea92a077233ca87bd&device_id=78f3d06ba0952bdccb9e15230ae4f8c6891f6292", status_code: 403, payload: [[123, 34, 99, 111, 100, 101, 34, 58, 52, 44, 34, 101, 114, 114, 111, 114, 68, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 34, 58, 34, 73, 110, 118, 97, 108, 105, 100, 32, 114, 101, 113, 117, 101, 115, 116, 34, 125]] }) }
[2023-06-20T05:25:08Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId("spotify:track:4vGFfCD9PvBuKDbTourDdW")>: ()
[2023-06-20T05:25:08Z ERROR librespot_core::mercury] error 403 for uri hm://keymaster/token/authenticated?scope=playlist-read&client_id=65b708073fc0480ea92a077233ca87bd&device_id=78f3d06ba0952bdccb9e15230ae4f8c6891f6292
[2023-06-20T05:25:08Z ERROR librespot_playback::player] Unable to load audio item: Error { kind: Unavailable, error: Response(MercuryResponse { uri: "hm://keymaster/token/authenticated?scope=playlist-read&client_id=65b708073fc0480ea92a077233ca87bd&device_id=78f3d06ba0952bdccb9e15230ae4f8c6891f6292", status_code: 403, payload: [[123, 34, 99, 111, 100, 101, 34, 58, 52, 44, 34, 101, 114, 114, 111, 114, 68, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 34, 58, 34, 73, 110, 118, 97, 108, 105, 100, 32, 114, 101, 113, 117, 101, 115, 116, 34, 125]] }) }
```

I think it is similar to #972 if it is not the same, but I have not found any way how to fix it yet...

```
~ # curl http://apresolve.spotify.com/
{"ap_list":["ap-gew4.spotify.com:4070","ap-gew4.spotify.com:443","ap-gew4.spotify.com:80","ap-gue1.spotify.com:4070","ap-gew1.spotify.com:443","ap-guc3.spotify.com:80"]}
```

### PR DESCRIPTION
**Pull request by lmore377**
This PR is a copy of #1220 as that one seems stale. This resolves the issue where authentication fails when spotify connect is started from a desktop client.

Fixes #1179 and #1245. Tested and works with clients from Android, iOS, Windows, Linux and macOS.

I still need to resolve the review comments from #1220, I'm just opening this now to keep track of changes.
I'm very inexperienced when it comes to rust so please be gentle 😆

Credits:
@kingosticks - Created the initial branch with the fix
@Gerrelt - Created the PR that this one is based on

### CODE REVIEW

**Comment by MarkParker5** [comment]
Hey @lmore377! I use this library in my project and faced the same issue. I really want this pull request to be merged ASAP. What's left to do? Maybe I can finish this.

**Comment by lmore377** [comment]
> Hey @lmore377! I use this library in my project and faced the same issue. I really want this pull request to be merged ASAP. What's left to do? Maybe I can finish this.

The review comments on #1220 just need to be looked over and applied here. I've been pretty preoccupied with other things and haven't really gotten around to sitting down and looking at this. One quick note, I noticed that auth broke again the other day even with this patch so there might be something more going on at Spotify's end. I'll check real quick.

**Comment by lmore377** [comment]
Yeah it seems like all forms of auth (even passing username and password with `-u` and `-p`) are broken with this PR. Main still works but like before, it only works when starting playback from a mobile device or passing `-u` and `-p`. I really don't know at all how the auth system works but from reading the verbose logs, it seems like librespot is able to set up the connection for control but for some reason it's failing to auth for playback. Unfortunately this is way out of my skillset so someone else is going to need to take the lead. If anyone wants permissions to work on my fork just let me know. Here's a log of connecting and trying to press play a few times for anyone interested (please let me know if there's any sensitive info in here I really don't know lmao):

[log.txt](https://github.com/librespot-org/librespot/files/14118384/log.txt)

**Comment by lmore377** [comment]
@roderickvd @kingosticks Do you guys have any idea about what could be going on here?

**Comment by roderickvd** [comment]
I don't know, I've been out of this for quite some time now. 

I checked that log and could be totally wrong, but it seems that librespot is doing a hard fail (shutting down) because it cannot dispatch a "social-connect/v2/session_update" command. That command probably really does not matter, so it should soft fail and ignore.

Spotify server-side does different things depending on the type of platform connecting, type of authentication you're using, current visibility of the moon, and the amount of fairy dust in the air, so it could be that authenticating this way triggers a bug that was not visible in librespot before.

**Comment by MarkParker5** [comment]
AFAICS this error is being handled and shouldn't cause a hard fail:

```rs
if let Err(e) = session.dispatch(cmd, data) {
    debug!("could not dispatch command: {}", e);
}
```
in `DispatchTask.poll`:
```rs
struct DispatchTask<S>(S, SessionWeak)
where
    S: TryStream<Ok = (u8, Bytes)> + Unpin;

impl<S> Future for DispatchTask<S>
where
    S: TryStream<Ok = (u8, Bytes)> + Unpin,
    <S as TryStream>::Ok: std::fmt::Debug,
{
    type Output = Result<(), S::Error>;

    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        let session = match self.1.try_upgrade() {
            Some(session) => session,
            None => return Poll::Ready(Ok(())),
        };

        loop {
            let (cmd, data) = match ready!(self.0.try_poll_next_unpin(cx)) {
                Some(Ok(t)) => t,
                None => {
                    warn!("Connection to server closed.");
                    session.shutdown();
                    return Poll::Ready(Ok(()));
                }
                Some(Err(e)) => {
                    session.shutdown();
                    return Poll::Ready(Err(e));
                }
            };

            if let Err(e) = session.dispatch(cmd, data) {
                debug!("could not dispatch command: {}", e);
            }
        }
    }
}
```
https://github.com/lmore377/librespot/blob/5a322e70e15d4e442a2d681609bb38eec8b31dc8/core/src/session.rs#L602-L604

I also checked the flow `DispatchTask.poll -> session.dispatch -> mercury.dispatch -> mercury.complete_request -> !found -> Err(MercuryError::Response(response).into())` and didn't find anything that looks like a reason for a hard fail. Meanwhile, I am not a rust developer and could have missed some details of the syntax, e.g. trailing "?" for ControlFlow::Break.

**Comment by gokberkkocak** [comment]
I'm also on linux and getting the same authentication problem. It's not a hard fail though, I think the log also includes the gracefully shutting via interruption as well. I believe the relevant part is:

```
[2024-01-31T23:04:40Z DEBUG librespot_core::spclient] Client token unavailable or expired, requesting new token.
[2024-01-31T23:04:40Z DEBUG librespot_core::spclient] Client token unavailable or expired, requesting new token.
[2024-01-31T23:04:40Z DEBUG librespot_core::http_client] Requesting https://clienttoken.spotify.com/v1/clienttoken
[2024-01-31T23:04:40Z DEBUG librespot_core::http_client] Requesting https://clienttoken.spotify.com/v1/clienttoken
[2024-01-31T23:04:40Z ERROR librespot_connect::spirc] ContextError: Error { kind: InvalidArgument, error: StatusCode(400) }
```

which I can provide the exact part with no-crash but in a non-playable state.

login5 client token:
image

---

I don't know how the client token is relevant to this process but that's the part just before the error and we cannot see any outcome of the client token process.

Building main and using no-discover cached authentication, I can verify that the client token step warns (but playable state) via `Unable to get client token. Trying to continue without...` (see below image), so at least the `Err` is used. However in this new auth method, client token does not result positive (i.e. `Got client token:`) or any negative one. Some other part is eating that result somewhere and it might be some other Err which might be key to solve this.

main client token:
image

---

Lastly, I don't know it's relevant but the comment on client token logic indicates on linux the old keymaster id is used.

> // on macOS and Windows.  On Android and iOS we can send a platform-specific client ID and are
        // then presented with a hash cash challenge. On Linux, we have to pass the old keymaster ID.

It might be possible that this new new login5 auth (that replaces keymaster auth) and mix usage of this old keymaster id on linux is causing issues.

**Comment by MarkParker5** [comment]
@gokberkkocak images are 404

**Comment by gokberkkocak** [comment]
Images are github hosted. I edited the comment to add the relevant parts as quote blocks if you are not able to load them.

**Comment by kingosticks** [comment]
I'll try take a look this week. Probably worth checking what the latest official clients are doing.

**Comment by MarkParker5** [comment]
Hello, any updates? @kingosticks did you have a chance to take a look?

**Comment by kingosticks** [comment]
I'm sorry, I didn't. I've had a backlog to get through but I'm basically done to the point where librespot is blocking me so I have to get into this again. Will try asap.

**Comment by hamishfagg** [comment]
@kingosticks don't want to be that guy but any updates?

**Comment by kingosticks** [comment]
It seems I am that other guy, the one who doesn't have any update. I did start looking at librespot again but I got distracted by something in gstreamer-rs and made no progress on this actual problems here. Over the next few weeks I'll either have a lot of free time or no free time and I'll have to wait and see where I land.

**Comment by hamishfagg** [comment]
No worries, i definitely understand how that goes 😅

It seems like (at least for me) librespot is completely broken now, where it was working intermittently for a while. I'd love to help but i dont know rust at all and I'm in the same boat of too many things to do.

I'd be willing to pitch in some money to get this fixed if anyone else can help.  Maybe if a few others can do the same we can make it worth someone's time? I loved my multiroom spotify setup 😥

**Comment by kingosticks** [comment]
Just to clarify, is the maste branch not still working?

**Comment by rohoog** [comment]
Master works, dev does not: error 403 for uri hm://keymaster/token/authenticated?....

**Comment by hamishfagg** [comment]
Oh shoot. I can't remember what caused me to switch over to dev, but master is working for now..

**Comment by MarkParker5** [comment]
The minimal build with spotify connect always worked for me, the problem appeared when building with dbus control activated, probably because playback control is on the server side and requires a different type of authorization.

**Comment by lmore377** [comment]
I've pretty much abandoned this PR and it seems like authentication from the mobile app works fine now

**Comment by MarkParker5** [comment]
@lmore377 did you try building with dbus control enabled?

**Comment by lmore377** [comment]
What's the feature flag for it?

**Comment by MarkParker5** [comment]
Oh, several months have already passed since the last test. I've already forgotten many details. The flag is `use_mpris = true` in the [spotifyd config file](https://github.com/Spotifyd/spotifyd/blob/master/docs/src/config/File.md). Then the search for a solution led me to this PR as the end point, but now I’m starting to suspect that the reason is in spotifyd, and not in librespot.

**Comment by kingosticks** [comment]
Following Spotify's impending promised changes to authentication, I re-resurrected this into https://github.com/librespot-org/librespot/pull/1309

**Pull request closed without merging**
