### PR TITLE
modularize discovery (wip)

### PR DESCRIPTION
**Pull request by awiouy**

### CODE REVIEW

**Comment by sashahilton00** [comment]
FYI I'm also working on modularising things, and have pushed the https://github.com/librespot-org/librespot/tree/modularise branch. Only the keymaster commit is on github though. Would it be ok if you PR against the modularise branch so we don't end up both working on the same stuff? Then we can merge it all later on?

**Comment by awiouy** [comment]
Ah, ok. Will do tonight.

**Comment by sashahilton00** [comment]
Thanks. As it currently stands, I was basically planning on having a networking crate (for spirc and discovery), playback (for the sinks and mixers), and I've already moved keymaster into the core, though I'm not dead set on those, as spirc and discovery in the same crate feels a little clunky; suggestions welcomed.

**Comment by awiouy** [comment]
Work in progress here: https://github.com/awiouy/librespot/tree/discovery
Closing, will reopen if I manage.

**Pull request closed without merging**
