### PR TITLE
Clean up list_compatible_devices

### PR DESCRIPTION
**Pull request by JasonLG1979**
Fix a typo and be a little more forgiving.

### CODE REVIEW

**Comment by roderickvd** [comment]
LGTM from a code review -- when you say this is more forgiving, you mean with the `description` right?

**Comment by JasonLG1979** [comment]
Yes. Basically don't explode if name or description is None.

**Comment by JasonLG1979** [comment]
The basic idea is to just skip names that are `None` (which really shouldn't happen anyway I would think?) and that if a description is `None` it's not the end of the world (again, I wouldn't think that would happen either? And if it does :shrug:) The only real fatal error now is if `HintIter::new_str` fails.

**Comment by JasonLG1979** [comment]
I also looked into you error message leaks and it seems like a years old alsa bug portaudio actually works around it by setting a stub function as the error logging handler when it enumerates alsa outputs. Pyaudio does basically the same thing.

**Comment by roderickvd** [comment]
Yeah probably nothing we can do to quench that.

**Comment by roderickvd** [comment]
Now we have format testing working well, we can consider doing something like `--format auto` and going for the highest supported format (or do so if no `--format` is specified). This should be ubiquitous for all backends. For backends that don't support testing or automatic downcasting, we could fall back to 16 bit.

**Comment by JasonLG1979** [comment]
> Now we have format testing working well, we can consider doing something like `--format auto` and going for the highest supported format (or do so if no `--format` is specified). This should be ubiquitous for all backends. For backends that don't support testing or automatic downcasting, we could fall back to 16 bit.

I can do that real quick. Off the top of my head the highest supported format is basically going to be F32 for anything that goes though software (except alsa though a plug that's F64) which is basically everything except alsa and the pipe output (we can't really know for sure what pipe goes to?). So what I propose is to actually try to detect the format in alsa, make auto = S16 for pipe as not to break backwards compatibility and make auto = F32 for everything else.

**Comment by JasonLG1979** [comment]
Well, an auto format mode complicates dithering because we can't really know for sure what the format is going to be in alsa backend when dithering is set. All of the other backends we can tell what the format is going to be. We have 2 options:

1. Make dithering default to none. (the easiest choice and what would prefer.)
2. Make dithering dynamic in the sense that it depends on the backend's format and also give it a proper "auto" value.

**Comment by roderickvd** [comment]
Yes, because of that it's worth a discussion and certainly going to be opinionated.

I'd say iterate from S32 to S24 to S24_3 to S16, in order from highest to lowest, with dithering settings as they are now (enabled for S24, S24_3 and S16). For everything other than totally obscure DACs that actually do floating point, this will provide the highest quality output without depending on dithering in the backend.

When I did the dithering code I looked into the code of the various backends quite a bit. From what I recall:

 - Both Alsa and GStreamer accept F64
 - Alsa doesn't dither at all
 - GStreamer and PortAudio dither by default, but their randomness is not as good as ours. For this reason *and* to be sure not to dither twice, I disabled the native dithering of those backends. (Also setting `--dither none` and still having dithering downstream is not what you'd expect.)

Users that really know what they are doing an always select F64 or F32 themselves. For the other 99.9%, iterating over the integer samples with dithering will set them up for great SQ out of the box.

**Comment by JasonLG1979** [comment]
> Yes, because of that it's worth a discussion and certainly going to be opinionated.

Yes to what?

> S32 to S24 to S24_3 to S16

Can do.

You didn't really answer my question.

You can't know for sure in main, when the dither mode is set what the format will be if you choose auto because dithering is "dumb" right now.

**Comment by JasonLG1979** [comment]
Dithering would need to track the actual format used by the backends to work in an automatic fashion. Right now it does not do that. It's set in main and stays that way forever.

**Comment by roderickvd** [comment]
"Yes" to: dithering complicates things. Somewhere along the road I plan to rewrite the sample pipeline to use a generic `Sample<T>` with a builder pattern that can chain dithering. But that's in the future, after the new API.

Maybe this is more difficult now then I thought it would be. I'd have to think about it more.

**Comment by JasonLG1979** [comment]
Maybe this is more difficult now then I thought it would be. I'd have to think about it more.

An option for now is still defaulting to `S16` but make `auto` an option with the caveat that format `auto` == dither `none`?

I have that already done. It wasn't that hard.

**Comment by JasonLG1979** [comment]
I also found a clippy lint warning in the portaudio backend introduced in https://github.com/librespot-org/librespot/pull/920.

**Comment by JasonLG1979** [comment]
See for yourself:
`cargo clippy --no-default-features --features portaudio-backend`

**Pull request merged**
