### PR TITLE
lewton: handle OggError(NoCapturePatternFound)

### LINKED ISSUE #88: librespot built with lewton support crashes after first song
<a href="https://github.com/awiouy"></img></a> **Issue by [awiouy](https://github.com/awiouy)**
_Tuesday Sep 05, 2017 at 19:35 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/248_

----

librespot built with lewton support crashes after first song with the following messages:
```
thread '<unnamed>' panicked at ' error: OggError(NoCapturePatternFound)', /checkout/src/libcore/result.rs:860:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /checkout/src/libcore/result.rs:860:4
```

Running with RUST_BACKTRACE=1 does not provide further information:
```
thread '<unnamed>' panicked at 'Vorbis error: OggError(NoCapturePatternFound)', /checkout/src/libcore/result.rs:860:4
stack backtrace:
   0: <unknown>
```
The above messages were issued while using ALSA backend.

librespot was built with Rust 1.20.0:
`$CARGO_BUILD --no-default-features --features "alsa-backend pulseaudio-backend with-lewton"`

### PR DESCRIPTION
**Pull request by awiouy**
This fixes #88 
I could not find a way to distinguish `NoCapturePatternFound` without adding `ogg`

### CODE REVIEW

**Comment by sashahilton00** [comment]
Yup, not possible without ogg package, tried earlier. Thanks for sorting this

**Comment by awiouy** [comment]
@est31 could you expose ˋNoCapturePattern` in lewton, so that we do not need to add ˋogg` to handle it?

**Comment by est31** [comment]
@awiouy great idea, will do!

**Comment by est31** [comment]
@awiouy see the 0.8.0 update of lewton, it includes a commit to expose the `OggReadError` enum.

**Comment by sashahilton00** [comment]
@est31 doesn't it need to be ```pub use ogg::reading::OggReadError```?

**Comment by est31** [comment]
@sashahilton00 I've done a reexport here, not sure what you mean: https://docs.rs/lewton/0.8.0/src/lewton/lib.rs.html#97

**Comment by sashahilton00** [comment]
@est31 apologies, should have phrased it better; it was intended as a question as opposed to correction, the reason for which is that I had a look at Anton's code then the ogg docs here: https://docs.rs/ogg/0.5.0/ogg/ and noticed that in Anton's code it was ```ogg::reading::OggReadError``` whilst in the docs it did not look like ```ogg::OggReadError``` is implemented, but that ```ogg::reading::OggReadError``` is, hence I am wondering how the re-export in lewton works, given that ```ogg::OggReadError``` doesn't look to be implemented by the ```ogg``` crate?

**Comment by plietar** [comment]
The ogg crate already reexports `ogg::reading::OggReadError` as `ogg::OggReadError` in https://docs.rs/ogg/0.5.1/src/ogg/lib.rs.html#37

**Comment by sashahilton00** [comment]
Got it, thanks for clarifying.

**Comment by est31** [comment]
Yes, there is a two layered export. Sadly it doesn't really show up as reexport in the lewton docs, but like a native enum of the lewton crate: https://docs.rs/lewton/0.8.0/lewton/

I've [pushed a commit](https://github.com/RustAudio/lewton/commit/4aa6ea4fd578d1150bdc15225666bbd6cbc974ee) to fix this. The next version of lewton will display it as pub use.

**Comment by awiouy** [comment]
Rebased (against current master) to use lewton 0.8.0
lewton 0.8.0 requires Rust 1.20.0

We have two options:
1. Require Rust 1.18.0 and use https://github.com/librespot-org/librespot/pull/124/commits/e87b1f83d5d28b4802faf902c80768151872f580
2. Require Rust 1.20.0 and use https://github.com/librespot-org/librespot/pull/123/commits/99e7da562d454b1eac548c44be63030560115242

I prefer option 2 (simpler fix, moving forward).

**Comment by sashahilton00** [comment]
I would also rather update to 1.20.0 instead of pulling in more dependencies, though I have no idea how many people are on 1.18. Should ask in gitter. Anyone, please weigh in if you have a view.

**Comment by sashahilton00** [comment]
I'm going to leave this here for a day or so, so that anyone concerned about the version bump has the chance to weigh in.

**Comment by plietar** [comment]
I'm fine with 1.20.0. That's 3 version behind latest stable, which is enough IMO.

**Comment by sashahilton00** [comment]
No objections, so merging.

**Pull request merged**
