### PR TITLE
Add activate and load functions to `Spirc`

### PR DESCRIPTION
**Pull request by oeed**
This adds functions that activate (i.e. set 'is active' to true/makes it the active player) and load function to play specific tracks.

I've tried to follow the structure used in the rest of the struct, but if there are any issues I'm more than happy to change.

### CODE REVIEW

**Comment by kingosticks** [comment]
Sample program to test this at https://github.com/librespot-org/librespot/discussions/1072#discussioncomment-4187603

Maybe it should be a new example

**Comment by oeed** [comment]
Yep I can make a new example for it and will fix up the tests too.

**Comment by roderickvd** [comment]
Thanks! Could you fix the clippy lints and run `cargo fmt` if you haven't already?

**Comment by kingosticks** [comment]
If you rebase your changes on current dev that'll fix it for you @oeed

**Comment by oeed** [comment]
Great thanks, have done.

Once this is merged I have two additional PRs I'll post that add functions to `Spirc` to get its state and another that broadcasts `PlayerEvent`s from `Spirc`.

**Comment by roderickvd** [comment]
Sorry to ask you one last thing after I haven't responded for a week or so.
Could you update the changelog? All ready to merge then!

**Comment by oeed** [comment]
No problem @roderickvd, done

**Pull request merged**
