### PR TITLE
Fix latest clippy warnings on master

### PR DESCRIPTION
**Pull request by kingosticks**
Same as #1076 but without the `fmt` fix.

### CODE REVIEW

**Comment by kingosticks** [comment]
Right, and this is failing because we never got those dep updates. Sweet.

**Comment by roderickvd** [comment]
What do you propose?

**Comment by kingosticks** [comment]
Assuming we are keeping dev and master as are, I guess I need to grab the changes that were previously proposed.

**Comment by roderickvd** [comment]
I think @JasonLG1979 deleted that branch. Do you still have it locally?

**Comment by kingosticks** [comment]
Nope!

**Comment by JasonLG1979** [comment]
Update to latest version of Rust:
```
rustup update
```

Update dependencies:

```
cargo update
```

Check for clippy lints:

```
cargo clippy
```

Fix the lints.

Commit and push changes.

Let CI do it's thing and fix any random missed things when/if they show up, bump the min Rust version in CI as needed.

Rinse and repeat until CI passes.

In this particular case CI is failing because `time` requires `1.57` and CI is using `1.56`. If you bumped the min Rust version to `1.57` it might pass?

**Comment by roderickvd** [comment]
Closing this in favor of #1113

**Pull request closed without merging**
