### PR TITLE
include more metadata in track struct

### PR DESCRIPTION
**Pull request by eladyn**
Based on [this patch](https://github.com/librespot-org/librespot/commit/4f54dc8f5b5b9191899b9159801958cc3e748de9), this exposes some more metadata in the public `struct`s that is sent from Spotify.

### CODE REVIEW

**Comment by roderickvd** [comment]
This introduces one additional network request per artist and album right? We should consider the precedent here. Preemptively loading such things (it’s omnipresent throughout, not just the artist and album here) cost calls while not every caller will be interested in them. Such callers may want to take the extra step and explicitly retrieve it themselves.

Open to other ideas. 

Or are you saying this code was broken to begin with?

**Comment by eladyn** [comment]
> This introduces one additional network request per artist and album right?

As far as I know, the data returned by the API already includes everything required to build the "real" `struct`s instead of just a `SpotifyId`, so it doesn't need any further network requests. (A similar question was probably already asked on the original proposal: https://github.com/librespot-org/librespot/discussions/834#discussioncomment-1144122 :) )

Did this answer your question or did I misunderstand something?

**Comment by ashthespy** [comment]
>As far as I know, the data returned by the API already includes everything required to build the "real" structs instead of just a SpotifyId, so it doesn't need any further network requests. (A similar question was probably already asked on the original proposal: https://github.com/librespot-org/librespot/discussions/834#discussioncomment-1144122 :) )

Well - https://github.com/librespot-org/librespot/commit/4f54dc8f5b5b9191899b9159801958cc3e748de9  I am (99.8%) sure makes multiple network requests. 
Each `parse` call makes a request to go from `SpotifyId` -> Metadata

I believe this is now just abstracted out into a different trait? I haven't looked at the refactored code yet.

**Comment by ashthespy** [comment]
So I took a minute to look at the code again, and dumped the raw request from hm. The info is already there, no extra requests need to be made.  Also the code in player.rs uses the `get_audio_item` which decouples the parsing of these fields..

**Comment by roderickvd** [comment]
OK great. @eladyn if you would be so kind to target `dev` instead of `new-api`? I just promoted `new-api` to `dev` so that's where the development should now be.

**Comment by dnlmlr** [comment]
There might be an issue with what fileds are delivered by the API for those metadata structs. I didn't check this with the new api yet, but in the previous api metadata fields like that only give partial information. So for example the id was always present, but nothing more (which I assume is one of the reasons why almost everything is optionalin many fields).

**Comment by dnlmlr** [comment]
A solution to the not-yet-confirmed problem in my previous comment might be to make something like a `LazyArtist` or `PartialArtist` that is unloaded (only id and maybe the name is present as well) by default, but can be easily loaded:
```rust
enum LazyArtist {
  Unloaded {
    id: SpotifyId,
    name: Option<String>,
  },
  Loaded(Artist),
}
```
this *lazy* or *partial* struct would then have a `load` function that swaps the variant from unloaded to loaded. And to get the id easily there you could add a `get_id()` function that returns the id from either of the types without matching.

(This whole comment should maybe be a separate issue, actually)

**Comment by roderickvd** [comment]
This should be still the same as on the old API. The endpoints and transport changed, but not the output of the metadata. Does that hold off merging this PR?

**Comment by dnlmlr** [comment]
Ok I did some testing with the changes in this PR when  querying Track metadata:
- The Album is beeing correctly parsed from the message
- The following fields in for the Album are filled with *non-default values*:
  -  `id`, `name`, `artists`, `album_type`, `label`, `date` and `cover_group`
- All other fields are not present and silently filled with the default values
- For the Artist it is pretty much the same, but since currently we only have `id`, `name` and `top_tracks` , only `top_tracks` is missing

I am currently implementing the missing metadata for Artist, so there would be a lot more stuff silently defaulting in Artist as well if all the metadata is parsed.

So there is definitely not the full `Artist` or `Album` metadata present in the queries for other types, but we get partial information that is more then just `id`. The hard question again is what can be expected to be there? Imho a partial / lazy wrapper for such types would be the best option. 
But since this PR does work without the need for extra requests and you still have safe access to the id like before I guess there is no reason to block it

**Comment by roderickvd** [comment]
:+1: let's go

**Pull request merged**
