### PR TITLE
Add optional linear volume contol

### PR DESCRIPTION
**Pull request by thekr1s**
implement issue https://github.com/librespot-org/librespot/issues/187

### CODE REVIEW

**Comment by ComlOnline** [comment]
@thekr1s The only reason the build failed is because of rustfmt. If you have a look at the travis build log you can see what needs changing.

**Comment by sashahilton00** [comment]
Please hold off merging, will review later.

**Comment by sashahilton00** [comment]
Looks good, only question, why have permissions on the files changed from 644 to 755?

**Comment by thekr1s** [comment]
No reason for changing the permissions.. I messed-up using mixed windows and linux....
I reverted the permission changes...

**Comment by sashahilton00** [comment]
Thanks for adding this. Will update wiki with new option. Closes #187. @Gongreg you should now be able to use ```--linear-volume``` with the latest commit.

**Pull request merged**
