### PR TITLE
Update bug_report.md

### PR DESCRIPTION
**Pull request by kingosticks**
Better bug reports please, stop removing context from logs

### CODE REVIEW

**Comment by roderickvd** [comment]
Thanks, I agree. How about also asking to verify they did a little due diligence? The duplicate issues, that could easily have been detected by looking around for 30 seconds, are also a bit tiring.

**Comment by roderickvd** [comment]
Why close?

**Comment by kingosticks** [comment]
Crap, I was cleaning up old branches and this badly named GitHub one got trashed !

**Comment by kingosticks** [comment]
I'll redo it later

**Pull request closed without merging**
