### PR TITLE
Add SinkActive|SinkInactive events

### PR DESCRIPTION
**Pull request by ashthespy**
Adding sink events to to the revamped `PlayerEvent`

### CODE REVIEW

**Comment by kaymes** [comment]
Just a thought: a use case for this event would be to allow the calling code to free the audio device. On a system that combines multiple players one might want to stop other players before the sink gets opened. In this case a notification isn't much use because librespot already attempted to open the device by the time the notification is processed.

Maybe the sink events should be done by a different mechanism that is blocking to allow calling code to perform actions before the sink is being opened and after it was closed.

On a library level this could be done by allowing to register a callback which is called blockingly before sink opening and after sink closing. In the main binary said callback would then call the notification script and wait for its completion.

Since this has the potential to slow delay playback there should be a switch to make this event optional.

**Comment by ashthespy** [comment]
Indeed, the use case for this is to let other players on the system use the audio device. Currently management of the players and sinks is handled externally in my use case (mpd + librespot). Given that in most cases with multiple players, there is going to an monitoring script/daemon, not sure if we need to add a mechanism to wait for the sink to `librespot`?

**Comment by kaymes** [comment]
Well, if mpd is running and one starts playback on librespot, doesn't the monitoring script have to stop mpd before librespot can get the sink? Thus, librespot would have to wait for said script.

I just had a play around with making a blocking event. I'll put it into another PR for discussion.

**Comment by ashthespy** [comment]
> Well, if mpd is running and one starts playback on librespot, doesn't the monitoring script have to stop mpd before librespot can get the sink? Thus, librespot would have to wait for said script.

True, how I handle this is to stop mpd when a track load event is triggered. But then again, as you point out, these are all workarounds..

**Comment by kaymes** [comment]
I just put the a blocking version in #449. Have a look what you think.

**Pull request closed without merging**
