### PR TITLE
Update to GStreamer bindings version 0.18 and various cleanups to the GStreamer audio backend

### PR DESCRIPTION
**Pull request by sdroege**
See individual commits for details.

### CODE REVIEW

**Comment by sdroege** [comment]
New GStreamer bindings need Rust 1.56 at least

**Comment by JasonLG1979** [comment]
Looks good except that `start`, `stop` and `write_bytes` all return `SinkResult<()>` so errors should be returned. Don't use `expect`. Ideally `open` would also return a result and in the future the plan is to make it, so right now the excepts are unavoidable.

**Comment by sdroege** [comment]
I was thinking of updating that before submitting the PR but assumed that there was a reason to use `except()` here instead of properly returning errors. If that's not the case I can update it one of these days.

**Comment by sdroege** [comment]
Changed that accordingly, and also caught asynchronous errors now.

**Comment by JasonLG1979** [comment]
> I was thinking of updating that before submitting the PR but assumed that there was a reason to use `except()` here instead of properly returning errors. If that's not the case I can update it one of these days.

I think the general though around here is that if you know enough to write an except message you know enough to to be able to return a meaningful error message. Just panicking takes the choice away from the caller as to how to handle the error. They may not want to just explode on error.

**Comment by JasonLG1979** [comment]
Unwraps are also a no-no. Although in cases in your new code it's for an option, so maybe Ok.

I also just tried to build your branch. This will never pass CI as glib 15 depends on nightly.

**Comment by sdroege** [comment]
> This will never pass CI as glib 15 depends on nightly.

As I wrote above, it needs at least Rust 1.56. Not nightly.

> Unwraps are also a no-no.

The only `unwrap`s are for locking the mutex which would only fail if a thread panicked before while the mutex was locked. If you want to handle that gracefully, good luck. That requires more changes than returning an error from here.

In any case, as there doesn't seem to be any interest in this let's just close this here. I only did the changes because I saw librespot is depending on an old version of the GStreamer bindings after I released a new version of those, and then saw that the GStreamer usage is minimal but rather wrong and easy to improve.

I'm not even using the library :shrug:

**Comment by roderickvd** [comment]
> In any case, as there doesn't seem to be any interest in this let's just close this here.

There is no need for that. Like I said in another PR, please don't take offense from slower-than-usual response from my side. I'm moving into a new home so am pressed for time these weeks.

> I only did the changes because I saw librespot is depending on an old version of the GStreamer bindings after I released a new version of those, and then saw that the GStreamer usage is minimal but rather wrong and easy to improve.

Your improvements are very much appreciated. A few questions:

> As I wrote above, it needs at least Rust 1.56. Not nightly.

I'd like some input from others on this, e.g. @kingosticks or @ashthespy? Recently I bumped the MSRV to 1.53 (June 2021) for Symphonia which I didn't really feel like doing, but saw no other way to get FLAC in natively. Now on the one hand you could say, as we're deviating from 1.48 (which is in stock Debian) anyway, why not go 1.56 (November 2021). On the other hand you could make an argument for staying a bit off the bleeding edge... but perhaps that's just sentiment?
 
> > Unwraps are also a no-no.
> 
> The only `unwrap`s are for locking the mutex which would only fail if a thread panicked before while the mutex was locked. If you want to handle that gracefully, good luck. That requires more changes than returning an error from here.

Please change to use `parking_lot::Mutex` which is now in `new-api`. That can't be poisoned and so doesn't require the `unwrap`. 
 
> I'm not even using the library 🤷

Thanks for your efforts. This is a nice clean-up but let's discuss the MSRV first.
I'd appreciate to reopen this but will leave that up to you.

**Comment by roderickvd** [comment]
Two other questions (code reviews don't seem to work -- maybe because the PR is closed?):

1. How does this work with endianness? Does something like `gst_audio::AUDIO_FORMAT_S32BE` exist that you could use?
2. In `Drop` you removed the transition first to `Ready` and then to `Null`, which I recently added because of the [documented possible state transitions](https://gstreamer.freedesktop.org/documentation/additional/design/states.html?gi-language=c) that I added as a code comment (now also removed). The transition directly to `Null` is not specified. Is that a documentation error or best to indeed follow the transitions as they were?

**Comment by sdroege** [comment]
> There is no need for that. Like I said in another PR, please don't take offense from slower-than-usual response from my side.

That's perfectly fine, my reason for closing this was because there was a response and that didn't appear like things would move forward in a useful way.

I can re-open this and move it to parking_lot if there is any interest in that. For the MSRV I don't have any opinion, it depends on what your constraints are.

> Please change to use `parking_lot::Mutex` which is now in `new-api`. That can't be poisoned and so doesn't require the `unwrap`.

Which of course also means that the mutex is not poisoned on panics and you could end up with invalid states. Not a problem in this case though.

> How does this work with endianness? Does something like `gst_audio::AUDIO_FORMAT_S32BE` exist that you could use?

The old code assumed native endianness so I kept it at that. If it should've been always big endian then the old code was wrong and indeed the correct format for that should've been used.

> In `Drop` you removed the transition first to `Ready` and then to `Null`, which I recently added because of the [documented possible state transitions](https://gstreamer.freedesktop.org/documentation/additional/design/states.html?gi-language=c) that I added as a code comment (now also removed). The transition directly to `Null` is not specified. Is that a documentation error or best to indeed follow the transitions as they were?

There is no transition directly from e.g. paused to null, but GStreamer will do all the intermediate state changes for you.

See also [here](https://gstreamer.freedesktop.org/documentation/additional/design/states.html#setting-state-on-elements):

> When changing the state of an element all intermediate states will also be set on the element until the final desired state is set.

**Comment by kingosticks** [comment]
The state of Rust packaging in Debian is a mess, you have to rustup to do pretty much anything so I think the version bump is OK. 

And since this backend is an example as much as anything else, it's great to have it fixed up by an expert and done properly. LGTM, let's merge when you get a chance (and good luck with the house move)!

**Comment by sdroege** [comment]
> The old code assumed native endianness so I kept it at that. If it should've been always big endian then the old code was wrong and indeed the correct format for that should've been used.

To add to this, the `gst_audio::AUDIO_FORMAT_S32` (etc) constants are doing exactly what the old code here did, just moving the conditional compilation out of your code. On little endian systems they map to `gst_audio::AudioFormat::S32LE`, on big endian systems to `S32BE`.

**Comment by roderickvd** [comment]
> I can re-open this and move it to parking_lot if there is any interest in that. For the MSRV I don't have any opinion, it depends on what your constraints are.

OK, let's go for it.

> There is no transition directly from e.g. paused to null, but GStreamer will do all the intermediate state changes for you.
> 
> See also [here](https://gstreamer.freedesktop.org/documentation/additional/design/states.html#setting-state-on-elements):
> 
> > When changing the state of an element all intermediate states will also be set on the element until the final desired state is set.

OK, sounds good!

> > The old code assumed native endianness so I kept it at that. If it should've been always big endian then the old code was wrong and indeed the correct format for that should've been used.
> 
> To add to this, the `gst_audio::AUDIO_FORMAT_S32` (etc) constants are doing exactly what the old code here did, just moving the conditional compilation out of your code. On little endian systems they map to `gst_audio::AudioFormat::S32LE`, on big endian systems to `S32BE`.

OK trice 😆

**Comment by sdroege** [comment]
Seems like this can't be re-opened. Continuation here: https://github.com/librespot-org/librespot/pull/964

**Pull request closed without merging**
