### PR TITLE
Fix fixed volume with hardware mixer.

### PR DESCRIPTION
**Pull request by JasonLG1979**
fixes https://github.com/librespot-org/librespot/issues/1008

### CODE REVIEW

**Comment by JasonLG1979** [comment]
Once it's been tested by someone else and is confirmed to also work for them and I'm sure there's no more code changes left I'll add to the change log.

**Comment by JasonLG1979** [comment]
After this is merged and `new-api` is caught up I think I'm going to look into *"de-panicking"* our `Mixer` implementation in the `new-api` branch.

It's not something I want to do in the current `dev` branch though, since it ***will*** break API, but it shouldn't be much different than messing with the `alsa` backend.

I'll probably model it after the audio backends. `MixerError`, `MixerResult` and so on.

**Comment by roderickvd** [comment]
Looks good to me but I no longer have a DAC with Alsa hardware mixing support, so I cannot verify.

**Comment by JasonLG1979** [comment]
> Looks good to me but I no longer have a DAC with Alsa hardware mixing support, so I cannot verify.

I will also test on the integrated audio and my JDS Labs OLDAC, but it would be really nice to have independent confirmation from people using a variety of DAC's.

**Comment by JasonLG1979** [comment]
All things being equal though, this fixes a logic error. It ***should*** work exactly the same on any properly implemented DAC. As per usual we won't actually find out how true that is after it's merged and it gets ***scream tested***,lol!!!

**Comment by roderickvd** [comment]
Seeing no one else is chiming in, if you can update the changelog then let's get this in.

**Pull request merged**
