### PR TITLE
Fix #209 - clean up zombies of 'onevent' programs

### LINKED ISSUE #209: --onevent PROGRAM
Program called onevent parameters becoms zombie, this behavior creates long list zombies after long time using librespot

### PR DESCRIPTION
**Pull request by erkia**

### CODE REVIEW

**Comment by michalfita** [comment]
This doesn't fix anything related to zombies, moreover it's going to cause new thread created for each program launched, piling up memory usage.

`wait()` on `Child` does effectively the same job as `status()` does on `Command`. Be **advised** not to merge this.

Proper fix should include allowed configurable timeout of execution of the program launched as result of the event, and then delay in thread for that timeout, then `try_wait()` and:
* if `Ok(Some(status))` is returned log at Debug level and finish the thread gracefully
* if `Ok(None)` is returned, then the thread should log at Error level the program hasn't been finished in desired time and should make attempt to `kill()` with proper handling of result and logging; leave the thread in case of failed kill attempt as there is nothing we can do.

Otherwise it's going to mask the problem, not solve it.

**Comment by erkia** [comment]
A proper fix would use some better communication mechanism than firing up external programs to notify about events. This pull request is a quick fix for the current situation - a complete lack of child handling and piling up zombie processes - while retaining the non-blocking behaviour. When this basic thing is fixed, any improvements are welcome.

**Comment by wfraser** [comment]
Another option is to make a custom Future that calls `waitpid` with the `WNOHANG` option, and only resolves when the child exits. Then spawn that onto the main event loop whenever a child process is spawned, and it'll periodically check if it exited.

**Comment by erkia** [comment]
Closing this in favor of #255

**Pull request closed without merging**
