### PR TITLE
Rewrite and simplify Player

### PR DESCRIPTION
**Pull request by udoprog**
Hey,

This is a mostly complete rewrite of how logic is handled in the Player.

* There are no dead code paths causing the player thread to exit sporadically. The only way that a player thread currently can shut down is either for the commands channel to disconnect or for it to panic.
* The various player states have been simplified and documented. In particular the code has been rewritten to not make use of an `Invalid` state any longer. The `EndOfTrack` state has been removed.
* The loaded track is no longer stored in the player state. Instead it is stored in an `loaded_track: Option<LoadedTrack>`. This makes it clearer what the lifetime of a `loaded_track` is and affords us to implement some things decoupled from the state.
* The player has no interim panics. Instead all errors are propagated as errors. If an error reaches the thread it will panic.
* The `end_of_track` oneshot is called in the `Drop` implementation of `LoadedTrack` to make sure we don't forget about it. Hopefully this means we can write clients without having to match against `Err(Cancelled)` in the receiving end.

This was also built on top of a previous patch which incorporated linear volume control:

This adds linear volume control at the same stage as normalization happens and adds player events to control the volume directly.

I'm pretty sure this can be implemented somewhere in the audio backend, as an audio filter, or as part of the mixer. But this avoids iterating over the samples twice if normalization happens anyways by multiplying it with the normalization factor.

### CODE REVIEW

**Comment by sashahilton00** [comment]
Thanks for the work, this looks fairly substantial, so I'm probably not going to be able to review it in the near future and test it out, if one of the other colaborators wants to step in, that'd be great.

**Comment by udoprog** [comment]
I'd like to clarify why I did this. I was testing a player that I'm working with for stability by letting it play for a couple of hours. After a while it randomly stopped playing without notifying that the loaded track had ended. I was trying to fix the issues I found with this rewrite and I'm now stability testing this patch again.

**Comment by sashahilton00** [comment]
Are you sure it's not because of reconnection not being implemented? every issue opened about tracks dropping out seems to come from us not handling reconnection atm.

**Comment by udoprog** [comment]
Can't say for sure. I was hoping this would improve available diagnostics so I could say for sure. All I know for sure is that the oneshot channel wasn't called even though the player had played the full track.

**Comment by sashahilton00** [comment]
If it is the network, what may be happening is that librespot attempts to retrieve the track, but due to there being no active session, due to connection dropout, the client hangs, the sender isn't triggered, and a restart is required.

**Comment by udoprog** [comment]
Ah. There's two things which make me think my particular problem wasn't reconnect issue. It always hangs at the end of a track. And I'm able to make it play again by loading a new track.

I have not seen this after the rewrite in this PR. Before it happened maybe once every 30 minutes. But I'll keep testing it.

**Comment by sashahilton00** [comment]
If you can make it play again by loading a new track, it's definitely not a connection issue, as connection issues ultimately cause a crash/necessary restart.

**Comment by sashahilton00** [comment]
Will try and test this tonight and let you know how it goes. Let me know when you're done adding commits and will review & merge.

**Comment by sashahilton00** [comment]
Just tested it, I get some odd behaviour with this rewrite though. When starting a song on iOS/desktop and switching to librespot, the playback starts, but then switching back to the official client causes librespot to load the next track and play that, whilst the official client is playing the current song. Quitting the main client and relaunching also does not cause it to sync up with librespot's current state.

**Comment by udoprog** [comment]
@sashahilton00 could this be because the PlayerEvent signals have been changed here:
https://github.com/librespot-org/librespot/pull/300/files#diff-f582d878256027ce3c970a26de626b55R50

Now these are only emitted when a track is loaded, unloaded, or changed. But not when the player for example pauses?

**Comment by sashahilton00** [comment]
Thing is, changing device should trigger Stop event, as opposed to pause I believe.

**Comment by udoprog** [comment]
Could you explain a bit more 1) what it is that you are doing and 2) what you expect to happen and why? I'm not familiar with the example client (I only use the Player directly), but maybe I can help troubleshoot.

**Comment by StopMotionCuber** [comment]
Didn't test myself, but I will present what I think is the problem:

You have 2 Spotify instances running, one is librespot and the other a desktop client.


Steps to reproduce:

1. Play music on desktop client
2. Switch Playback device to librespot client
3. Switch back Playback device to desktop client

Expected behavior: Client should always play the same song

Actual behavior: After 2nd switch of playback device the next song is played by the desktop client


Hope I got the error right

**Comment by sashahilton00** [comment]
Sure, the steps taken were the following:

1. Run `cargo build`
2. Run librespot
3. Start song on desktop client.
4. Switch playback to librespot.
5. Switch playback back to desktop.
6. At this point, the desktop continues playback as expected, but librespot skips to the next song in the queue and starts playing, so 2 songs are playing at the same time.

**Comment by sashahilton00** [comment]
Given that this is still broken and there haven't been any new commits, shall I close it?

**Comment by udoprog** [comment]
Ah, yeah sure. I'm not working on this any longer!

**Pull request closed without merging**
