### PR TITLE
Adjust arg types of `Credentials::with_blob`

### PR DESCRIPTION
**Pull request by Johannesd3**
... to avoid redundant utf-8 checking

### CODE REVIEW

**Comment by Johannesd3** [comment]
3x error while caching...

**Comment by roderickvd** [comment]
Seems smart. Maybe add a comment surrounding that code for future reference? (other than `git blame`)

**Comment by roderickvd** [comment]
@Johannesd3 OK to merge?

**Comment by Johannesd3** [comment]
Yes.

**Pull request merged**
