### PR TITLE
Snapcraft recipe to auto build snap package of Librespot example app

### PR DESCRIPTION
**Pull request by keshavbhatt**
Hello! I added snapcraft recipe to build librespot example app snap to the snap store - see https://snapcraft.io/docs/releasing-your-app if you want publish librespot client app to snap store and reach million more Linux users :)

This merge simply adds the snap build recipe to your repo which will be picked up by the auto-build system of snapcraft.io if you register a namespace librespot there.

If you want me to publish on your behalf and manage the snap for your repo in Snapstore let me know. The published app can be transferred to the real owner(you) anytime. 

Thanks for making a great Spotify client library & app <3

### CODE REVIEW

**Comment by roderickvd** [comment]
Thanks for your PR. I have no experience with Snapcraft, can anyone else chime in whether we'd want this or not? Maybe also in relation to #727.

**Comment by JasonLG1979** [comment]
@roderickvd I have no experience with snap either but form what I understand it's much like flatpak in that it's pretty common for the flatpak stuff to be a separate repo not necessarily maintained by the main project. That would prevent you guys from having to maintain something you don't use and really don't know anything about.

**Comment by roderickvd** [comment]
I'm still on the fence and leaning towards not doing this. I mean we package and distribute through `crates.io` which is fine for our purposes. We then get picked up by other applications that redistribute by their own means, or by audio distributions like moOde. These channels make more sense to me then redistributing `librespot` as-is over Flatpak or Snap which seem more geared towards end-user applications.

If there are others who want to repackage `librespot` then that's more than fine but the way I see it, that should not impose a maintenance requirement in our code tree.

Any arguments in the other direction?

**Comment by roderickvd** [comment]
If there are no other takers, I will be respectfully closing this PR. Thanks for your contribution nonetheless. Perhaps you could do the same for the downstream packages, that should be better suited to be offered as an integration application? If anyone else feels differently then we can reconsider it.

**Pull request closed without merging**
