### PR TITLE
Further progress on tokio migration

### PR DESCRIPTION
**Pull request by Johannesd3**
This bundles #668 and #683 into one PR (I'm sick of multiple parallel PRs).

* Merge the latest `dev` into `tokio_migration`
* Fix clippy warnings and formatting.
* Get rid of most of the `util` module (Formerly #668).
* Improve CI (after fixing errors which would prevent it from succeeding). In contrast to the solution presented in #683, the macOS build was removed because of strange errors as result of caching the target directory.

### CODE REVIEW

**Comment by roderickvd** [comment]
> I'm sick of multiple parallel PRs

I hear you, man 😆 

By the way I just picked up Rust 1.51 and see that Rust 2021 introduces some new warnings (some of them by default, not clippy). I'll jump in after submitting dithering and noise shaping.

**Comment by Johannesd3** [comment]
@roderickvd You're now an expert in testing all those backends, I suppose. Could you verify that everything works as intended and I did not make any mistakes while merging?

**Comment by Johannesd3** [comment]
I don't know exactly what happened, but [this assertion](https://github.com/Johannesd3/librespot/blob/0ba6f14eca246c11990977f245666497c876a42d/core/tests/connect.rs#L16) failed. Maybe the Spotify servers sent an invalid response?

**Comment by roderickvd** [comment]
> @roderickvd You're now an expert in testing all those backends, I suppose. Could you verify that everything works as intended and I did not make any mistakes while merging?

All tested, all good! (with the same caveats as in #660 -- though Alsa on Rodio is working now with the latest cpal and Rodio) That's some amazingly swift work man.

Minor point I just noticed:

https://github.com/librespot-org/librespot/blob/3e9aee1d46e9bc90d2b7c321a5f8d7c823c98788/playback/src/audio_backend/mod.rs#L118-L119

If Rodio is intended to be the default, best to move it to the top of the list. If no backend is specified on the command line, it picks the first. This is not specific to your work but while you're at it...

**Pull request merged**
