### PR TITLE
core API: the next batch

### PR DESCRIPTION
**Pull request by awiouy**
Builds upon #141 
Messages of relevant commits start with `Core API:`

### CODE REVIEW

**Comment by awiouy** [comment]
Done for today. Please review.

**Comment by sashahilton00** [comment]
Looks fine, I do wonder where Bitrate should be implemented, since the core is responsible for retrieving the audio, and playback is meant to be essentially audio processing, but having looked over the playback crate, there is enough other stuff going on in there with regards to handling decoding/controls/etc. that it's probably fine. perhaps at a later date we should look into separating playback and sinks into seperate crates, then just providing PCM to the sink crate. anyway, it's fine for now, will merge once Travis is done, it's taking it's sweet time tonight...

**Comment by plietar** [comment]
> core is responsible for retrieving the audio

`librespot-audio` is responsible for that. However the API exposed by `audio` uses `FileId` directly.
Having it `Bitrate` in `playback` is fine.

**Comment by sashahilton00** [comment]
Great. Just merged #111 and it's conflicting with this one. Are you ok to work your git mojo to resolve this, or shall I just revert #111 and merge this first, then deal with #111?

**Comment by sashahilton00** [comment]
Actually, think I might have it, one sec

**Pull request closed without merging**
