### PR TITLE
Eliminate most uses of util module

### PR DESCRIPTION
**Pull request by Johannesd3**
Seems as if Diffie Hellman works exactly the same way in core and discovery, but except of the constants the code wasn't reused until now. 

Sequel: Without the use of `powm` in discovery, it became unnecessary that this function is exposed in the util module. Looking through the other uses of `util`, I realized that most of them are easy to replace. The last remaining item in `util` is `SeqGenerator` as it is used once in `spirc.rs`.

### CODE REVIEW

**Comment by sashahilton00** [comment]
Why is the MSRV being bumped to 1.45?

**Comment by Johannesd3** [comment]
IIRC it's the MSRV of Tokio 1.0

**Comment by sashahilton00** [comment]
Ah right, ignore my previous comment, missed that tihs was a PR against the `tokio_migration` branch.

**Comment by roderickvd** [comment]
Also expect a new Debian stable to land in July with Rust 1.48.

**Pull request closed without merging**
